/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Reports that the process is running. It deliberately touches no
         *     dependency: a liveness probe that fails because Postgres is briefly
         *     unreachable causes a restart loop instead of reporting a degraded
         *     dependency.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Checks every dependency the process needs to serve traffic: the database,
         *     the queue, and the configured object store. Returns 503 with the failing
         *     check named when any is unreachable, so a deploy fails visibly rather than
         *     serving errors.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Creates a server-side session and sets the session cookie.
         *
         *     A wrong password and an unknown account return exactly the same error.
         *     Distinguishing them tells an attacker which accounts exist.
         *
         *     Repeated failures lock the account for a configured period. The lockout is
         *     durable, so a restart does not unlock it, and an admin can clear it.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Destroys the session row, so the cookie is useless immediately.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation and set a password
         * @description Single use, and expires. The token is stored hashed, so a leaked database
         *     yields no working invitation links.
         *
         *     Password rules come from the settings registry rather than being hardcoded
         *     in the client, so the message names the rule that failed.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Requires the current password. Every other session for this user is
         *     destroyed, because a password change is the one moment a user expects
         *     other devices to be signed out.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a user
         * @description Creates the user with no password and returns a single-use invitation link.
         *
         *     The link is returned in the response and shown once, because email is an
         *     optional integration: on a zero-integration install there is no SMTP to
         *     send it, and the admin passes it on by whatever means they already use. If
         *     SMTP is configured the platform also sends it.
         */
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userID}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's role
         * @description An admin cannot change their own role. Locking the last admin out of their
         *     own instance is a support call nobody wants, and the check is cheap.
         *
         *     Every session belonging to the user is rotated, so a role change takes
         *     effect on the next request rather than at the end of a session.
         */
        put: operations["setUserRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userID}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enable or disable a user
         * @description Disabling destroys every session the user holds, so access ends
         *     immediately rather than when a token would have expired.
         */
        put: operations["setUserStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign a user out everywhere
         * @description Deletes every session row for the user. This is why sessions are
         *     server-side: an offboarded employee's access ends here, with no token TTL
         *     to wait out.
         */
        delete: operations["revokeUserSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userID}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear a login lockout
         * @description Clears the lockout left by repeated failed sign-ins, without waiting for it
         *     to expire.
         */
        post: operations["unlockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The single error shape. Produced only by the mapper in
         *     internal/platform/httpx, so every failure looks the same.
         */
        Error: {
            /**
             * @description Stable and machine readable. Branch on this, never on message. Every
             *     value is catalogued in docs/error-codes.md.
             * @example target_host_not_allowed
             */
            code: string;
            /**
             * @description Safe to show a user, and says what to do next.
             * @example Host "api.example.test" is not on this project's allowlist. Add it in Settings, Project, Targets.
             */
            message: string;
            /**
             * @description Field-level context for inline rendering. Never carries a secret.
             * @example {
             *       "host": "api.example.test"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * @description Present only on a 500. The handle between what the user saw and the
             *     full wrapped cause in the log, which is never returned.
             * @example 9f2c1a7e
             */
            incidentId?: string;
        };
        /**
         * @description How every stored secret reads back. The plaintext is never returned by any
         *     code path, so a UI offers Replace rather than edit.
         * @example {
         *       "isSet": true,
         *       "updatedAt": "2026-08-10T09:14:22Z",
         *       "hint": "sk-a…XyZ4"
         *     }
         */
        SecretRead: {
            isSet: boolean;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @description First and last few characters only, enough to recognise which key is stored.
             * @example sk-a…XyZ4
             */
            hint?: string;
        };
        /**
         * @description Pass as cursor to fetch the next page. Null or absent means the last page.
         * @example eyJjIjoiMjAyNi0wOC0xMFQwOToxNDoyMloifQ
         */
        NextCursor: string | null;
        /**
         * @description Returned with 202 by every long operation. The client subscribes to the
         *     job rather than waiting: the user may close the browser and be notified
         *     when the chain finishes.
         * @example {
         *       "jobId": "6f1c9d2e-6b1a-4f7a-9c3e-2b8d5a4c1e77",
         *       "status": "queued",
         *       "eventsUrl": "/api/v1/jobs/6f1c9d2e-6b1a-4f7a-9c3e-2b8d5a4c1e77/events"
         *     }
         */
        JobReference: {
            /** Format: uuid */
            jobId: string;
            status: components["schemas"]["JobStatus"];
            /**
             * @description SSE endpoint for live status and the event log.
             * @example /api/v1/jobs/6f1c.../events
             */
            eventsUrl?: string;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * @description The four platform roles. Authorisation is enforced per route group on the
         *     server; a client uses this only to decide what to render.
         * @enum {string}
         */
        Role: "admin" | "qa_lead" | "qa_engineer" | "viewer";
        /**
         * @description A user as the API returns them. There is no password field in this schema,
         *     so a hash cannot appear in a response even by accident
         *     (backend-standards.md 4).
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /**
             * @description IANA name. All timestamps are stored UTC and displayed in this zone (NFR-7).
             * @example Asia/Kolkata
             */
            timezone: string;
            disabled: boolean;
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UserPage: {
            items: components["schemas"]["User"][];
            nextCursor?: components["schemas"]["NextCursor"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AcceptInviteRequest: {
            token: string;
            name?: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        InviteUserRequest: {
            /** Format: email */
            email: string;
            name?: string;
            role: components["schemas"]["Role"];
        };
        /**
         * @description Returned once, when the invitation is created. The token is stored hashed,
         *     so this link cannot be produced again: a lost link is replaced by issuing a
         *     new invitation.
         */
        Invitation: {
            user: components["schemas"]["User"];
            /**
             * @description Send this to the invitee. Shown once.
             * @example http://localhost:3000/accept-invite?token=9f2c1a7e...
             */
            acceptUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @enum {string} */
        CheckStatus: "ok" | "failing" | "not_configured";
        DependencyCheck: {
            /** @example object_store */
            name: string;
            status: components["schemas"]["CheckStatus"];
            /**
             * @description Which implementation answered, or why it failed. Never contains a
             *     credential.
             * @example local-disk
             */
            detail?: string;
        };
        Liveness: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            checks: components["schemas"]["DependencyCheck"][];
        };
    };
    responses: {
        /** @description The request is structurally valid but not permitted. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "validation_failed",
                 *       "message": "Email is not valid.",
                 *       "details": {
                 *         "field": "email"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unauthenticated",
                 *       "message": "Sign in to continue."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but not permitted. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "role_required",
                 *       "message": "This action requires the Admin role."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Not found, or not visible to this caller. The two are deliberately
         *     indistinguishable.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "project_not_found",
                 *       "message": "Project not found."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "project_archived",
                 *       "message": "This project is archived and is read-only. Unarchive it to make changes."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited. Retry-After is set. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "rate_limited",
                 *       "message": "Too many requests. Wait a moment and try again.",
                 *       "details": {
                 *         "retryAfterSeconds": 30
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description An unexpected failure. Carries an incident ID and nothing else; the cause
         *     is in the structured log against that ID.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "internal_error",
                 *       "message": "Something went wrong on our side.",
                 *       "incidentId": "9f2c1a7e"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Page size. Every list has a hard maximum; there is no unbounded list. */
        Limit: number;
        /** @description Opaque cursor from a previous response's nextCursor. Do not construct one. */
        Cursor: string;
        UserID: string;
        /**
         * @description Supported on every mutating endpoint a CI system or webhook can retry.
         *     Replaying the same key with the same body returns the original result;
         *     reusing it with a different body is a conflict.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "checks": [
                     *         {
                     *           "name": "database",
                     *           "status": "ok"
                     *         },
                     *         {
                     *           "name": "queue",
                     *           "status": "ok"
                     *         },
                     *         {
                     *           "name": "object_store",
                     *           "status": "ok",
                     *           "detail": "local-disk"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one dependency is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable",
                     *       "checks": [
                     *         {
                     *           "name": "database",
                     *           "status": "ok"
                     *         },
                     *         {
                     *           "name": "queue",
                     *           "status": "failing",
                     *           "detail": "dial tcp 127.0.0.1:56379: connect: connection refused"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "max@hyscaler.com",
                 *       "password": "correct-horse-battery-staple"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. The session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email or password is incorrect. Deliberately identical for an unknown account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "invalid_credentials",
                     *       "message": "Email or password is incorrect."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The account is disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "account_disabled",
                     *       "message": "This account is disabled. Ask an admin to re-enable it."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Locked after repeated failures. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "account_locked",
                     *       "message": "Too many failed sign-in attempts. This account is locked temporarily.",
                     *       "details": {
                     *         "retryAfterSeconds": 900
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Password set and signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The invitation is invalid or expired, or the password is too weak. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "invite_invalid",
                     *       "message": "This invitation link is invalid or has expired. Ask an admin to send a new one."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. Other sessions were destroyed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f9a2b41-6c7d-4e8f-9a1b-2c3d4e5f6a7b",
                     *       "email": "max@hyscaler.com",
                     *       "name": "Max",
                     *       "role": "admin",
                     *       "timezone": "Asia/Kolkata",
                     *       "disabled": false,
                     *       "createdAt": "2026-08-01T09:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Page size. Every list has a hard maximum; there is no unbounded list. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous response's nextCursor. Do not construct one. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Supported on every mutating endpoint a CI system or webhook can retry.
                 *     Replaying the same key with the same body returns the original result;
                 *     reusing it with a different body is a conflict.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "newjoiner@hyscaler.com",
                 *       "name": "New Joiner",
                 *       "role": "qa_engineer"
                 *     }
                 */
                "application/json": components["schemas"]["InviteUserRequest"];
            };
        };
        responses: {
            /** @description Invited. The link is shown once and not retrievable later. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description An account with that email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "email_already_taken",
                     *       "message": "An account with that email already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    setUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Role changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Not an admin, or an attempt to change your own role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "cannot_change_own_role",
                     *       "message": "You cannot change your own role. Ask another admin."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disabled: boolean;
                };
            };
        };
        responses: {
            /** @description Status changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description How many sessions were destroyed. */
                        revoked: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    unlockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lockout cleared, or there was none. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
