// Package uitests turns a discovered flow graph into Playwright specs, and holds the
// selector policy that decides whether a generated spec is worth keeping (F-6.4,
// F-6.12, BE-7.4).
//
// The policy is the interesting part, and it is code rather than a line in a prompt on
// purpose. "Prefer data-testid" as an instruction produces a suite that mostly prefers
// it; a suite where one spec in twenty locates a button by `div:nth-child(3) > button`
// is a suite that breaks the first time somebody adds a wrapper div, and it breaks in a
// way that looks like a real failure. So the rule is enforced after generation, on
// every selector, and a spec that violates it is **rejected and regenerated** rather
// than merged with a warning (BE-7.4.2).
//
// The order the policy prefers, strongest first:
//
//	getByTestId          a contract between the app and its tests
//	getByRole + name     the accessible name, which is what a user reads
//	getByLabel           a form control's label
//	getByPlaceholder     weaker: placeholders are copy and copy changes
//	getByText            weakest of the acceptable ones: also copy
//
// and what it refuses outright: anything positional, anything indexed by number, and
// anything reaching through the DOM's shape rather than its meaning.
package uitests

import (
	"fmt"
	"regexp"
	"strings"
)

// Violation is one selector the policy refuses.
type Violation struct {
	// Line is 1-based, so it can be quoted straight back to a model or shown in a UI.
	Line int

	// Selector is the offending text, trimmed to something readable.
	Selector string

	// Reason says which rule it broke, in words that name the fix.
	Reason string
}

func (v Violation) String() string {
	return fmt.Sprintf("line %d: %s — %s", v.Line, v.Selector, v.Reason)
}

// rules are the refusals, in the order they are reported.
//
// Each pattern matches the *call* rather than a bare string, so a test whose fixture
// data happens to contain "nth-child" is not rejected for it: the policy is about how
// an element is located, not about what a page contains.
var rules = []struct {
	pattern *regexp.Regexp
	reason  string
}{
	{
		// The headline rule from the requirements: positional CSS is rejected, not
		// discouraged (BE-7.4.2).
		regexp.MustCompile(`(?i)\b(?:page|frame|locator|within)\s*\.\s*(?:locator|\$\$?)\s*\(\s*['"\x60][^'"\x60]*:nth-(?:child|of-type|last-child|last-of-type)\b`),
		"positional CSS breaks the first time somebody adds a wrapper element; " +
			"use getByTestId, or getByRole with the accessible name",
	},
	{
		positionalIndex(),
		"a numeric index into a list of matches is positional by another name; " +
			"locate the element by what it is, not by where it sits",
	},
	{
		regexp.MustCompile(`(?i)\b(?:page|frame|locator)\s*\.\s*(?:locator|\$\$?)\s*\(\s*['"\x60][^'"\x60]*\b(?:first-child|last-child|only-child)\b`),
		"a structural pseudo-class describes the DOM's shape rather than the element; " +
			"use a test id or a role",
	},
	{
		regexp.MustCompile(`(?i)\b(?:page|frame|locator)\s*\.\s*(?:locator|\$\$?)\s*\(\s*['"\x60][^'"\x60]*\s*>\s*[a-z]+\s*>\s*[a-z]+`),
		"a chain of child combinators encodes the current markup; " +
			"use a test id or a role with the accessible name",
	},
	{
		regexp.MustCompile(`(?i)\.locator\s*\(\s*['"\x60]\s*(?:div|span|p|td|tr|li|section|article)\s*['"\x60]\s*\)`),
		"a bare tag selector matches whatever the page grows next; " +
			"use a test id, a role, or a label",
	},
	{
		regexp.MustCompile(`(?i)\bXPath\s*=|\.locator\s*\(\s*['"\x60]\s*(?://|\.//)`),
		"XPath locates by document position; use a test id or a role",
	},
	{
		regexp.MustCompile(`(?i)\bwaitForTimeout\s*\(`),
		"a fixed sleep is the most common cause of a flaky suite; " +
			"wait for the thing itself with expect(...).toBeVisible() or waitFor",
	},
	{
		// A class chain is the other common positional smell: framework-generated class
		// names change on every build.
		regexp.MustCompile(`(?i)\.locator\s*\(\s*['"\x60][^'"\x60]*\.[A-Za-z0-9_-]+\s*\.\s*[A-Za-z0-9_-]+`),
		"chained class names are generated by the build and change with it; " +
			"use a test id or a role",
	},
}

// positionalIndex matches a numeric index into a set of matches, which is nth-child by
// another name.
//
// `.first()` on its own is permitted: a page with one obvious match uses it to say "the
// first, and there should only be one", which is a different statement from "the third
// one, whatever that is".
func positionalIndex() *regexp.Regexp {
	return regexp.MustCompile(`(?i)\.\s*nth\s*\(\s*[0-9]+\s*\)|\.\s*(?:eq|item)\s*\(\s*[0-9]+\s*\)`)
}

// Check reports every violation in a generated spec.
//
// A pure function of the text, which is the point: it is unit-testable, it runs on
// every generated file without a container or a network, and it gives the same answer
// every time (BE-7.4.3).
func Check(spec string) []Violation {
	var violations []Violation

	for index, line := range strings.Split(spec, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "*") {
			// A comment mentioning nth-child is a comment, and rejecting a file for its
			// prose would be the policy failing at its own job.
			continue
		}

		for _, rule := range rules {
			if match := rule.pattern.FindString(line); match != "" {
				violations = append(violations, Violation{
					Line:     index + 1,
					Selector: excerpt(match),
					Reason:   rule.reason,
				})
				// One violation per line is enough to send it back; listing three ways the
				// same line is wrong makes the feedback longer without making it clearer.
				break
			}
		}
	}

	return violations
}

// Acceptable reports whether the spec passes the policy.
func Acceptable(spec string) bool { return len(Check(spec)) == 0 }

// Summarise renders violations for a prompt or a job log, capped so one pathological
// file cannot fill either.
func Summarise(violations []Violation) string {
	const maximum = 12

	lines := make([]string, 0, min(len(violations), maximum))
	for index, violation := range violations {
		if index == maximum {
			lines = append(lines, fmt.Sprintf("… and %d more", len(violations)-maximum))
			break
		}
		lines = append(lines, "- "+violation.String())
	}
	return strings.Join(lines, "\n")
}

// Preferred returns the locator the policy wants for an element, given what the page
// snapshot said about it.
//
// Used when generating rather than when checking, so the generated spec starts inside
// the policy instead of being corrected into it. Empty means the element cannot be
// located stably at all, which is worth saying: a button with no test id, no role, no
// label, and no text is a button the application should fix before anybody writes a
// test against it.
func Preferred(testID, role, name, label, text string) string {
	switch {
	case testID != "":
		return fmt.Sprintf("page.getByTestId(%s)", quote(testID))
	case role != "" && name != "":
		return fmt.Sprintf("page.getByRole(%s, { name: %s })", quote(role), quote(name))
	case label != "":
		return fmt.Sprintf("page.getByLabel(%s)", quote(label))
	case text != "":
		return fmt.Sprintf("page.getByText(%s)", quote(text))
	default:
		return ""
	}
}

// Ranked lists the acceptable locator strategies, strongest first.
//
// Exported so the prompt the generator sends and the policy the checker enforces come
// from one list: two copies of a preference order is two orders, and the drift shows up
// as a suite that keeps being regenerated for reasons the prompt never mentioned.
func Ranked() []string {
	return []string{
		"getByTestId",
		"getByRole with an accessible name",
		"getByLabel",
		"getByPlaceholder",
		"getByText",
	}
}

// quote renders a string for a TypeScript source file.
//
// Single quotes with the contents escaped, because that is what a Playwright spec looks
// like, and a generated file that does not look hand-written is a generated file people
// distrust.
func quote(value string) string {
	escaped := strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", " ").Replace(value)
	return "'" + escaped + "'"
}

func excerpt(text string) string {
	trimmed := strings.TrimSpace(text)
	if len(trimmed) > 120 {
		return trimmed[:120] + "…"
	}
	return trimmed
}
