package datagen

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/hyscaler/qavia/api/internal/ingest"
)

// Database schema input (BE-8.7, F-3.7, F-3.8).
//
// A SQL dump is parsed here, locally, with no MCP server and no connection to
// anybody's database. That is the built-in path and it is the one that has to work: a
// client who can send a `pg_dump --schema-only` can generate data for their tables
// today, without giving this platform a database credential or standing up a server
// beside it (F-13.6).
//
// The optional path — a read-only Postgres MCP server, scoped to one database with a
// read-only role — adds live schema awareness and nothing this cannot do. It belongs
// with the rest of the MCP work in BE-10, and the deliberate consequence of building
// this first is that removing that configuration later changes nothing about whether
// data can be generated.
//
// The parse is deliberately narrow. It reads `CREATE TABLE` and the column list, and it
// ignores everything else in the file: triggers, functions, grants, and data. A dump is
// a program, and a parser that tried to understand all of one would be a parser with
// opinions about a client's schema that it cannot justify.

// Table is one parsed table.
type Table struct {
	Name    string
	Columns []Column
}

// Column is one parsed column, in the terms that shape generated data.
type Column struct {
	Name string

	// Type is the declared SQL type, lowercased and without its length: `varchar`,
	// `numeric`, `timestamptz`.
	Type string

	// Length is a character limit where the type declared one, so a generated value
	// fits the column rather than failing the insert.
	Length *int

	// Precision and Scale come from `numeric(p,s)`, which is the only place a dump
	// says how many decimal places a value may have.
	Precision *int
	Scale     *int

	NotNull    bool
	PrimaryKey bool

	// Enum is the value list from a check constraint of the form
	// `col IN ('a','b')`, which is how a dump most often expresses an enumeration.
	Enum []string
}

// Schema converts a table into the shape the generator walks.
//
// The conversion is the interesting part: a generator that understood SQL types
// directly would be a second type system to maintain, so a table becomes the same
// `ingest.Schema` an OpenAPI body does and everything downstream — the faker, the
// boundary cases, the export — is unchanged.
func (t Table) Schema() ingest.Schema {
	schema := ingest.Schema{
		Type:        "object",
		Description: fmt.Sprintf("rows of the %s table", t.Name),
		Properties:  make(map[string]ingest.Schema, len(t.Columns)),
	}

	for _, column := range t.Columns {
		property := column.Schema()
		schema.Properties[column.Name] = property

		if column.NotNull && !column.PrimaryKey {
			// A NOT NULL column is a required field, which is what makes the invalid set
			// able to omit it and expect a rejection. A primary key is excluded because
			// it is usually generated by the database, and a fixture that supplies one
			// collides with the sequence.
			schema.Required = append(schema.Required, column.Name)
		}
	}

	sort.Strings(schema.Required)
	return schema
}

// Schema converts one column.
func (c Column) Schema() ingest.Schema {
	schema := ingest.Schema{Enum: c.Enum}

	switch {
	case strings.HasPrefix(c.Type, "int"), c.Type == "smallint", c.Type == "bigint",
		c.Type == "serial", c.Type == "bigserial", c.Type == "smallserial":
		schema.Type = "integer"
		schema.Minimum = boundOf(1)
		schema.Maximum = boundOf(rangeFor(c.Type))

	case c.Type == "numeric", c.Type == "decimal", c.Type == "real",
		c.Type == "double", c.Type == "doubleprecision", c.Type == "money", c.Type == "float":
		schema.Type = "number"
		schema.Minimum = boundOf(0)
		schema.Maximum = boundOf(precisionCeiling(c.Precision))

	case c.Type == "bool", c.Type == "boolean":
		schema.Type = "boolean"

	case c.Type == "uuid":
		schema.Type = "string"
		schema.Format = "uuid"

	case c.Type == "date":
		schema.Type = "string"
		schema.Format = "date"

	case strings.HasPrefix(c.Type, "timestamp"):
		schema.Type = "string"
		schema.Format = "date-time"

	case strings.HasPrefix(c.Type, "time"):
		schema.Type = "string"
		schema.Format = "time"

	case c.Type == "json", c.Type == "jsonb":
		// An object with no described properties. The generator says so in a warning
		// rather than inventing a shape, because a jsonb column's contents are the one
		// thing a dump genuinely does not know.
		schema.Type = "object"

	case c.Type == "inet", c.Type == "cidr":
		schema.Type = "string"
		schema.Format = "ipv4"

	default:
		schema.Type = "string"
		schema.MaxLength = c.Length
	}

	return schema
}

// ParseDump reads the CREATE TABLE statements out of a SQL dump.
//
// Bounded: a dump is an upload, and an upload is untrusted input. What bounds it is the
// caller's size limit on the artifact plus maxDumpTables here, so a file describing ten
// thousand tables produces a stated refusal rather than a response nobody can read.
func ParseDump(dump string) ([]Table, []string, error) {
	statements := createTable.FindAllStringSubmatch(dump, -1)
	if len(statements) == 0 {
		return nil, nil, fmt.Errorf("datagen: no CREATE TABLE statement was found; " +
			"a schema-only dump (pg_dump --schema-only) is what this reads")
	}

	var (
		tables   []Table
		warnings []string
	)

	for _, statement := range statements {
		if len(tables) >= maxDumpTables {
			warnings = append(warnings, fmt.Sprintf(
				"the dump declares more than %d tables; the rest were not read", maxDumpTables))
			break
		}

		name := unquote(statement[1])
		body := statement[2]

		table := Table{Name: name}
		for _, definition := range splitDefinitions(body) {
			column, kind := parseDefinition(definition)
			switch kind {
			case definitionColumn:
				table.Columns = append(table.Columns, column)
			case definitionCheck:
				// A check constraint naming a column's permitted values is an enumeration,
				// and the only form of one many dumps carry.
				applyCheck(&table, definition)
			case definitionOther:
				// A primary key, a foreign key, an index. Nothing to generate from.
			}
		}

		if len(table.Columns) == 0 {
			warnings = append(warnings, fmt.Sprintf("%s: no columns could be read", name))
			continue
		}
		tables = append(tables, table)
	}

	if len(tables) == 0 {
		return nil, warnings, fmt.Errorf("datagen: no table in the dump had readable columns")
	}
	return tables, warnings, nil
}

// maxDumpTables bounds one parse.
const maxDumpTables = 200

// createTable matches a table declaration and captures its name and body.
//
// Written as one expression rather than a tokeniser because that is the honest scope of
// this parser: it reads column declarations and ignores the rest of the file. A dump
// whose CREATE TABLE this cannot match is reported as unreadable rather than partially
// understood.
var createTable = regexp.MustCompile(`(?is)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([^\s(]+)\s*\((.*?)\)\s*(?:INHERITS[^;]*)?;`)

type definitionKind int

const (
	definitionColumn definitionKind = iota
	definitionCheck
	definitionOther
)

// constraintKeywords start a table-level constraint rather than a column.
var constraintKeywords = []string{
	"primary key", "foreign key", "unique", "check", "constraint", "exclude", "like",
}

// parseDefinition reads one line of a column list.
func parseDefinition(definition string) (Column, definitionKind) {
	trimmed := strings.TrimSpace(definition)
	lowered := strings.ToLower(trimmed)

	for _, keyword := range constraintKeywords {
		if strings.HasPrefix(lowered, keyword) {
			if strings.Contains(lowered, "check") {
				return Column{}, definitionCheck
			}
			return Column{}, definitionOther
		}
	}

	fields := strings.Fields(trimmed)
	if len(fields) < 2 {
		return Column{}, definitionOther
	}

	column := Column{
		Name:       unquote(fields[0]),
		NotNull:    strings.Contains(lowered, "not null"),
		PrimaryKey: strings.Contains(lowered, "primary key"),
	}

	declared := fields[1]
	if len(fields) > 2 && strings.HasPrefix(strings.ToLower(fields[2]), "precision") {
		// `double precision`, which is two words and the only common type that is.
		declared += fields[2]
	}

	column.Type, column.Length, column.Precision, column.Scale = parseType(declared)

	if values := inClause.FindStringSubmatch(trimmed); len(values) == 2 {
		// An inline check on the column itself: `status text CHECK (status IN ('a','b'))`.
		column.Enum = quotedValues(values[1])
	}

	return column, definitionColumn
}

// parseType splits `varchar(40)` or `numeric(12,2)` into its parts.
func parseType(declared string) (string, *int, *int, *int) {
	name := strings.ToLower(strings.TrimSpace(declared))
	name = strings.TrimSuffix(name, ",")

	open := strings.Index(name, "(")
	if open < 0 {
		return strings.ReplaceAll(name, " ", ""), nil, nil, nil
	}

	base := strings.ReplaceAll(name[:open], " ", "")
	inside := strings.TrimSuffix(name[open+1:], ")")
	parts := strings.Split(inside, ",")

	first, err := strconv.Atoi(strings.TrimSpace(parts[0]))
	if err != nil {
		return base, nil, nil, nil
	}

	if len(parts) == 1 {
		if base == "numeric" || base == "decimal" {
			return base, nil, &first, nil
		}
		return base, &first, nil, nil
	}

	second, err := strconv.Atoi(strings.TrimSpace(parts[1]))
	if err != nil {
		return base, nil, &first, nil
	}
	return base, nil, &first, &second
}

// applyCheck reads a table-level check constraint and attaches its enumeration.
func applyCheck(table *Table, definition string) {
	values := inClause.FindStringSubmatch(definition)
	if len(values) != 2 {
		return
	}

	column := checkColumn.FindStringSubmatch(definition)
	if len(column) != 2 {
		return
	}

	name := unquote(column[1])
	for index := range table.Columns {
		if table.Columns[index].Name == name {
			table.Columns[index].Enum = quotedValues(values[1])
			return
		}
	}
}

var (
	// inClause captures the value list of `... IN ('a', 'b')`.
	inClause = regexp.MustCompile(`(?is)\bIN\s*\(([^)]*)\)`)

	// checkColumn captures the column a check constrains.
	checkColumn = regexp.MustCompile(`(?is)CHECK\s*\(\s*\(?\s*([^\s()]+)`)

	quoted = regexp.MustCompile(`'((?:[^']|'')*)'`)
)

// quotedValues reads the string literals out of a value list.
func quotedValues(list string) []string {
	matches := quoted.FindAllStringSubmatch(list, -1)

	values := make([]string, 0, len(matches))
	for _, match := range matches {
		values = append(values, strings.ReplaceAll(match[1], "''", "'"))
	}
	return values
}

// splitDefinitions splits a column list on commas that are not inside brackets.
//
// A naive split on every comma breaks `numeric(12,2)` and every check constraint in the
// file, which is most of the reason a dump parser needs any care at all.
func splitDefinitions(body string) []string {
	var (
		definitions []string
		current     strings.Builder
		depth       int
		inString    bool
	)

	for _, character := range body {
		switch {
		case character == '\'':
			inString = !inString
		case inString:
			// A comma or bracket inside a literal is text.
		case character == '(':
			depth++
		case character == ')':
			depth--
		case character == ',' && depth == 0:
			definitions = append(definitions, current.String())
			current.Reset()
			continue
		}
		current.WriteRune(character)
	}

	if strings.TrimSpace(current.String()) != "" {
		definitions = append(definitions, current.String())
	}
	return definitions
}

// unquote strips the quoting a dump puts around identifiers, and any schema prefix: a
// generated fixture is about the table, and `public.` in a field name is noise.
func unquote(identifier string) string {
	cleaned := strings.Trim(strings.TrimSpace(identifier), `"`+"`")
	if index := strings.LastIndex(cleaned, "."); index >= 0 {
		cleaned = cleaned[index+1:]
	}
	return strings.Trim(cleaned, `"`+"`")
}

func boundOf(value float64) *float64 { return &value }

// rangeFor keeps a generated integer inside the column's width. A smallint column with
// a value of 40000 fails the insert, which makes the whole fixture useless.
func rangeFor(declared string) float64 {
	switch declared {
	case "smallint", "smallserial":
		return 32_000
	case "bigint", "bigserial":
		return 1_000_000_000
	default:
		return 2_000_000
	}
}

// precisionCeiling keeps a generated decimal inside `numeric(p,s)`.
func precisionCeiling(precision *int) float64 {
	if precision == nil || *precision <= 0 || *precision > 12 {
		return 100_000
	}

	ceiling := 1.0
	for index := 0; index < *precision-2; index++ {
		ceiling *= 10
	}
	return ceiling
}
