package testfiles

import (
	"archive/zip"
	"context"
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
)

// Export writes the suite as a zip (F-6.10).
//
// Streamed into the caller's writer rather than built in memory: a 300-file suite
// with a scaffold is small, and the reason to stream anyway is that nothing about
// this path should get slower as a suite grows.
//
// The archive is deterministic: files are ordered by path and every entry carries a
// fixed timestamp, so exporting the same suite twice produces the same bytes. That
// is what makes an exported suite diffable against the last one.
func (s *Service) Export(
	ctx context.Context,
	writer io.Writer,
	projectID uuid.UUID,
	projectName string,
	framework Framework,
) error {
	files, err := s.All(ctx, projectID, framework)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return nil
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })

	archive := zip.NewWriter(writer)

	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := writeEntry(archive, file.Path, file.Content); err != nil {
			return err
		}
	}

	// The scaffold is what makes the zip runnable rather than a folder of files:
	// `npm install && npm test` has to work with only environment variables
	// supplied (BE-3.6).
	if hasFramework(files, FrameworkSupertest) {
		if err := writeEntry(archive, "package.json", packageJSON(projectName)); err != nil {
			return err
		}
		if err := writeEntry(archive, "tsconfig.json", tsconfigJSON()); err != nil {
			return err
		}
		if err := writeEntry(archive, ".env.example", envExample()); err != nil {
			return err
		}
	}

	if err := writeEntry(archive, "README.md", readme(projectName, files)); err != nil {
		return err
	}

	if err := archive.Close(); err != nil {
		return fmt.Errorf("finish export archive: %w", err)
	}
	return nil
}

// fixedModTime keeps the archive byte-identical across exports of the same suite.
var fixedModTime = time.Date(2020, time.January, 1, 0, 0, 0, 0, time.UTC)

func writeEntry(archive *zip.Writer, path, content string) error {
	header := &zip.FileHeader{Name: path, Method: zip.Deflate, Modified: fixedModTime}

	entry, err := archive.CreateHeader(header)
	if err != nil {
		return fmt.Errorf("add %s to the export: %w", path, err)
	}
	if _, err := io.WriteString(entry, content); err != nil {
		return fmt.Errorf("write %s into the export: %w", path, err)
	}
	return nil
}

func hasFramework(files []File, framework Framework) bool {
	for _, file := range files {
		if file.Framework == framework {
			return true
		}
	}
	return false
}

func packageJSON(projectName string) string {
	return `{
  "name": "` + slug(projectName) + `-tests",
  "private": true,
  "description": "API tests generated by Qavia from approved test cases.",
  "scripts": {
    "test": "vitest run"
  },
  "devDependencies": {
    "supertest": "^7.0.0",
    "typescript": "^5.6.0",
    "vitest": "^2.1.0",
    "@types/supertest": "^6.0.2"
  }
}
`
}

func tsconfigJSON() string {
	return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "types": ["vitest/globals"]
  },
  "include": ["tests/**/*.ts"]
}
`
}

func envExample() string {
	return `# The suite reads its target and credentials from the environment, so the same
# files run against staging and production without being edited.
QAVIA_TARGET_URL=https://staging.example.test
QAVIA_AUTH_TOKEN=
`
}

// readme tells somebody who has only the zip how to run it, and lists what each
// file covers so a failure can be traced back to a case.
func readme(projectName string, files []File) string {
	var out strings.Builder

	out.WriteString("# " + projectName + " test suite\n\n")
	out.WriteString("Generated by Qavia from approved test cases. " +
		"Every file below names the cases it implements, so a failure traces back to " +
		"a test case and from there to a requirement.\n\n")

	out.WriteString("## Running it\n\n")
	out.WriteString("```sh\nnpm install\ncp .env.example .env   # then fill it in\n" +
		"QAVIA_TARGET_URL=https://staging.example.test npm test\n```\n\n")
	out.WriteString("The suite reads `QAVIA_TARGET_URL` and `QAVIA_AUTH_TOKEN` from the " +
		"environment. Nothing is hardcoded, which is why the same files run against any " +
		"environment you point them at.\n\n")

	out.WriteString("## Files\n\n")
	out.WriteString("| File | Framework | Cases covered |\n|---|---|---|\n")
	for _, file := range files {
		fmt.Fprintf(&out, "| `%s` | %s | %d |\n",
			file.Path, file.Framework, len(file.TestCaseIDs))
	}

	out.WriteString("\n## Traceability\n\n")
	for _, file := range files {
		if len(file.TestCaseIDs) == 0 {
			continue
		}
		out.WriteString("- `" + file.Path + "`\n")
		for _, id := range file.TestCaseIDs {
			out.WriteString("  - test case `" + id.String() + "`\n")
		}
	}

	return out.String()
}

func slug(name string) string {
	var out strings.Builder
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
		case r == ' ' || r == '-' || r == '_':
			if out.Len() > 0 && !strings.HasSuffix(out.String(), "-") {
				out.WriteRune('-')
			}
		}
	}

	trimmed := strings.Trim(out.String(), "-")
	if trimmed == "" {
		return "qavia"
	}
	return trimmed
}
