// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const clearDefaultProvider = `-- name: ClearDefaultProvider :exec
UPDATE llm_providers SET is_default = false, updated_at = now() WHERE is_default
`

// ClearDefaultProvider and SetDefaultProvider run in one transaction. The partial
// unique index refuses two defaults, so the clear has to happen first.
func (q *Queries) ClearDefaultProvider(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultProvider)
	return err
}

const countAssignmentsUsingModel = `-- name: CountAssignmentsUsingModel :one
SELECT count(*) FROM tier_assignments WHERE model_id = $1 OR fallback_model_id = $1
`

func (q *Queries) CountAssignmentsUsingModel(ctx context.Context, modelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsUsingModel, modelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssignmentsUsingProvider = `-- name: CountAssignmentsUsingProvider :one
SELECT count(*)
FROM tier_assignments a
JOIN llm_models m ON m.id = a.model_id OR m.id = a.fallback_model_id
WHERE m.provider_id = $1
`

// CountAssignmentsUsingProvider is what makes deleting a referenced provider a
// clear refusal rather than a cascade that silently unassigns a tier.
func (q *Queries) CountAssignmentsUsingProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsUsingProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledProviders = `-- name: CountEnabledProviders :one
SELECT count(*) FROM llm_providers WHERE is_enabled
`

// CountEnabledProviders backs the setup status and the enqueue-time check: an AI
// job with no configured provider is refused when the user presses submit, not
// inside a worker twenty minutes later.
func (q *Queries) CountEnabledProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLLMModel = `-- name: CreateLLMModel :one
INSERT INTO llm_models (
    provider_id, model_id, display_name, tiers, capabilities,
    price_input, price_output, price_cache_read, price_cache_write,
    max_input_tokens, max_output_tokens, is_enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, provider_id, model_id, display_name, tiers, capabilities,
          price_input, price_output, price_cache_read, price_cache_write,
          max_input_tokens, max_output_tokens, is_enabled, created_at, updated_at
`

type CreateLLMModelParams struct {
	ProviderID      uuid.UUID
	ModelID         string
	DisplayName     string
	Tiers           []string
	Capabilities    json.RawMessage
	PriceInput      decimal.Decimal
	PriceOutput     decimal.Decimal
	PriceCacheRead  *decimal.Decimal
	PriceCacheWrite *decimal.Decimal
	MaxInputTokens  *int32
	MaxOutputTokens *int32
	IsEnabled       bool
}

func (q *Queries) CreateLLMModel(ctx context.Context, arg CreateLLMModelParams) (LlmModel, error) {
	row := q.db.QueryRow(ctx, createLLMModel,
		arg.ProviderID,
		arg.ModelID,
		arg.DisplayName,
		arg.Tiers,
		arg.Capabilities,
		arg.PriceInput,
		arg.PriceOutput,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.MaxInputTokens,
		arg.MaxOutputTokens,
		arg.IsEnabled,
	)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.Tiers,
		&i.Capabilities,
		&i.PriceInput,
		&i.PriceOutput,
		&i.PriceCacheRead,
		&i.PriceCacheWrite,
		&i.MaxInputTokens,
		&i.MaxOutputTokens,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLLMProvider = `-- name: CreateLLMProvider :one

INSERT INTO llm_providers (name, kind, config, credentials, data_residency, is_enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7::uuid)
RETURNING id, name, kind, config, credentials, data_residency, is_enabled, is_default,
          health_status, health_checked_at, health_detail, created_by, created_at, updated_at
`

type CreateLLMProviderParams struct {
	Name          string
	Kind          LlmProviderKind
	Config        json.RawMessage
	Credentials   json.RawMessage
	DataResidency LlmDataResidency
	IsEnabled     bool
	CreatedBy     *uuid.UUID
}

// The AI provider layer: providers, models, tier assignments, and the call log.
//
// Resolution for a tier is project assignment, then global assignment, then an
// error. Never a silent code default: a zero value that quietly means "use
// whatever" is the failure this whole design prevents (ai-architecture.md 3.2).
func (q *Queries) CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createLLMProvider,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Credentials,
		arg.DataResidency,
		arg.IsEnabled,
		arg.CreatedBy,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Credentials,
		&i.DataResidency,
		&i.IsEnabled,
		&i.IsDefault,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLLMModel = `-- name: DeleteLLMModel :execrows
DELETE FROM llm_models WHERE id = $1
`

func (q *Queries) DeleteLLMModel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLLMModel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLLMProvider = `-- name: DeleteLLMProvider :execrows
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteLLMProvider(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLLMProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTierAssignment = `-- name: DeleteTierAssignment :execrows
DELETE FROM tier_assignments WHERE id = $1
`

func (q *Queries) DeleteTierAssignment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTierAssignment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLLMModel = `-- name: GetLLMModel :one
SELECT id, provider_id, model_id, display_name, tiers, capabilities,
       price_input, price_output, price_cache_read, price_cache_write,
       max_input_tokens, max_output_tokens, is_enabled, created_at, updated_at
FROM llm_models
WHERE id = $1
`

func (q *Queries) GetLLMModel(ctx context.Context, id uuid.UUID) (LlmModel, error) {
	row := q.db.QueryRow(ctx, getLLMModel, id)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.Tiers,
		&i.Capabilities,
		&i.PriceInput,
		&i.PriceOutput,
		&i.PriceCacheRead,
		&i.PriceCacheWrite,
		&i.MaxInputTokens,
		&i.MaxOutputTokens,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProvider = `-- name: GetLLMProvider :one
SELECT id, name, kind, config, credentials, data_residency, is_enabled, is_default,
       health_status, health_checked_at, health_detail, created_by, created_at, updated_at
FROM llm_providers
WHERE id = $1
`

func (q *Queries) GetLLMProvider(ctx context.Context, id uuid.UUID) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getLLMProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Credentials,
		&i.DataResidency,
		&i.IsEnabled,
		&i.IsDefault,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLLMCalls = `-- name: ListLLMCalls :many
SELECT id, provider_id, model_id, provider_kind, model_name, tier, agent,
       project_id, job_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
       cost_usd, latency_ms, fallback_used, at
FROM llm_calls
WHERE at >= $1 AND at < $2
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::bigint IS NULL OR id < $4::bigint)
ORDER BY id DESC
LIMIT $5
`

type ListLLMCallsParams struct {
	At        time.Time
	At_2      time.Time
	ProjectID *uuid.UUID
	Cursor    *int64
	PageSize  int32
}

func (q *Queries) ListLLMCalls(ctx context.Context, arg ListLLMCallsParams) ([]LlmCall, error) {
	rows, err := q.db.Query(ctx, listLLMCalls,
		arg.At,
		arg.At_2,
		arg.ProjectID,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmCall{}
	for rows.Next() {
		var i LlmCall
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelID,
			&i.ProviderKind,
			&i.ModelName,
			&i.Tier,
			&i.Agent,
			&i.ProjectID,
			&i.JobID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsd,
			&i.LatencyMs,
			&i.FallbackUsed,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMModels = `-- name: ListLLMModels :many
SELECT id, provider_id, model_id, display_name, tiers, capabilities,
       price_input, price_output, price_cache_read, price_cache_write,
       max_input_tokens, max_output_tokens, is_enabled, created_at, updated_at
FROM llm_models
WHERE ($1::uuid IS NULL OR provider_id = $1::uuid)
ORDER BY model_id
`

func (q *Queries) ListLLMModels(ctx context.Context, providerID *uuid.UUID) ([]LlmModel, error) {
	rows, err := q.db.Query(ctx, listLLMModels, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelID,
			&i.DisplayName,
			&i.Tiers,
			&i.Capabilities,
			&i.PriceInput,
			&i.PriceOutput,
			&i.PriceCacheRead,
			&i.PriceCacheWrite,
			&i.MaxInputTokens,
			&i.MaxOutputTokens,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProviders = `-- name: ListLLMProviders :many
SELECT id, name, kind, config, credentials, data_residency, is_enabled, is_default,
       health_status, health_checked_at, health_detail, created_by, created_at, updated_at
FROM llm_providers
ORDER BY is_default DESC, lower(name)
`

func (q *Queries) ListLLMProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listLLMProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Credentials,
			&i.DataResidency,
			&i.IsEnabled,
			&i.IsDefault,
			&i.HealthStatus,
			&i.HealthCheckedAt,
			&i.HealthDetail,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTierAssignments = `-- name: ListTierAssignments :many
SELECT id, scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by, created_at, updated_at
FROM tier_assignments
WHERE ($1::uuid IS NULL AND scope = 'global')
   OR ($1::uuid IS NOT NULL AND scope_id = $1::uuid)
ORDER BY tier
`

func (q *Queries) ListTierAssignments(ctx context.Context, projectID *uuid.UUID) ([]TierAssignment, error) {
	rows, err := q.db.Query(ctx, listTierAssignments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TierAssignment{}
	for rows.Next() {
		var i TierAssignment
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Tier,
			&i.ModelID,
			&i.FallbackModelID,
			&i.Effort,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLLMCall = `-- name: RecordLLMCall :one
INSERT INTO llm_calls (
    provider_id, model_id, provider_kind, model_name, tier, agent,
    project_id, job_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
    cost_usd, latency_ms, fallback_used
)
VALUES (
    $12::uuid, $13::uuid, $1, $2, $3, $4,
    $14::uuid, $15::uuid, $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, provider_id, model_id, provider_kind, model_name, tier, agent,
          project_id, job_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
          cost_usd, latency_ms, fallback_used, at
`

type RecordLLMCallParams struct {
	ProviderKind     string
	ModelName        string
	Tier             LlmTier
	Agent            string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostUsd          decimal.Decimal
	LatencyMs        int32
	FallbackUsed     bool
	ProviderID       *uuid.UUID
	ModelID          *uuid.UUID
	ProjectID        *uuid.UUID
	JobID            *uuid.UUID
}

// RecordLLMCall is written by Go and only by Go. Python returns usage and
// persists nothing (backend-standards.md 10).
func (q *Queries) RecordLLMCall(ctx context.Context, arg RecordLLMCallParams) (LlmCall, error) {
	row := q.db.QueryRow(ctx, recordLLMCall,
		arg.ProviderKind,
		arg.ModelName,
		arg.Tier,
		arg.Agent,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostUsd,
		arg.LatencyMs,
		arg.FallbackUsed,
		arg.ProviderID,
		arg.ModelID,
		arg.ProjectID,
		arg.JobID,
	)
	var i LlmCall
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.ProviderKind,
		&i.ModelName,
		&i.Tier,
		&i.Agent,
		&i.ProjectID,
		&i.JobID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CostUsd,
		&i.LatencyMs,
		&i.FallbackUsed,
		&i.At,
	)
	return i, err
}

const resolveTier = `-- name: ResolveTier :many
SELECT id, scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by, created_at, updated_at
FROM tier_assignments
WHERE tier = $1
  AND (scope = 'global' OR (scope = 'project' AND scope_id = $2::uuid))
ORDER BY scope DESC
`

type ResolveTierParams struct {
	Tier      LlmTier
	ProjectID *uuid.UUID
}

// ResolveTier is the whole resolution rule in one query: project first, then
// global, ordered so the caller takes the first row and never sorts it itself.
func (q *Queries) ResolveTier(ctx context.Context, arg ResolveTierParams) ([]TierAssignment, error) {
	rows, err := q.db.Query(ctx, resolveTier, arg.Tier, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TierAssignment{}
	for rows.Next() {
		var i TierAssignment
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Tier,
			&i.ModelID,
			&i.FallbackModelID,
			&i.Effort,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultProvider = `-- name: SetDefaultProvider :exec
UPDATE llm_providers SET is_default = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SetDefaultProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultProvider, id)
	return err
}

const setLLMModelCapabilities = `-- name: SetLLMModelCapabilities :exec
UPDATE llm_models
SET capabilities = $2, updated_at = now()
WHERE id = $1
`

type SetLLMModelCapabilitiesParams struct {
	ID           uuid.UUID
	Capabilities json.RawMessage
}

// SetLLMModelCapabilities is written by the probe. Detected capability overwrites
// declared capability, because a declaration is a claim and a probe is a
// measurement (F-16.5).
func (q *Queries) SetLLMModelCapabilities(ctx context.Context, arg SetLLMModelCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setLLMModelCapabilities, arg.ID, arg.Capabilities)
	return err
}

const setLLMProviderCredentials = `-- name: SetLLMProviderCredentials :exec
UPDATE llm_providers
SET credentials = $2, updated_at = now()
WHERE id = $1
`

type SetLLMProviderCredentialsParams struct {
	ID          uuid.UUID
	Credentials json.RawMessage
}

// SetLLMProviderCredentials is separate from the rest of the update, because a
// form submitted without the secret field must not blank the stored one: a secret
// is replaced deliberately or left alone (F-1.8).
func (q *Queries) SetLLMProviderCredentials(ctx context.Context, arg SetLLMProviderCredentialsParams) error {
	_, err := q.db.Exec(ctx, setLLMProviderCredentials, arg.ID, arg.Credentials)
	return err
}

const setLLMProviderHealth = `-- name: SetLLMProviderHealth :exec
UPDATE llm_providers
SET health_status = $2, health_detail = $3, health_checked_at = now(), updated_at = now()
WHERE id = $1
`

type SetLLMProviderHealthParams struct {
	ID           uuid.UUID
	HealthStatus LlmHealthStatus
	HealthDetail string
}

func (q *Queries) SetLLMProviderHealth(ctx context.Context, arg SetLLMProviderHealthParams) error {
	_, err := q.db.Exec(ctx, setLLMProviderHealth, arg.ID, arg.HealthStatus, arg.HealthDetail)
	return err
}

const spendByAgent = `-- name: SpendByAgent :many
SELECT agent,
       count(*)::bigint AS calls,
       sum(input_tokens)::bigint AS input_tokens,
       sum(output_tokens)::bigint AS output_tokens,
       sum(cache_read_tokens)::bigint AS cache_read_tokens,
       sum(cost_usd)::numeric AS cost_usd
FROM llm_calls
WHERE at >= $1 AND at < $2
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
GROUP BY agent
ORDER BY cost_usd DESC
`

type SpendByAgentParams struct {
	At        time.Time
	At_2      time.Time
	ProjectID *uuid.UUID
}

type SpendByAgentRow struct {
	Agent           string
	Calls           int64
	InputTokens     int64
	OutputTokens    int64
	CacheReadTokens int64
	CostUsd         decimal.Decimal
}

func (q *Queries) SpendByAgent(ctx context.Context, arg SpendByAgentParams) ([]SpendByAgentRow, error) {
	rows, err := q.db.Query(ctx, spendByAgent, arg.At, arg.At_2, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByAgentRow{}
	for rows.Next() {
		var i SpendByAgentRow
		if err := rows.Scan(
			&i.Agent,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByProject = `-- name: SpendByProject :many
SELECT coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid) AS project_id,
       count(*)::bigint AS calls,
       sum(input_tokens)::bigint AS input_tokens,
       sum(output_tokens)::bigint AS output_tokens,
       sum(cache_read_tokens)::bigint AS cache_read_tokens,
       sum(cost_usd)::numeric AS cost_usd
FROM llm_calls
WHERE at >= $1 AND at < $2
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
GROUP BY 1
ORDER BY cost_usd DESC
`

type SpendByProjectParams struct {
	At        time.Time
	At_2      time.Time
	ProjectID *uuid.UUID
}

type SpendByProjectRow struct {
	ProjectID       *uuid.UUID
	Calls           int64
	InputTokens     int64
	OutputTokens    int64
	CacheReadTokens int64
	CostUsd         decimal.Decimal
}

func (q *Queries) SpendByProject(ctx context.Context, arg SpendByProjectParams) ([]SpendByProjectRow, error) {
	rows, err := q.db.Query(ctx, spendByProject, arg.At, arg.At_2, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByProjectRow{}
	for rows.Next() {
		var i SpendByProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByProvider = `-- name: SpendByProvider :many
SELECT coalesce(provider_id, '00000000-0000-0000-0000-000000000000'::uuid) AS provider_id,
       max(provider_kind)::text AS provider_kind,
       count(*)::bigint AS calls,
       sum(input_tokens)::bigint AS input_tokens,
       sum(output_tokens)::bigint AS output_tokens,
       sum(cache_read_tokens)::bigint AS cache_read_tokens,
       sum(cost_usd)::numeric AS cost_usd
FROM llm_calls
WHERE at >= $1 AND at < $2
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
GROUP BY 1
ORDER BY cost_usd DESC
`

type SpendByProviderParams struct {
	At        time.Time
	At_2      time.Time
	ProjectID *uuid.UUID
}

type SpendByProviderRow struct {
	ProviderID      *uuid.UUID
	ProviderKind    string
	Calls           int64
	InputTokens     int64
	OutputTokens    int64
	CacheReadTokens int64
	CostUsd         decimal.Decimal
}

// SpendByProvider, SpendByProject, and SpendByAgent back the dashboard. Genuine
// SQL aggregates, generated like any other query, so the numbers reconcile exactly
// against a direct SUM over llm_calls (BE-1.14).
func (q *Queries) SpendByProvider(ctx context.Context, arg SpendByProviderParams) ([]SpendByProviderRow, error) {
	rows, err := q.db.Query(ctx, spendByProvider, arg.At, arg.At_2, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByProviderRow{}
	for rows.Next() {
		var i SpendByProviderRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderKind,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendSince = `-- name: SpendSince :one
SELECT coalesce(sum(cost_usd), 0)::numeric AS total
FROM llm_calls
WHERE at >= $1
  AND ($2::uuid IS NULL OR provider_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
`

type SpendSinceParams struct {
	At         time.Time
	ProviderID *uuid.UUID
	ProjectID  *uuid.UUID
}

// SpendSince is the ceiling check, evaluated before a call rather than after
// (F-16.10). A mixed setup may have one cheap local provider and one metered one,
// so it is available per provider and in total.
func (q *Queries) SpendSince(ctx context.Context, arg SpendSinceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, spendSince, arg.At, arg.ProviderID, arg.ProjectID)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const spendTotal = `-- name: SpendTotal :one
SELECT count(*)::bigint AS calls,
       coalesce(sum(input_tokens), 0)::bigint AS input_tokens,
       coalesce(sum(output_tokens), 0)::bigint AS output_tokens,
       coalesce(sum(cache_read_tokens), 0)::bigint AS cache_read_tokens,
       coalesce(sum(cache_write_tokens), 0)::bigint AS cache_write_tokens,
       coalesce(sum(cost_usd), 0)::numeric AS cost_usd
FROM llm_calls
WHERE at >= $1 AND at < $2
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
`

type SpendTotalParams struct {
	At        time.Time
	At_2      time.Time
	ProjectID *uuid.UUID
}

type SpendTotalRow struct {
	Calls            int64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	CostUsd          decimal.Decimal
}

func (q *Queries) SpendTotal(ctx context.Context, arg SpendTotalParams) (SpendTotalRow, error) {
	row := q.db.QueryRow(ctx, spendTotal, arg.At, arg.At_2, arg.ProjectID)
	var i SpendTotalRow
	err := row.Scan(
		&i.Calls,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CostUsd,
	)
	return i, err
}

const updateLLMModel = `-- name: UpdateLLMModel :one
UPDATE llm_models
SET display_name = $2, tiers = $3, capabilities = $4,
    price_input = $5, price_output = $6, price_cache_read = $7, price_cache_write = $8,
    max_input_tokens = $9, max_output_tokens = $10, is_enabled = $11, updated_at = now()
WHERE id = $1
RETURNING id, provider_id, model_id, display_name, tiers, capabilities,
          price_input, price_output, price_cache_read, price_cache_write,
          max_input_tokens, max_output_tokens, is_enabled, created_at, updated_at
`

type UpdateLLMModelParams struct {
	ID              uuid.UUID
	DisplayName     string
	Tiers           []string
	Capabilities    json.RawMessage
	PriceInput      decimal.Decimal
	PriceOutput     decimal.Decimal
	PriceCacheRead  *decimal.Decimal
	PriceCacheWrite *decimal.Decimal
	MaxInputTokens  *int32
	MaxOutputTokens *int32
	IsEnabled       bool
}

func (q *Queries) UpdateLLMModel(ctx context.Context, arg UpdateLLMModelParams) (LlmModel, error) {
	row := q.db.QueryRow(ctx, updateLLMModel,
		arg.ID,
		arg.DisplayName,
		arg.Tiers,
		arg.Capabilities,
		arg.PriceInput,
		arg.PriceOutput,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.MaxInputTokens,
		arg.MaxOutputTokens,
		arg.IsEnabled,
	)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.Tiers,
		&i.Capabilities,
		&i.PriceInput,
		&i.PriceOutput,
		&i.PriceCacheRead,
		&i.PriceCacheWrite,
		&i.MaxInputTokens,
		&i.MaxOutputTokens,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLLMProvider = `-- name: UpdateLLMProvider :one
UPDATE llm_providers
SET name = $2, config = $3, data_residency = $4, is_enabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, kind, config, credentials, data_residency, is_enabled, is_default,
          health_status, health_checked_at, health_detail, created_by, created_at, updated_at
`

type UpdateLLMProviderParams struct {
	ID            uuid.UUID
	Name          string
	Config        json.RawMessage
	DataResidency LlmDataResidency
	IsEnabled     bool
}

func (q *Queries) UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateLLMProvider,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.DataResidency,
		arg.IsEnabled,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Credentials,
		&i.DataResidency,
		&i.IsEnabled,
		&i.IsDefault,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGlobalTierAssignment = `-- name: UpsertGlobalTierAssignment :one
INSERT INTO tier_assignments (scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by)
VALUES ('global', NULL, $1, $2, $3::uuid, $4::text,
        $5::uuid)
ON CONFLICT (tier) WHERE scope = 'global' DO UPDATE
SET model_id = EXCLUDED.model_id,
    fallback_model_id = EXCLUDED.fallback_model_id,
    effort = EXCLUDED.effort,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by, created_at, updated_at
`

type UpsertGlobalTierAssignmentParams struct {
	Tier            LlmTier
	ModelID         uuid.UUID
	FallbackModelID *uuid.UUID
	Effort          *string
	UpdatedBy       *uuid.UUID
}

// UpsertTierAssignment writes the global row. Global and project need separate
// statements because their uniqueness is enforced by two partial indexes: a NULL
// scope_id is not equal to itself, so one ON CONFLICT target cannot cover both.
func (q *Queries) UpsertGlobalTierAssignment(ctx context.Context, arg UpsertGlobalTierAssignmentParams) (TierAssignment, error) {
	row := q.db.QueryRow(ctx, upsertGlobalTierAssignment,
		arg.Tier,
		arg.ModelID,
		arg.FallbackModelID,
		arg.Effort,
		arg.UpdatedBy,
	)
	var i TierAssignment
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Tier,
		&i.ModelID,
		&i.FallbackModelID,
		&i.Effort,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectTierAssignment = `-- name: UpsertProjectTierAssignment :one
INSERT INTO tier_assignments (scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by)
VALUES ('project', $1, $2, $3, $4::uuid, $5::text,
        $6::uuid)
ON CONFLICT (scope_id, tier) WHERE scope = 'project' DO UPDATE
SET model_id = EXCLUDED.model_id,
    fallback_model_id = EXCLUDED.fallback_model_id,
    effort = EXCLUDED.effort,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, scope, scope_id, tier, model_id, fallback_model_id, effort, updated_by, created_at, updated_at
`

type UpsertProjectTierAssignmentParams struct {
	ScopeID         *uuid.UUID
	Tier            LlmTier
	ModelID         uuid.UUID
	FallbackModelID *uuid.UUID
	Effort          *string
	UpdatedBy       *uuid.UUID
}

func (q *Queries) UpsertProjectTierAssignment(ctx context.Context, arg UpsertProjectTierAssignmentParams) (TierAssignment, error) {
	row := q.db.QueryRow(ctx, upsertProjectTierAssignment,
		arg.ScopeID,
		arg.Tier,
		arg.ModelID,
		arg.FallbackModelID,
		arg.Effort,
		arg.UpdatedBy,
	)
	var i TierAssignment
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Tier,
		&i.ModelID,
		&i.FallbackModelID,
		&i.Effort,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
