// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyses.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAnalysis = `-- name: CreateAnalysis :one

INSERT INTO analyses (
    run_result_id, reason, root_cause, suggested_fix, evidence,
    related_commit, stability_score, prompt_version, model_name
) VALUES ($1, $2, $3, $4, $5, $6, $9::numeric, $7, $8)
RETURNING id, run_result_id, reason, root_cause, suggested_fix, evidence,
          related_commit, stability_score, prompt_version, model_name, created_at
`

type CreateAnalysisParams struct {
	RunResultID    uuid.UUID
	Reason         string
	RootCause      string
	SuggestedFix   string
	Evidence       json.RawMessage
	RelatedCommit  string
	PromptVersion  string
	ModelName      string
	StabilityScore *decimal.Decimal
}

// Failure analyses and the feedback on them (BE-5.1, BE-5.8).
//
// The evidence column is written whole by Go, after every reference in it has been
// checked against the artifact it points at: an analysis citing line 4,000 of a
// 300-line log is rejected before it reaches this table (BE-5.3).
func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error) {
	row := q.db.QueryRow(ctx, createAnalysis,
		arg.RunResultID,
		arg.Reason,
		arg.RootCause,
		arg.SuggestedFix,
		arg.Evidence,
		arg.RelatedCommit,
		arg.PromptVersion,
		arg.ModelName,
		arg.StabilityScore,
	)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.RunResultID,
		&i.Reason,
		&i.RootCause,
		&i.SuggestedFix,
		&i.Evidence,
		&i.RelatedCommit,
		&i.StabilityScore,
		&i.PromptVersion,
		&i.ModelName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnalysisFeedback = `-- name: DeleteAnalysisFeedback :exec
DELETE FROM analysis_feedback WHERE analysis_id = $1 AND user_id = $2
`

type DeleteAnalysisFeedbackParams struct {
	AnalysisID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) DeleteAnalysisFeedback(ctx context.Context, arg DeleteAnalysisFeedbackParams) error {
	_, err := q.db.Exec(ctx, deleteAnalysisFeedback, arg.AnalysisID, arg.UserID)
	return err
}

const failingResultsForRun = `-- name: FailingResultsForRun :many
SELECT id, run_id, test_case_id, test_file_id, name, status, duration_ms, attempt,
       failure_message, log_key, screenshot_key, video_key, created_at, trace_key,
       quarantined
FROM run_results
WHERE run_id = $1 AND status IN ('failed', 'flaky', 'errored')
ORDER BY status, name, attempt
`

// FailingResultsForRun is what the analyse chain iterates: every failure worth
// explaining, flaky ones included, because "why is this flaky" is the question a
// reviewer actually has.
func (q *Queries) FailingResultsForRun(ctx context.Context, runID uuid.UUID) ([]RunResult, error) {
	rows, err := q.db.Query(ctx, failingResultsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunResult{}
	for rows.Next() {
		var i RunResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TestCaseID,
			&i.TestFileID,
			&i.Name,
			&i.Status,
			&i.DurationMs,
			&i.Attempt,
			&i.FailureMessage,
			&i.LogKey,
			&i.ScreenshotKey,
			&i.VideoKey,
			&i.CreatedAt,
			&i.TraceKey,
			&i.Quarantined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const feedbackByPromptVersion = `-- name: FeedbackByPromptVersion :many
SELECT prompt_version,
       count(*) FILTER (WHERE helpful)::bigint AS helpful,
       count(*) FILTER (WHERE NOT helpful)::bigint AS unhelpful
FROM analysis_feedback
GROUP BY prompt_version
ORDER BY prompt_version
`

type FeedbackByPromptVersionRow struct {
	PromptVersion string
	Helpful       int64
	Unhelpful     int64
}

// FeedbackByPromptVersion is the point of storing the version: prompt iteration with
// numbers rather than impressions (BE-5.8.2).
func (q *Queries) FeedbackByPromptVersion(ctx context.Context) ([]FeedbackByPromptVersionRow, error) {
	rows, err := q.db.Query(ctx, feedbackByPromptVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedbackByPromptVersionRow{}
	for rows.Next() {
		var i FeedbackByPromptVersionRow
		if err := rows.Scan(&i.PromptVersion, &i.Helpful, &i.Unhelpful); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, run_result_id, reason, root_cause, suggested_fix, evidence,
       related_commit, stability_score, prompt_version, model_name, created_at
FROM analyses
WHERE id = $1
`

func (q *Queries) GetAnalysis(ctx context.Context, id uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, id)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.RunResultID,
		&i.Reason,
		&i.RootCause,
		&i.SuggestedFix,
		&i.Evidence,
		&i.RelatedCommit,
		&i.StabilityScore,
		&i.PromptVersion,
		&i.ModelName,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysisFeedback = `-- name: GetAnalysisFeedback :one
SELECT analysis_id, user_id, helpful, note, prompt_version, created_at
FROM analysis_feedback
WHERE analysis_id = $1 AND user_id = $2
`

type GetAnalysisFeedbackParams struct {
	AnalysisID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) GetAnalysisFeedback(ctx context.Context, arg GetAnalysisFeedbackParams) (AnalysisFeedback, error) {
	row := q.db.QueryRow(ctx, getAnalysisFeedback, arg.AnalysisID, arg.UserID)
	var i AnalysisFeedback
	err := row.Scan(
		&i.AnalysisID,
		&i.UserID,
		&i.Helpful,
		&i.Note,
		&i.PromptVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getRunResult = `-- name: GetRunResult :one
SELECT id, run_id, test_case_id, test_file_id, name, status, duration_ms, attempt,
       failure_message, log_key, screenshot_key, video_key, created_at, trace_key,
       quarantined
FROM run_results
WHERE id = $1
`

func (q *Queries) GetRunResult(ctx context.Context, id uuid.UUID) (RunResult, error) {
	row := q.db.QueryRow(ctx, getRunResult, id)
	var i RunResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestFileID,
		&i.Name,
		&i.Status,
		&i.DurationMs,
		&i.Attempt,
		&i.FailureMessage,
		&i.LogKey,
		&i.ScreenshotKey,
		&i.VideoKey,
		&i.CreatedAt,
		&i.TraceKey,
		&i.Quarantined,
	)
	return i, err
}

const latestAnalysisForResult = `-- name: LatestAnalysisForResult :one
SELECT id, run_result_id, reason, root_cause, suggested_fix, evidence,
       related_commit, stability_score, prompt_version, model_name, created_at
FROM analyses
WHERE run_result_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// LatestAnalysisForResult is what the UI shows: a re-analysis after a prompt change
// is a new row, and the newest one wins.
func (q *Queries) LatestAnalysisForResult(ctx context.Context, runResultID uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, latestAnalysisForResult, runResultID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.RunResultID,
		&i.Reason,
		&i.RootCause,
		&i.SuggestedFix,
		&i.Evidence,
		&i.RelatedCommit,
		&i.StabilityScore,
		&i.PromptVersion,
		&i.ModelName,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalysesForRun = `-- name: ListAnalysesForRun :many
SELECT a.id, a.run_result_id, a.reason, a.root_cause, a.suggested_fix, a.evidence,
       a.related_commit, a.stability_score, a.prompt_version, a.model_name, a.created_at
FROM analyses a
JOIN run_results r ON r.id = a.run_result_id
WHERE r.run_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) ListAnalysesForRun(ctx context.Context, runID uuid.UUID) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listAnalysesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.RunResultID,
			&i.Reason,
			&i.RootCause,
			&i.SuggestedFix,
			&i.Evidence,
			&i.RelatedCommit,
			&i.StabilityScore,
			&i.PromptVersion,
			&i.ModelName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resultAttempts = `-- name: ResultAttempts :many
SELECT status, attempt
FROM run_results
WHERE run_id = $1 AND name = $2
ORDER BY attempt
`

type ResultAttemptsParams struct {
	RunID uuid.UUID
	Name  string
}

type ResultAttemptsRow struct {
	Status  RunResultStatus
	Attempt int32
}

// ResultAttempts backs the stability score's first permitted signal: how a test
// behaved across the attempts of one run (BE-5.4.1).
func (q *Queries) ResultAttempts(ctx context.Context, arg ResultAttemptsParams) ([]ResultAttemptsRow, error) {
	rows, err := q.db.Query(ctx, resultAttempts, arg.RunID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResultAttemptsRow{}
	for rows.Next() {
		var i ResultAttemptsRow
		if err := rows.Scan(&i.Status, &i.Attempt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resultHistoryByName = `-- name: ResultHistoryByName :many
SELECT r.status, r.attempt, r.created_at
FROM run_results r
JOIN runs n ON n.id = r.run_id
WHERE n.project_id = $1 AND r.name = $2
ORDER BY r.created_at DESC
LIMIT $3
`

type ResultHistoryByNameParams struct {
	ProjectID uuid.UUID
	Name      string
	Limit     int32
}

type ResultHistoryByNameRow struct {
	Status    RunResultStatus
	Attempt   int32
	CreatedAt time.Time
}

// ResultHistoryByName is the second stability input: how this test has behaved over
// recent runs of the same project. By name rather than by test case, because a
// result the platform could not map to exactly one case still has a history.
func (q *Queries) ResultHistoryByName(ctx context.Context, arg ResultHistoryByNameParams) ([]ResultHistoryByNameRow, error) {
	rows, err := q.db.Query(ctx, resultHistoryByName, arg.ProjectID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResultHistoryByNameRow{}
	for rows.Next() {
		var i ResultHistoryByNameRow
		if err := rows.Scan(&i.Status, &i.Attempt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStabilityScore = `-- name: SetStabilityScore :exec
UPDATE analyses
SET stability_score = $2::numeric
WHERE id = $1
`

type SetStabilityScoreParams struct {
	ID             uuid.UUID
	StabilityScore *decimal.Decimal
}

// SetStabilityScore is written after the analysis, because the score comes from
// re-run history and commit overlap rather than from the agent (BE-5.4).
func (q *Queries) SetStabilityScore(ctx context.Context, arg SetStabilityScoreParams) error {
	_, err := q.db.Exec(ctx, setStabilityScore, arg.ID, arg.StabilityScore)
	return err
}

const upsertAnalysisFeedback = `-- name: UpsertAnalysisFeedback :exec
INSERT INTO analysis_feedback (analysis_id, user_id, helpful, note, prompt_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (analysis_id, user_id) DO UPDATE
SET helpful = EXCLUDED.helpful,
    note = EXCLUDED.note,
    prompt_version = EXCLUDED.prompt_version,
    created_at = now()
`

type UpsertAnalysisFeedbackParams struct {
	AnalysisID    uuid.UUID
	UserID        uuid.UUID
	Helpful       bool
	Note          string
	PromptVersion string
}

func (q *Queries) UpsertAnalysisFeedback(ctx context.Context, arg UpsertAnalysisFeedbackParams) error {
	_, err := q.db.Exec(ctx, upsertAnalysisFeedback,
		arg.AnalysisID,
		arg.UserID,
		arg.Helpful,
		arg.Note,
		arg.PromptVersion,
	)
	return err
}
