// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO artifacts (id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::uuid)
RETURNING id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by, created_at
`

type CreateArtifactParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Kind        string
	Filename    string
	StorageKey  string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	Version     int32
	LineageID   uuid.UUID
	UploadedBy  *uuid.UUID
}

// Artifacts: uploaded or connected inputs, versioned by content hash.
// CreateArtifact relies on the unique index on (project_id, sha256): an identical
// re-upload conflicts and the service returns the existing row with
// deduplicated: true rather than re-running generation (FR-1.4).
//
// The id is supplied rather than generated here because the storage key contains
// it, and the object is written before the row exists: a key built after the
// insert would mean either a second statement to fill it in or a row that briefly
// points nowhere.
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Filename,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Version,
		arg.LineageID,
		arg.UploadedBy,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Version,
		&i.LineageID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findArtifactLineage = `-- name: FindArtifactLineage :one
SELECT lineage_id, max(version)::int AS latest_version
FROM artifacts
WHERE project_id = $1 AND kind = $2 AND filename = $3
GROUP BY lineage_id
ORDER BY max(version) DESC
LIMIT 1
`

type FindArtifactLineageParams struct {
	ProjectID uuid.UUID
	Kind      string
	Filename  string
}

type FindArtifactLineageRow struct {
	LineageID     uuid.UUID
	LatestVersion int32
}

// FindArtifactLineage locates the previous versions of the same logical input, by
// filename and kind within a project. This is what a re-upload of a changed spec
// attaches itself to, and what phase 11 diffs against.
func (q *Queries) FindArtifactLineage(ctx context.Context, arg FindArtifactLineageParams) (FindArtifactLineageRow, error) {
	row := q.db.QueryRow(ctx, findArtifactLineage, arg.ProjectID, arg.Kind, arg.Filename)
	var i FindArtifactLineageRow
	err := row.Scan(&i.LineageID, &i.LatestVersion)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by, created_at
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Version,
		&i.LineageID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByHash = `-- name: GetArtifactByHash :one
SELECT id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by, created_at
FROM artifacts
WHERE project_id = $1 AND sha256 = $2
`

type GetArtifactByHashParams struct {
	ProjectID uuid.UUID
	Sha256    []byte
}

func (q *Queries) GetArtifactByHash(ctx context.Context, arg GetArtifactByHashParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByHash, arg.ProjectID, arg.Sha256)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Filename,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Version,
		&i.LineageID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by, created_at
FROM artifacts
WHERE lineage_id = $1
ORDER BY version DESC
`

func (q *Queries) ListArtifactVersions(ctx context.Context, lineageID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, lineageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Filename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.Version,
			&i.LineageID,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, project_id, kind, filename, storage_key, content_type, size_bytes, sha256, version, lineage_id, uploaded_by, created_at
FROM artifacts
WHERE project_id = $1
  AND ($2::text IS NULL OR kind = $2::text)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $4
`

type ListArtifactsParams struct {
	ProjectID uuid.UUID
	Kind      *string
	Cursor    *time.Time
	PageSize  int32
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.ProjectID,
		arg.Kind,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Filename,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.Version,
			&i.LineageID,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsOlderThan = `-- name: ListArtifactsOlderThan :many
SELECT id, project_id, storage_key
FROM artifacts
WHERE created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListArtifactsOlderThanParams struct {
	CreatedAt time.Time
	PageSize  int32
}

type ListArtifactsOlderThanRow struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	StorageKey string
}

// ListArtifactsOlderThan drives the retention job. Retention is a setting in days
// (F-17.5).
func (q *Queries) ListArtifactsOlderThan(ctx context.Context, arg ListArtifactsOlderThanParams) ([]ListArtifactsOlderThanRow, error) {
	rows, err := q.db.Query(ctx, listArtifactsOlderThan, arg.CreatedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsOlderThanRow{}
	for rows.Next() {
		var i ListArtifactsOlderThanRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
