// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countAuditEntriesByAction = `-- name: CountAuditEntriesByAction :many
SELECT action, count(*) AS total
FROM audit_log
WHERE at > $1
GROUP BY action
ORDER BY total DESC
`

type CountAuditEntriesByActionRow struct {
	Action string
	Total  int64
}

func (q *Queries) CountAuditEntriesByAction(ctx context.Context, at time.Time) ([]CountAuditEntriesByActionRow, error) {
	rows, err := q.db.Query(ctx, countAuditEntriesByAction, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditEntriesByActionRow{}
	for rows.Next() {
		var i CountAuditEntriesByActionRow
		if err := rows.Scan(&i.Action, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, actor_id, actor_email, action, subject, project_id, ip, detail, at
FROM audit_log
WHERE ($1::bigint IS NULL OR id < $1::bigint)
ORDER BY id DESC
LIMIT $2
`

type ListAuditEntriesParams struct {
	Cursor   *int64
	PageSize int32
}

// ListAuditEntries is deliberately narrow. The filtered admin view is a dynamic
// query built with squirrel inside the store, because four optional filters would
// otherwise mean sixteen generated queries.
func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Subject,
			&i.ProjectID,
			&i.Ip,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditEntry = `-- name: RecordAuditEntry :exec

INSERT INTO audit_log (actor_id, actor_email, action, subject, project_id, ip, detail)
VALUES ($5::uuid, $1, $2, $3, $6::uuid, $7::inet, $4)
`

type RecordAuditEntryParams struct {
	ActorEmail string
	Action     string
	Subject    string
	Detail     json.RawMessage
	ActorID    *uuid.UUID
	ProjectID  *uuid.UUID
	Ip         *netip.Addr
}

// The audit log. Every privileged action, and nothing that holds a secret.
func (q *Queries) RecordAuditEntry(ctx context.Context, arg RecordAuditEntryParams) error {
	_, err := q.db.Exec(ctx, recordAuditEntry,
		arg.ActorEmail,
		arg.Action,
		arg.Subject,
		arg.Detail,
		arg.ActorID,
		arg.ProjectID,
		arg.Ip,
	)
	return err
}
