// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package dbgen

import (
	"context"
)

// iteratorForAppendRunLogLines implements pgx.CopyFromSource.
type iteratorForAppendRunLogLines struct {
	rows                 []AppendRunLogLinesParams
	skippedFirstNextCall bool
}

func (r *iteratorForAppendRunLogLines) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAppendRunLogLines) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].Line,
	}, nil
}

func (r iteratorForAppendRunLogLines) Err() error {
	return nil
}

// Live log lines (BE-4.11). Written in batches by the worker, read by the SSE
// stream, deleted once the run's full log is safely in object storage.
func (q *Queries) AppendRunLogLines(ctx context.Context, arg []AppendRunLogLinesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_log_lines"}, []string{"run_id", "line"}, &iteratorForAppendRunLogLines{rows: arg})
}

// iteratorForCreateCoverageFilesBulk implements pgx.CopyFromSource.
type iteratorForCreateCoverageFilesBulk struct {
	rows                 []CreateCoverageFilesBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCoverageFilesBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCoverageFilesBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CoverageRunID,
		r.rows[0].Path,
		r.rows[0].LinesTotal,
		r.rows[0].LinesCovered,
		r.rows[0].BranchesTotal,
		r.rows[0].BranchesCovered,
	}, nil
}

func (r iteratorForCreateCoverageFilesBulk) Err() error {
	return nil
}

func (q *Queries) CreateCoverageFilesBulk(ctx context.Context, arg []CreateCoverageFilesBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"coverage_files"}, []string{"coverage_run_id", "path", "lines_total", "lines_covered", "branches_total", "branches_covered"}, &iteratorForCreateCoverageFilesBulk{rows: arg})
}

// iteratorForCreateRunResultsBulk implements pgx.CopyFromSource.
type iteratorForCreateRunResultsBulk struct {
	rows                 []CreateRunResultsBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRunResultsBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRunResultsBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].TestCaseID,
		r.rows[0].TestFileID,
		r.rows[0].Name,
		r.rows[0].Status,
		r.rows[0].DurationMs,
		r.rows[0].Attempt,
		r.rows[0].FailureMessage,
		r.rows[0].LogKey,
		r.rows[0].ScreenshotKey,
		r.rows[0].VideoKey,
		r.rows[0].TraceKey,
		r.rows[0].Quarantined,
	}, nil
}

func (r iteratorForCreateRunResultsBulk) Err() error {
	return nil
}

func (q *Queries) CreateRunResultsBulk(ctx context.Context, arg []CreateRunResultsBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_results"}, []string{"run_id", "test_case_id", "test_file_id", "name", "status", "duration_ms", "attempt", "failure_message", "log_key", "screenshot_key", "video_key", "trace_key", "quarantined"}, &iteratorForCreateRunResultsBulk{rows: arg})
}

// iteratorForCreateTestCasesBulk implements pgx.CopyFromSource.
type iteratorForCreateTestCasesBulk struct {
	rows                 []CreateTestCasesBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTestCasesBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTestCasesBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].RequirementID,
		r.rows[0].Title,
		r.rows[0].Preconditions,
		r.rows[0].Steps,
		r.rows[0].Expected,
		r.rows[0].Priority,
		r.rows[0].Category,
		r.rows[0].Status,
		r.rows[0].Fingerprint,
		r.rows[0].Endpoint,
		r.rows[0].GeneratedBy,
	}, nil
}

func (r iteratorForCreateTestCasesBulk) Err() error {
	return nil
}

// CreateTestCasesBulk is the generation write path: 400 cases is one statement
// rather than 400 round trips inside a transaction that is now long
// (backend-standards.md 8).
func (q *Queries) CreateTestCasesBulk(ctx context.Context, arg []CreateTestCasesBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"test_cases"}, []string{"project_id", "requirement_id", "title", "preconditions", "steps", "expected", "priority", "category", "status", "fingerprint", "endpoint", "generated_by"}, &iteratorForCreateTestCasesBulk{rows: arg})
}
