// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coverage.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const coverageTrend = `-- name: CoverageTrend :many
SELECT id, commit_sha, lines_total, lines_covered, branches_total, branches_covered, created_at
FROM coverage_runs
WHERE project_id = $1 AND error = '' AND created_at >= $2
ORDER BY created_at
`

type CoverageTrendParams struct {
	ProjectID uuid.UUID
	CreatedAt time.Time
}

type CoverageTrendRow struct {
	ID              uuid.UUID
	CommitSha       string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
	CreatedAt       time.Time
}

// CoverageTrend backs the "did it rise" question that gives measured coverage its
// point: a number with no history is a number nobody acts on.
func (q *Queries) CoverageTrend(ctx context.Context, arg CoverageTrendParams) ([]CoverageTrendRow, error) {
	rows, err := q.db.Query(ctx, coverageTrend, arg.ProjectID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageTrendRow{}
	for rows.Next() {
		var i CoverageTrendRow
		if err := rows.Scan(
			&i.ID,
			&i.CommitSha,
			&i.LinesTotal,
			&i.LinesCovered,
			&i.BranchesTotal,
			&i.BranchesCovered,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type CreateCoverageFilesBulkParams struct {
	CoverageRunID   uuid.UUID
	Path            string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
}

const createCoverageRun = `-- name: CreateCoverageRun :one

INSERT INTO coverage_runs (
    project_id, commit_sha, tool, command,
    lines_total, lines_covered, branches_total, branches_covered, error, job_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, commit_sha, tool, command, lines_total, lines_covered,
          branches_total, branches_covered, error, job_id, created_at
`

type CreateCoverageRunParams struct {
	ProjectID       uuid.UUID
	CommitSha       string
	Tool            string
	Command         string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
	Error           string
	JobID           *uuid.UUID
}

// Code coverage (BE-6.6, BE-6.7).
//
// Percentages are computed on read from the stored totals. A stored percentage is a
// number that can disagree with its own numerator after one bad migration, and the
// whole value of this table is that it agrees with the tool that produced it.
func (q *Queries) CreateCoverageRun(ctx context.Context, arg CreateCoverageRunParams) (CoverageRun, error) {
	row := q.db.QueryRow(ctx, createCoverageRun,
		arg.ProjectID,
		arg.CommitSha,
		arg.Tool,
		arg.Command,
		arg.LinesTotal,
		arg.LinesCovered,
		arg.BranchesTotal,
		arg.BranchesCovered,
		arg.Error,
		arg.JobID,
	)
	var i CoverageRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.Tool,
		&i.Command,
		&i.LinesTotal,
		&i.LinesCovered,
		&i.BranchesTotal,
		&i.BranchesCovered,
		&i.Error,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const latestCoverageRun = `-- name: LatestCoverageRun :one
SELECT id, project_id, commit_sha, tool, command, lines_total, lines_covered,
       branches_total, branches_covered, error, job_id, created_at
FROM coverage_runs
WHERE project_id = $1 AND error = ''
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestCoverageRun(ctx context.Context, projectID uuid.UUID) (CoverageRun, error) {
	row := q.db.QueryRow(ctx, latestCoverageRun, projectID)
	var i CoverageRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.Tool,
		&i.Command,
		&i.LinesTotal,
		&i.LinesCovered,
		&i.BranchesTotal,
		&i.BranchesCovered,
		&i.Error,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const listCoverageFiles = `-- name: ListCoverageFiles :many
SELECT path, lines_total, lines_covered, branches_total, branches_covered
FROM coverage_files
WHERE coverage_run_id = $1
ORDER BY
    CASE WHEN lines_total = 0 THEN 1 ELSE 0 END,
    (lines_covered::numeric / NULLIF(lines_total, 0)),
    path
LIMIT $2
`

type ListCoverageFilesParams struct {
	CoverageRunID uuid.UUID
	PageSize      int32
}

type ListCoverageFilesRow struct {
	Path            string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
}

// ListCoverageFiles is the per-file detail, least covered first: the only order
// anybody reads it in.
func (q *Queries) ListCoverageFiles(ctx context.Context, arg ListCoverageFilesParams) ([]ListCoverageFilesRow, error) {
	rows, err := q.db.Query(ctx, listCoverageFiles, arg.CoverageRunID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoverageFilesRow{}
	for rows.Next() {
		var i ListCoverageFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.LinesTotal,
			&i.LinesCovered,
			&i.BranchesTotal,
			&i.BranchesCovered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
