// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: defects.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countDefectsByStatus = `-- name: CountDefectsByStatus :many
SELECT status, count(*)::bigint AS total
FROM defects
WHERE project_id = $1
GROUP BY status
`

type CountDefectsByStatusRow struct {
	Status DefectStatus
	Total  int64
}

func (q *Queries) CountDefectsByStatus(ctx context.Context, projectID uuid.UUID) ([]CountDefectsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDefectsByStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDefectsByStatusRow{}
	for rows.Next() {
		var i CountDefectsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDefect = `-- name: CreateDefect :one

INSERT INTO defects (
    project_id, run_result_id, test_case_id, requirement_id, analysis_id,
    title, description, severity, status, assignee_id, root_cause_key, created_by,
    test_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
          title, description, severity, status, assignee_id, duplicate_of,
          root_cause_key, external_ref, created_by, created_at, updated_at,
          resolved_at, test_name
`

type CreateDefectParams struct {
	ProjectID     uuid.UUID
	RunResultID   *uuid.UUID
	TestCaseID    *uuid.UUID
	RequirementID *uuid.UUID
	AnalysisID    *uuid.UUID
	Title         string
	Description   string
	Severity      DefectSeverity
	Status        DefectStatus
	AssigneeID    *uuid.UUID
	RootCauseKey  string
	CreatedBy     *uuid.UUID
	TestName      string
}

// The built-in defect tracker (BE-5.5).
//
// It ships before any external tracker exists, because bug tracking has to work on
// an installation with no Jira and no GitHub. The external_ref column is where a
// tracker somebody else owns gets recorded later; on a zero-integration install it
// stays empty and nothing here changes.
//
// The filtered list is built with squirrel in the owning store rather than generated
// here: five optional filters is thirty-two queries or one unindexable one
// (backend-standards.md 9).
func (q *Queries) CreateDefect(ctx context.Context, arg CreateDefectParams) (Defect, error) {
	row := q.db.QueryRow(ctx, createDefect,
		arg.ProjectID,
		arg.RunResultID,
		arg.TestCaseID,
		arg.RequirementID,
		arg.AnalysisID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Status,
		arg.AssigneeID,
		arg.RootCauseKey,
		arg.CreatedBy,
		arg.TestName,
	)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const createDefectComment = `-- name: CreateDefectComment :one
INSERT INTO defect_comments (defect_id, author_id, body, system)
VALUES ($1, $2, $3, $4)
RETURNING id, defect_id, author_id, body, system, created_at
`

type CreateDefectCommentParams struct {
	DefectID uuid.UUID
	AuthorID *uuid.UUID
	Body     string
	System   bool
}

func (q *Queries) CreateDefectComment(ctx context.Context, arg CreateDefectCommentParams) (DefectComment, error) {
	row := q.db.QueryRow(ctx, createDefectComment,
		arg.DefectID,
		arg.AuthorID,
		arg.Body,
		arg.System,
	)
	var i DefectComment
	err := row.Scan(
		&i.ID,
		&i.DefectID,
		&i.AuthorID,
		&i.Body,
		&i.System,
		&i.CreatedAt,
	)
	return i, err
}

const defectForResult = `-- name: DefectForResult :one
SELECT id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
       title, description, severity, status, assignee_id, duplicate_of,
       root_cause_key, external_ref, created_by, created_at, updated_at,
       resolved_at, test_name
FROM defects
WHERE run_result_id = $1
`

// DefectForResult is the promotion guard: promoting the same failure twice returns
// the defect that already exists (BE-5.6.3).
func (q *Queries) DefectForResult(ctx context.Context, runResultID *uuid.UUID) (Defect, error) {
	row := q.db.QueryRow(ctx, defectForResult, runResultID)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const getDefect = `-- name: GetDefect :one
SELECT id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
       title, description, severity, status, assignee_id, duplicate_of,
       root_cause_key, external_ref, created_by, created_at, updated_at,
       resolved_at, test_name
FROM defects
WHERE id = $1
`

func (q *Queries) GetDefect(ctx context.Context, id uuid.UUID) (Defect, error) {
	row := q.db.QueryRow(ctx, getDefect, id)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const linkDuplicate = `-- name: LinkDuplicate :one
UPDATE defects
SET duplicate_of = $2,
    status = CASE WHEN $2::uuid IS NULL THEN 'open'::defect_status
                  ELSE 'duplicate'::defect_status END,
    resolved_at = CASE WHEN $2::uuid IS NULL THEN NULL
                       ELSE coalesce(resolved_at, now()) END,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
          title, description, severity, status, assignee_id, duplicate_of,
          root_cause_key, external_ref, created_by, created_at, updated_at,
          resolved_at, test_name
`

type LinkDuplicateParams struct {
	ID          uuid.UUID
	DuplicateOf *uuid.UUID
}

// LinkDuplicate is reversible: passing null unlinks, because the platform proposes
// and a person decides (BE-5.7.3).
func (q *Queries) LinkDuplicate(ctx context.Context, arg LinkDuplicateParams) (Defect, error) {
	row := q.db.QueryRow(ctx, linkDuplicate, arg.ID, arg.DuplicateOf)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const listDefectComments = `-- name: ListDefectComments :many
SELECT id, defect_id, author_id, body, system, created_at
FROM defect_comments
WHERE defect_id = $1
  AND ($2::timestamptz IS NULL OR created_at > $2::timestamptz)
ORDER BY created_at
LIMIT $3
`

type ListDefectCommentsParams struct {
	DefectID uuid.UUID
	After    *time.Time
	PageSize int32
}

func (q *Queries) ListDefectComments(ctx context.Context, arg ListDefectCommentsParams) ([]DefectComment, error) {
	rows, err := q.db.Query(ctx, listDefectComments, arg.DefectID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefectComment{}
	for rows.Next() {
		var i DefectComment
		if err := rows.Scan(
			&i.ID,
			&i.DefectID,
			&i.AuthorID,
			&i.Body,
			&i.System,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicatesOf = `-- name: ListDuplicatesOf :many
SELECT id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
       title, description, severity, status, assignee_id, duplicate_of,
       root_cause_key, external_ref, created_by, created_at, updated_at,
       resolved_at, test_name
FROM defects
WHERE duplicate_of = $1
ORDER BY created_at
`

// ListDuplicatesOf is how one defect shows its recurrences: three runs failing the
// same way is one defect with three linked occurrences (BE-5.7).
func (q *Queries) ListDuplicatesOf(ctx context.Context, duplicateOf *uuid.UUID) ([]Defect, error) {
	rows, err := q.db.Query(ctx, listDuplicatesOf, duplicateOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Defect{}
	for rows.Next() {
		var i Defect
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RunResultID,
			&i.TestCaseID,
			&i.RequirementID,
			&i.AnalysisID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.Status,
			&i.AssigneeID,
			&i.DuplicateOf,
			&i.RootCauseKey,
			&i.ExternalRef,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.TestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openDefectWithRootCause = `-- name: OpenDefectWithRootCause :one
SELECT id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
       title, description, severity, status, assignee_id, duplicate_of,
       root_cause_key, external_ref, created_by, created_at, updated_at,
       resolved_at, test_name
FROM defects
WHERE project_id = $1
  AND test_case_id = $2
  AND root_cause_key = $3
  AND status IN ('open', 'acknowledged', 'in_progress')
  AND duplicate_of IS NULL
ORDER BY created_at
LIMIT 1
`

type OpenDefectWithRootCauseParams struct {
	ProjectID    uuid.UUID
	TestCaseID   *uuid.UUID
	RootCauseKey string
}

// OpenDefectWithRootCause is duplicate detection, and it is a lookup rather than a
// model call: the same test case with the same normalised root cause is the same
// defect (BE-5.7.2). Closed defects are excluded, because a failure recurring after
// a fix is a regression and deserves its own row.
func (q *Queries) OpenDefectWithRootCause(ctx context.Context, arg OpenDefectWithRootCauseParams) (Defect, error) {
	row := q.db.QueryRow(ctx, openDefectWithRootCause, arg.ProjectID, arg.TestCaseID, arg.RootCauseKey)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const openDefectWithRootCauseByName = `-- name: OpenDefectWithRootCauseByName :one
SELECT id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
       title, description, severity, status, assignee_id, duplicate_of,
       root_cause_key, external_ref, created_by, created_at, updated_at,
       resolved_at, test_name
FROM defects
WHERE project_id = $1
  AND test_name = $2
  AND root_cause_key = $3
  AND status IN ('open', 'acknowledged', 'in_progress')
  AND duplicate_of IS NULL
ORDER BY created_at
LIMIT 1
`

type OpenDefectWithRootCauseByNameParams struct {
	ProjectID    uuid.UUID
	TestName     string
	RootCauseKey string
}

// OpenDefectWithRootCauseByName is the fallback when a result could not be mapped to
// exactly one test case. The test's name plus the normalised root cause is still
// "this test, failing this way" (BE-5.7.2).
func (q *Queries) OpenDefectWithRootCauseByName(ctx context.Context, arg OpenDefectWithRootCauseByNameParams) (Defect, error) {
	row := q.db.QueryRow(ctx, openDefectWithRootCauseByName, arg.ProjectID, arg.TestName, arg.RootCauseKey)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}

const setDefectExternalRef = `-- name: SetDefectExternalRef :exec
UPDATE defects
SET external_ref = $2, updated_at = now()
WHERE id = $1
`

type SetDefectExternalRefParams struct {
	ID          uuid.UUID
	ExternalRef json.RawMessage
}

func (q *Queries) SetDefectExternalRef(ctx context.Context, arg SetDefectExternalRefParams) error {
	_, err := q.db.Exec(ctx, setDefectExternalRef, arg.ID, arg.ExternalRef)
	return err
}

const touchDefect = `-- name: TouchDefect :exec
UPDATE defects SET updated_at = now() WHERE id = $1
`

// TouchDefect keeps updated_at meaningful when the change was a comment rather than
// a field: a thread that moved is a defect that moved.
func (q *Queries) TouchDefect(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDefect, id)
	return err
}

const updateDefect = `-- name: UpdateDefect :one
UPDATE defects
SET title = coalesce($2, title),
    description = coalesce($3, description),
    severity = coalesce($4::defect_severity, severity),
    status = coalesce($5::defect_status, status),
    assignee_id = CASE WHEN $6::bool THEN NULL
                       ELSE coalesce($7, assignee_id) END,
    -- resolved_at follows the status rather than being set by a caller: a defect that
    -- is fixed but has no resolution time is a defect nobody can measure.
    resolved_at = CASE
        WHEN coalesce($5::defect_status, status)
             IN ('fixed', 'wont_fix', 'duplicate') THEN coalesce(resolved_at, now())
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, run_result_id, test_case_id, requirement_id, analysis_id,
          title, description, severity, status, assignee_id, duplicate_of,
          root_cause_key, external_ref, created_by, created_at, updated_at,
          resolved_at, test_name
`

type UpdateDefectParams struct {
	ID            uuid.UUID
	Title         *string
	Description   *string
	Severity      NullDefectSeverity
	Status        NullDefectStatus
	ClearAssignee *bool
	AssigneeID    *uuid.UUID
}

func (q *Queries) UpdateDefect(ctx context.Context, arg UpdateDefectParams) (Defect, error) {
	row := q.db.QueryRow(ctx, updateDefect,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Status,
		arg.ClearAssignee,
		arg.AssigneeID,
	)
	var i Defect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunResultID,
		&i.TestCaseID,
		&i.RequirementID,
		&i.AnalysisID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.AssigneeID,
		&i.DuplicateOf,
		&i.RootCauseKey,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.TestName,
	)
	return i, err
}
