// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generation.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countCoveredRequirements = `-- name: CountCoveredRequirements :one
SELECT count(DISTINCT r.id)
FROM requirements r
JOIN test_cases t ON t.requirement_id = r.id AND t.superseded_by IS NULL
WHERE r.project_id = $1
`

func (q *Queries) CountCoveredRequirements(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCoveredRequirements, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEndpoints = `-- name: CountEndpoints :one
SELECT count(*) FROM endpoints WHERE project_id = $1
`

func (q *Queries) CountEndpoints(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpoints, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequirements = `-- name: CountRequirements :one
SELECT count(*) FROM requirements WHERE project_id = $1
`

func (q *Queries) CountRequirements(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequirements, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestCases = `-- name: CountTestCases :one
SELECT count(*) FROM test_cases WHERE project_id = $1 AND superseded_by IS NULL
`

func (q *Queries) CountTestCases(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTestCases, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestCasesByStatus = `-- name: CountTestCasesByStatus :many
SELECT status, count(*)::bigint AS total
FROM test_cases
WHERE project_id = $1 AND superseded_by IS NULL
GROUP BY status
`

type CountTestCasesByStatusRow struct {
	Status TestCaseStatus
	Total  int64
}

func (q *Queries) CountTestCasesByStatus(ctx context.Context, projectID uuid.UUID) ([]CountTestCasesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countTestCasesByStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTestCasesByStatusRow{}
	for rows.Next() {
		var i CountTestCasesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO requirements (
    project_id, artifact_id, endpoint_id, kind, title, body, source_ref, fingerprint, generated_by
)
VALUES (
    $1, $8::uuid, $9::uuid,
    $2, $3, $4, $5, $6, $7
)
ON CONFLICT (project_id, fingerprint) DO UPDATE
SET title = EXCLUDED.title, body = EXCLUDED.body
RETURNING id, project_id, artifact_id, endpoint_id, kind, title, body, source_ref,
          fingerprint, generated_by, created_at
`

type CreateRequirementParams struct {
	ProjectID   uuid.UUID
	Kind        RequirementKind
	Title       string
	Body        string
	SourceRef   string
	Fingerprint []byte
	GeneratedBy string
	ArtifactID  *uuid.UUID
	EndpointID  *uuid.UUID
}

// CreateRequirement conflicts on the fingerprint, so re-running extract on an
// unchanged artifact writes nothing new and returns what was already there.
func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error) {
	row := q.db.QueryRow(ctx, createRequirement,
		arg.ProjectID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.SourceRef,
		arg.Fingerprint,
		arg.GeneratedBy,
		arg.ArtifactID,
		arg.EndpointID,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ArtifactID,
		&i.EndpointID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.SourceRef,
		&i.Fingerprint,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (
    project_id, requirement_id, title, preconditions, steps, expected,
    priority, category, status, fingerprint, endpoint, generated_by, created_by
)
VALUES (
    $1, $12::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $13::uuid
)
RETURNING id, project_id, requirement_id, title, preconditions, steps, expected,
          priority, category, status, fingerprint, superseded_by, generated_by,
          created_by, created_at, updated_at, endpoint
`

type CreateTestCaseParams struct {
	ProjectID     uuid.UUID
	Title         string
	Preconditions string
	Steps         json.RawMessage
	Expected      string
	Priority      TestPriority
	Category      TestCategory
	Status        TestCaseStatus
	Fingerprint   []byte
	Endpoint      string
	GeneratedBy   string
	RequirementID *uuid.UUID
	CreatedBy     *uuid.UUID
}

// CreateTestCase is the single-row path, used by manual authoring and by the
// dedupe pass. Bulk generation uses CopyFrom instead.
func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.ProjectID,
		arg.Title,
		arg.Preconditions,
		arg.Steps,
		arg.Expected,
		arg.Priority,
		arg.Category,
		arg.Status,
		arg.Fingerprint,
		arg.Endpoint,
		arg.GeneratedBy,
		arg.RequirementID,
		arg.CreatedBy,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequirementID,
		&i.Title,
		&i.Preconditions,
		&i.Steps,
		&i.Expected,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Fingerprint,
		&i.SupersededBy,
		&i.GeneratedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Endpoint,
	)
	return i, err
}

type CreateTestCasesBulkParams struct {
	ProjectID     uuid.UUID
	RequirementID *uuid.UUID
	Title         string
	Preconditions string
	Steps         json.RawMessage
	Expected      string
	Priority      TestPriority
	Category      TestCategory
	Status        TestCaseStatus
	Fingerprint   []byte
	Endpoint      string
	GeneratedBy   string
}

const deleteEndpointsForArtifact = `-- name: DeleteEndpointsForArtifact :execrows
DELETE FROM endpoints WHERE artifact_id = $1
`

func (q *Queries) DeleteEndpointsForArtifact(ctx context.Context, artifactID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndpointsForArtifact, artifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTestCase = `-- name: DeleteTestCase :execrows
DELETE FROM test_cases WHERE id = $1
`

func (q *Queries) DeleteTestCase(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTestCase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequirement = `-- name: GetRequirement :one
SELECT id, project_id, artifact_id, endpoint_id, kind, title, body, source_ref,
       fingerprint, generated_by, created_at
FROM requirements
WHERE id = $1
`

func (q *Queries) GetRequirement(ctx context.Context, id uuid.UUID) (Requirement, error) {
	row := q.db.QueryRow(ctx, getRequirement, id)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ArtifactID,
		&i.EndpointID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.SourceRef,
		&i.Fingerprint,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTestCase = `-- name: GetTestCase :one
SELECT id, project_id, requirement_id, title, preconditions, steps, expected,
       priority, category, status, fingerprint, superseded_by, generated_by,
       created_by, created_at, updated_at, endpoint
FROM test_cases
WHERE id = $1
`

func (q *Queries) GetTestCase(ctx context.Context, id uuid.UUID) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, id)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequirementID,
		&i.Title,
		&i.Preconditions,
		&i.Steps,
		&i.Expected,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Fingerprint,
		&i.SupersededBy,
		&i.GeneratedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Endpoint,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, project_id, artifact_id, method, path, operation_id, summary, description,
       parameters, request, responses, security, source_ref, created_at
FROM endpoints
WHERE project_id = $1
  AND ($2::uuid IS NULL OR artifact_id = $2::uuid)
ORDER BY path, method
`

type ListEndpointsParams struct {
	ProjectID  uuid.UUID
	ArtifactID *uuid.UUID
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints, arg.ProjectID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ArtifactID,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Description,
			&i.Parameters,
			&i.Request,
			&i.Responses,
			&i.Security,
			&i.SourceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirements = `-- name: ListRequirements :many
SELECT id, project_id, artifact_id, endpoint_id, kind, title, body, source_ref,
       fingerprint, generated_by, created_at
FROM requirements
WHERE project_id = $1
  AND ($2::uuid IS NULL OR artifact_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $4
`

type ListRequirementsParams struct {
	ProjectID  uuid.UUID
	ArtifactID *uuid.UUID
	Cursor     *time.Time
	PageSize   int32
}

func (q *Queries) ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]Requirement, error) {
	rows, err := q.db.Query(ctx, listRequirements,
		arg.ProjectID,
		arg.ArtifactID,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Requirement{}
	for rows.Next() {
		var i Requirement
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ArtifactID,
			&i.EndpointID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.SourceRef,
			&i.Fingerprint,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesByFingerprint = `-- name: ListTestCasesByFingerprint :many
SELECT id, fingerprint
FROM test_cases
WHERE project_id = $1 AND superseded_by IS NULL
  AND fingerprint = ANY($2::bytea[])
`

type ListTestCasesByFingerprintParams struct {
	ProjectID    uuid.UUID
	Fingerprints [][]byte
}

type ListTestCasesByFingerprintRow struct {
	ID          uuid.UUID
	Fingerprint []byte
}

// ListTestCasesByFingerprint is how the generation pass learns what it already
// has before writing, so an unchanged spec produces zero new rows.
func (q *Queries) ListTestCasesByFingerprint(ctx context.Context, arg ListTestCasesByFingerprintParams) ([]ListTestCasesByFingerprintRow, error) {
	rows, err := q.db.Query(ctx, listTestCasesByFingerprint, arg.ProjectID, arg.Fingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestCasesByFingerprintRow{}
	for rows.Next() {
		var i ListTestCasesByFingerprintRow
		if err := rows.Scan(&i.ID, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesForRequirement = `-- name: ListTestCasesForRequirement :many
SELECT id, project_id, requirement_id, title, preconditions, steps, expected,
       priority, category, status, fingerprint, superseded_by, generated_by,
       created_by, created_at, updated_at, endpoint
FROM test_cases
WHERE requirement_id = $1 AND superseded_by IS NULL
ORDER BY created_at
`

// ListTestCasesForRequirement is the narrow candidate set the AI dedupe pass
// compares against, which is what keeps that cost bounded (F-5.4).
func (q *Queries) ListTestCasesForRequirement(ctx context.Context, requirementID *uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesForRequirement, requirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RequirementID,
			&i.Title,
			&i.Preconditions,
			&i.Steps,
			&i.Expected,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Fingerprint,
			&i.SupersededBy,
			&i.GeneratedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Endpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requirementCoverage = `-- name: RequirementCoverage :many
SELECT r.id, r.kind, r.title, r.source_ref,
       count(t.id) FILTER (WHERE t.superseded_by IS NULL)::bigint AS test_case_count
FROM requirements r
LEFT JOIN test_cases t ON t.requirement_id = r.id
WHERE r.project_id = $1
GROUP BY r.id, r.kind, r.title, r.source_ref
ORDER BY test_case_count, r.title
`

type RequirementCoverageRow struct {
	ID            uuid.UUID
	Kind          RequirementKind
	Title         string
	SourceRef     string
	TestCaseCount int64
}

// RequirementCoverage answers "which requirements have test cases" as one indexed
// query, which is what BE-2.1 exists to make possible. Passing coverage arrives
// with runs in phase 4; this is the generation half (FR-7.2 keeps the two numbers
// separate).
func (q *Queries) RequirementCoverage(ctx context.Context, projectID uuid.UUID) ([]RequirementCoverageRow, error) {
	rows, err := q.db.Query(ctx, requirementCoverage, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequirementCoverageRow{}
	for rows.Next() {
		var i RequirementCoverageRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.SourceRef,
			&i.TestCaseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestCaseStatus = `-- name: SetTestCaseStatus :execrows
UPDATE test_cases
SET status = $2, updated_at = now()
WHERE id = ANY($3::uuid[]) AND project_id = $1 AND superseded_by IS NULL
`

type SetTestCaseStatusParams struct {
	ProjectID uuid.UUID
	Status    TestCaseStatus
	Ids       []uuid.UUID
}

// SetTestCaseStatus backs bulk approve and reject. The batch is capped by the
// service and runs in one transaction.
func (q *Queries) SetTestCaseStatus(ctx context.Context, arg SetTestCaseStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTestCaseStatus, arg.ProjectID, arg.Status, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeTestCase = `-- name: SupersedeTestCase :execrows
UPDATE test_cases
SET superseded_by = $2, updated_at = now()
WHERE id = $1 AND superseded_by IS NULL
`

type SupersedeTestCaseParams struct {
	ID           uuid.UUID
	SupersededBy *uuid.UUID
}

// SupersedeTestCase records a merge rather than deleting the loser, so "why is
// this case gone" has an answer.
func (q *Queries) SupersedeTestCase(ctx context.Context, arg SupersedeTestCaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeTestCase, arg.ID, arg.SupersededBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTestCase = `-- name: UpdateTestCase :one
UPDATE test_cases
SET title = $2, preconditions = $3, steps = $4, expected = $5,
    priority = $6, category = $7, status = $8, updated_at = now()
WHERE id = $1 AND superseded_by IS NULL
RETURNING id, project_id, requirement_id, title, preconditions, steps, expected,
          priority, category, status, fingerprint, superseded_by, generated_by,
          created_by, created_at, updated_at, endpoint
`

type UpdateTestCaseParams struct {
	ID            uuid.UUID
	Title         string
	Preconditions string
	Steps         json.RawMessage
	Expected      string
	Priority      TestPriority
	Category      TestCategory
	Status        TestCaseStatus
}

func (q *Queries) UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, updateTestCase,
		arg.ID,
		arg.Title,
		arg.Preconditions,
		arg.Steps,
		arg.Expected,
		arg.Priority,
		arg.Category,
		arg.Status,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequirementID,
		&i.Title,
		&i.Preconditions,
		&i.Steps,
		&i.Expected,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Fingerprint,
		&i.SupersededBy,
		&i.GeneratedBy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Endpoint,
	)
	return i, err
}

const upsertEndpoint = `-- name: UpsertEndpoint :one

INSERT INTO endpoints (
    project_id, artifact_id, method, path, operation_id, summary, description,
    parameters, request, responses, security, source_ref
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (artifact_id, method, path) DO UPDATE
SET operation_id = EXCLUDED.operation_id,
    summary      = EXCLUDED.summary,
    description  = EXCLUDED.description,
    parameters   = EXCLUDED.parameters,
    request      = EXCLUDED.request,
    responses    = EXCLUDED.responses,
    security     = EXCLUDED.security,
    source_ref   = EXCLUDED.source_ref
RETURNING id, project_id, artifact_id, method, path, operation_id, summary, description,
          parameters, request, responses, security, source_ref, created_at
`

type UpsertEndpointParams struct {
	ProjectID   uuid.UUID
	ArtifactID  uuid.UUID
	Method      string
	Path        string
	OperationID string
	Summary     string
	Description string
	Parameters  json.RawMessage
	Request     json.RawMessage
	Responses   json.RawMessage
	Security    json.RawMessage
	SourceRef   string
}

// Ingest and generation: endpoints, requirements, and test cases.
//
// Two ideas run through this file. Re-running work is free, because the unique
// indexes turn a repeat into a conflict rather than a duplicate. And bulk writes
// are one statement: 400 test cases is a CopyFrom, not 400 round trips inside a
// transaction that is now long (backend-standards.md 8).
// UpsertEndpoint makes re-parsing an artifact idempotent. A changed spec updates
// the row it already had rather than leaving two versions of one endpoint.
func (q *Queries) UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, upsertEndpoint,
		arg.ProjectID,
		arg.ArtifactID,
		arg.Method,
		arg.Path,
		arg.OperationID,
		arg.Summary,
		arg.Description,
		arg.Parameters,
		arg.Request,
		arg.Responses,
		arg.Security,
		arg.SourceRef,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ArtifactID,
		&i.Method,
		&i.Path,
		&i.OperationID,
		&i.Summary,
		&i.Description,
		&i.Parameters,
		&i.Request,
		&i.Responses,
		&i.Security,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}
