// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendJobEvent = `-- name: AppendJobEvent :one
INSERT INTO job_events (job_id, level, message)
VALUES ($1, $2, $3)
RETURNING id, job_id, level, message, at
`

type AppendJobEventParams struct {
	JobID   uuid.UUID
	Level   JobEventLevel
	Message string
}

func (q *Queries) AppendJobEvent(ctx context.Context, arg AppendJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, appendJobEvent, arg.JobID, arg.Level, arg.Message)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Level,
		&i.Message,
		&i.At,
	)
	return i, err
}

const cancelJob = `-- name: CancelJob :execrows
UPDATE jobs
SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CancelJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, count(*) AS total
FROM jobs
WHERE project_id = $1
GROUP BY status
`

type CountJobsByStatusRow struct {
	Status JobStatus
	Total  int64
}

func (q *Queries) CountJobsByStatus(ctx context.Context, projectID *uuid.UUID) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (project_id, type, payload, idempotency_key, correlation_id, parent_job_id, enqueued_by, max_attempts)
VALUES (
    $6::uuid, $1, $2, $3, $4,
    $7::uuid, $8::uuid, $5
)
ON CONFLICT (type, idempotency_key) DO UPDATE
SET type = jobs.type
RETURNING id, project_id, type, status, progress, attempts, max_attempts, error,
          parent_job_id, payload, idempotency_key, correlation_id, enqueued_by,
          queued_at, started_at, finished_at,
          (jobs.queued_at < now() - interval '1 microsecond') AS existed
`

type EnqueueJobParams struct {
	Type           string
	Payload        json.RawMessage
	IdempotencyKey string
	CorrelationID  string
	MaxAttempts    int16
	ProjectID      *uuid.UUID
	ParentJobID    *uuid.UUID
	EnqueuedBy     *uuid.UUID
}

type EnqueueJobRow struct {
	ID             uuid.UUID
	ProjectID      *uuid.UUID
	Type           string
	Status         JobStatus
	Progress       int16
	Attempts       int16
	MaxAttempts    int16
	Error          *string
	ParentJobID    *uuid.UUID
	Payload        json.RawMessage
	IdempotencyKey string
	CorrelationID  string
	EnqueuedBy     *uuid.UUID
	QueuedAt       time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
	Existed        bool
}

// Jobs and job events.
//
// The jobs row is the durable record of what ran. Redis holds only in-flight
// coordination.
// EnqueueJob is idempotent by unique index on (type, idempotency_key). A retried
// enqueue returns the existing row instead of creating a second one, which is what
// makes NFR-4 structural rather than disciplined.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Type,
		arg.Payload,
		arg.IdempotencyKey,
		arg.CorrelationID,
		arg.MaxAttempts,
		arg.ProjectID,
		arg.ParentJobID,
		arg.EnqueuedBy,
	)
	var i EnqueueJobRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.ParentJobID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.EnqueuedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Existed,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, project_id, type, status, progress, attempts, max_attempts, error,
       parent_job_id, payload, idempotency_key, correlation_id, enqueued_by,
       queued_at, started_at, finished_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.ParentJobID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.EnqueuedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listChainEventsSince = `-- name: ListChainEventsSince :many
SELECT e.id, e.job_id, e.level, e.message, e.at
FROM job_events e
JOIN jobs j ON j.id = e.job_id
WHERE (j.id = $1 OR j.parent_job_id = $1) AND e.id > $2
ORDER BY e.id
LIMIT $3
`

type ListChainEventsSinceParams struct {
	ID       uuid.UUID
	ID_2     int64
	PageSize int32
}

// ListChainEventsSince is the same, widened to a chain.
//
// Handlers write their log lines against the stage that is running, so a viewer
// watching the submission would otherwise see an empty log while three stages
// narrated themselves. Asking for a stage still returns only that stage's lines,
// because a stage has no children.
func (q *Queries) ListChainEventsSince(ctx context.Context, arg ListChainEventsSinceParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listChainEventsSince, arg.ID, arg.ID_2, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Level,
			&i.Message,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildJobs = `-- name: ListChildJobs :many
SELECT id, project_id, type, status, progress, attempts, max_attempts, error,
       parent_job_id, payload, idempotency_key, correlation_id, enqueued_by,
       queued_at, started_at, finished_at
FROM jobs
WHERE parent_job_id = $1
ORDER BY queued_at
`

func (q *Queries) ListChildJobs(ctx context.Context, parentJobID *uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listChildJobs, parentJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.ParentJobID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.EnqueuedBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEventsSince = `-- name: ListJobEventsSince :many
SELECT id, job_id, level, message, at
FROM job_events
WHERE job_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListJobEventsSinceParams struct {
	JobID    uuid.UUID
	ID       int64
	PageSize int32
}

// ListJobEventsSince backs the SSE stream. The bigserial id doubles as the
// Last-Event-ID cursor, so a reconnect resumes without gaps or duplicates.
func (q *Queries) ListJobEventsSince(ctx context.Context, arg ListJobEventsSinceParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsSince, arg.JobID, arg.ID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Level,
			&i.Message,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForProject = `-- name: ListJobsForProject :many
SELECT id, project_id, type, status, progress, attempts, max_attempts, error,
       parent_job_id, payload, idempotency_key, correlation_id, enqueued_by,
       queued_at, started_at, finished_at
FROM jobs
WHERE project_id = $1
  AND ($2::timestamptz IS NULL OR queued_at < $2::timestamptz)
ORDER BY queued_at DESC
LIMIT $3
`

type ListJobsForProjectParams struct {
	ProjectID *uuid.UUID
	Cursor    *time.Time
	PageSize  int32
}

func (q *Queries) ListJobsForProject(ctx context.Context, arg ListJobsForProjectParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsForProject, arg.ProjectID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.ParentJobID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.CorrelationID,
			&i.EnqueuedBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChainRunning = `-- name: MarkChainRunning :execrows
UPDATE jobs
SET status = 'running',
    started_at = coalesce(started_at, now())
WHERE id = $1 AND status = 'queued'
`

// MarkChainRunning moves a parent row out of queued when its first stage starts.
//
// Deliberately not MarkJobRunning: that counts an attempt, and a parent is not
// attempted. A three-stage chain would otherwise report three attempts on a
// submission that never failed once.
func (q *Queries) MarkChainRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markChainRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobFailed = `-- name: MarkJobFailed :execrows
UPDATE jobs
SET status = 'failed', finished_at = now(), error = $2
WHERE id = $1 AND status IN ('queued', 'running')
`

type MarkJobFailedParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobFailed, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobQueuedForRetry = `-- name: MarkJobQueuedForRetry :execrows
UPDATE jobs
SET status = 'queued', error = $2
WHERE id = $1 AND status = 'running'
`

type MarkJobQueuedForRetryParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) MarkJobQueuedForRetry(ctx context.Context, arg MarkJobQueuedForRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markJobQueuedForRetry, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobRunning = `-- name: MarkJobRunning :execrows
UPDATE jobs
SET status = 'running',
    attempts = attempts + 1,
    started_at = coalesce(started_at, now())
WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) MarkJobRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markJobRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobSucceeded = `-- name: MarkJobSucceeded :execrows
UPDATE jobs
SET status = 'succeeded', progress = 100, finished_at = now(), error = NULL
WHERE id = $1 AND status = 'running'
`

func (q *Queries) MarkJobSucceeded(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markJobSucceeded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobProgress = `-- name: SetJobProgress :execrows
UPDATE jobs
SET progress = $2
WHERE id = $1 AND status = 'running'
`

type SetJobProgressParams struct {
	ID       uuid.UUID
	Progress int16
}

func (q *Queries) SetJobProgress(ctx context.Context, arg SetJobProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJobProgress, arg.ID, arg.Progress)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
