// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMCPServer = `-- name: CreateMCPServer :one

INSERT INTO mcp_servers (
    name, transport, command, args, url, credentials, scope, scope_id,
    enabled_tools, auto_write, is_enabled, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, transport, command, args, url, credentials, scope, scope_id,
          enabled_tools, discovered_tools, auto_write, is_enabled, health_status,
          health_checked_at, health_detail, created_by, created_at, updated_at
`

type CreateMCPServerParams struct {
	Name         string
	Transport    McpTransport
	Command      string
	Args         []string
	Url          string
	Credentials  json.RawMessage
	Scope        McpScope
	ScopeID      *uuid.UUID
	EnabledTools []string
	AutoWrite    bool
	IsEnabled    bool
	CreatedBy    *uuid.UUID
}

// MCP servers and call audit (BE-10.1).
func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.Name,
		arg.Transport,
		arg.Command,
		arg.Args,
		arg.Url,
		arg.Credentials,
		arg.Scope,
		arg.ScopeID,
		arg.EnabledTools,
		arg.AutoWrite,
		arg.IsEnabled,
		arg.CreatedBy,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Command,
		&i.Args,
		&i.Url,
		&i.Credentials,
		&i.Scope,
		&i.ScopeID,
		&i.EnabledTools,
		&i.DiscoveredTools,
		&i.AutoWrite,
		&i.IsEnabled,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :execrows
DELETE FROM mcp_servers WHERE id = $1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, name, transport, command, args, url, credentials, scope, scope_id,
       enabled_tools, discovered_tools, auto_write, is_enabled, health_status,
       health_checked_at, health_detail, created_by, created_at, updated_at
FROM mcp_servers
WHERE id = $1
`

func (q *Queries) GetMCPServer(ctx context.Context, id uuid.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Command,
		&i.Args,
		&i.Url,
		&i.Credentials,
		&i.Scope,
		&i.ScopeID,
		&i.EnabledTools,
		&i.DiscoveredTools,
		&i.AutoWrite,
		&i.IsEnabled,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMCPServers = `-- name: ListAllMCPServers :many
SELECT id, name, transport, command, args, url, credentials, scope, scope_id,
       enabled_tools, discovered_tools, auto_write, is_enabled, health_status,
       health_checked_at, health_detail, created_by, created_at, updated_at
FROM mcp_servers
ORDER BY scope, name
`

func (q *Queries) ListAllMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listAllMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.Command,
			&i.Args,
			&i.Url,
			&i.Credentials,
			&i.Scope,
			&i.ScopeID,
			&i.EnabledTools,
			&i.DiscoveredTools,
			&i.AutoWrite,
			&i.IsEnabled,
			&i.HealthStatus,
			&i.HealthCheckedAt,
			&i.HealthDetail,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPCalls = `-- name: ListMCPCalls :many
SELECT id, server_id, server_name, tool, arguments, status, error, agent, project_id, job_id, at
FROM mcp_calls
WHERE ($1::uuid IS NULL OR server_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
ORDER BY at DESC
LIMIT $3
`

type ListMCPCallsParams struct {
	ServerID  *uuid.UUID
	ProjectID *uuid.UUID
	PageSize  int32
}

func (q *Queries) ListMCPCalls(ctx context.Context, arg ListMCPCallsParams) ([]McpCall, error) {
	rows, err := q.db.Query(ctx, listMCPCalls, arg.ServerID, arg.ProjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpCall{}
	for rows.Next() {
		var i McpCall
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.ServerName,
			&i.Tool,
			&i.Arguments,
			&i.Status,
			&i.Error,
			&i.Agent,
			&i.ProjectID,
			&i.JobID,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServersForScope = `-- name: ListMCPServersForScope :many
SELECT id, name, transport, command, args, url, credentials, scope, scope_id,
       enabled_tools, discovered_tools, auto_write, is_enabled, health_status,
       health_checked_at, health_detail, created_by, created_at, updated_at
FROM mcp_servers
WHERE is_enabled
  AND (scope = 'global' OR (scope = 'project' AND scope_id = $1))
ORDER BY name
`

// ListMCPServersForScope is what an agent's tool loader reads: the enabled servers a
// project may use, which is the global ones plus that project's own. The per-project
// boundary is here — another project's servers are never returned.
func (q *Queries) ListMCPServersForScope(ctx context.Context, scopeID *uuid.UUID) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersForScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.Command,
			&i.Args,
			&i.Url,
			&i.Credentials,
			&i.Scope,
			&i.ScopeID,
			&i.EnabledTools,
			&i.DiscoveredTools,
			&i.AutoWrite,
			&i.IsEnabled,
			&i.HealthStatus,
			&i.HealthCheckedAt,
			&i.HealthDetail,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMCPCall = `-- name: RecordMCPCall :exec
INSERT INTO mcp_calls (server_id, server_name, tool, arguments, status, error, agent, project_id, job_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordMCPCallParams struct {
	ServerID   *uuid.UUID
	ServerName string
	Tool       string
	Arguments  json.RawMessage
	Status     string
	Error      string
	Agent      string
	ProjectID  *uuid.UUID
	JobID      *uuid.UUID
}

func (q *Queries) RecordMCPCall(ctx context.Context, arg RecordMCPCallParams) error {
	_, err := q.db.Exec(ctx, recordMCPCall,
		arg.ServerID,
		arg.ServerName,
		arg.Tool,
		arg.Arguments,
		arg.Status,
		arg.Error,
		arg.Agent,
		arg.ProjectID,
		arg.JobID,
	)
	return err
}

const recordMCPHealth = `-- name: RecordMCPHealth :exec
UPDATE mcp_servers
SET health_status = $2, health_detail = $3, discovered_tools = $4, health_checked_at = now(),
    updated_at = now()
WHERE id = $1
`

type RecordMCPHealthParams struct {
	ID              uuid.UUID
	HealthStatus    McpHealth
	HealthDetail    string
	DiscoveredTools json.RawMessage
}

func (q *Queries) RecordMCPHealth(ctx context.Context, arg RecordMCPHealthParams) error {
	_, err := q.db.Exec(ctx, recordMCPHealth,
		arg.ID,
		arg.HealthStatus,
		arg.HealthDetail,
		arg.DiscoveredTools,
	)
	return err
}

const setMCPCredentials = `-- name: SetMCPCredentials :exec
UPDATE mcp_servers SET credentials = $2, updated_at = now() WHERE id = $1
`

type SetMCPCredentialsParams struct {
	ID          uuid.UUID
	Credentials json.RawMessage
}

func (q *Queries) SetMCPCredentials(ctx context.Context, arg SetMCPCredentialsParams) error {
	_, err := q.db.Exec(ctx, setMCPCredentials, arg.ID, arg.Credentials)
	return err
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers
SET name = $2, transport = $3, command = $4, args = $5, url = $6,
    scope = $7, scope_id = $8, enabled_tools = $9, auto_write = $10, is_enabled = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, name, transport, command, args, url, credentials, scope, scope_id,
          enabled_tools, discovered_tools, auto_write, is_enabled, health_status,
          health_checked_at, health_detail, created_by, created_at, updated_at
`

type UpdateMCPServerParams struct {
	ID           uuid.UUID
	Name         string
	Transport    McpTransport
	Command      string
	Args         []string
	Url          string
	Scope        McpScope
	ScopeID      *uuid.UUID
	EnabledTools []string
	AutoWrite    bool
	IsEnabled    bool
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.ID,
		arg.Name,
		arg.Transport,
		arg.Command,
		arg.Args,
		arg.Url,
		arg.Scope,
		arg.ScopeID,
		arg.EnabledTools,
		arg.AutoWrite,
		arg.IsEnabled,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Command,
		&i.Args,
		&i.Url,
		&i.Credentials,
		&i.Scope,
		&i.ScopeID,
		&i.EnabledTools,
		&i.DiscoveredTools,
		&i.AutoWrite,
		&i.IsEnabled,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthDetail,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
