// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mocks.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getMockServer = `-- name: GetMockServer :one
SELECT project_id, container_id, status, url, host_port, routes, faults, route_count,
       image, error, started_by, started_at, stopped_at, created_at, updated_at
FROM mock_servers
WHERE project_id = $1
`

func (q *Queries) GetMockServer(ctx context.Context, projectID uuid.UUID) (MockServer, error) {
	row := q.db.QueryRow(ctx, getMockServer, projectID)
	var i MockServer
	err := row.Scan(
		&i.ProjectID,
		&i.ContainerID,
		&i.Status,
		&i.Url,
		&i.HostPort,
		&i.Routes,
		&i.Faults,
		&i.RouteCount,
		&i.Image,
		&i.Error,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunningMocks = `-- name: ListRunningMocks :many
SELECT project_id, container_id, status, url, host_port, routes, faults, route_count,
       image, error, started_by, started_at, stopped_at, created_at, updated_at
FROM mock_servers
WHERE status = 'running'
ORDER BY started_at
`

// ListRunningMocks is what a sweeper reconciles against the host: a row that says
// running with no container behind it is a row a UI is lying with.
func (q *Queries) ListRunningMocks(ctx context.Context) ([]MockServer, error) {
	rows, err := q.db.Query(ctx, listRunningMocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MockServer{}
	for rows.Next() {
		var i MockServer
		if err := rows.Scan(
			&i.ProjectID,
			&i.ContainerID,
			&i.Status,
			&i.Url,
			&i.HostPort,
			&i.Routes,
			&i.Faults,
			&i.RouteCount,
			&i.Image,
			&i.Error,
			&i.StartedBy,
			&i.StartedAt,
			&i.StoppedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMockStopped = `-- name: MarkMockStopped :one
UPDATE mock_servers
SET status = 'stopped', container_id = '', url = '', host_port = 0,
    stopped_at = now(), error = $2, updated_at = now()
WHERE project_id = $1
RETURNING project_id, container_id, status, url, host_port, routes, faults, route_count,
          image, error, started_by, started_at, stopped_at, created_at, updated_at
`

type MarkMockStoppedParams struct {
	ProjectID uuid.UUID
	Error     string
}

// MarkMockStopped records that the container is gone, keeping the routes so a restart
// serves the same mock.
func (q *Queries) MarkMockStopped(ctx context.Context, arg MarkMockStoppedParams) (MockServer, error) {
	row := q.db.QueryRow(ctx, markMockStopped, arg.ProjectID, arg.Error)
	var i MockServer
	err := row.Scan(
		&i.ProjectID,
		&i.ContainerID,
		&i.Status,
		&i.Url,
		&i.HostPort,
		&i.Routes,
		&i.Faults,
		&i.RouteCount,
		&i.Image,
		&i.Error,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMockServer = `-- name: UpsertMockServer :one

INSERT INTO mock_servers (
    project_id, container_id, status, url, host_port, routes, faults, route_count,
    image, error, started_by, started_at, stopped_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (project_id) DO UPDATE
SET container_id = EXCLUDED.container_id,
    status       = EXCLUDED.status,
    url          = EXCLUDED.url,
    host_port    = EXCLUDED.host_port,
    routes       = EXCLUDED.routes,
    faults       = EXCLUDED.faults,
    route_count  = EXCLUDED.route_count,
    image        = EXCLUDED.image,
    error        = EXCLUDED.error,
    started_by   = EXCLUDED.started_by,
    started_at   = EXCLUDED.started_at,
    stopped_at   = EXCLUDED.stopped_at,
    updated_at   = now()
RETURNING project_id, container_id, status, url, host_port, routes, faults, route_count,
          image, error, started_by, started_at, stopped_at, created_at, updated_at
`

type UpsertMockServerParams struct {
	ProjectID   uuid.UUID
	ContainerID string
	Status      string
	Url         string
	HostPort    int32
	Routes      json.RawMessage
	Faults      json.RawMessage
	RouteCount  int32
	Image       string
	Error       string
	StartedBy   *uuid.UUID
	StartedAt   *time.Time
	StoppedAt   *time.Time
}

// Mock servers (BE-8.6). One row per project: a project has one mock, and restarting
// replaces its container rather than adding a row.
func (q *Queries) UpsertMockServer(ctx context.Context, arg UpsertMockServerParams) (MockServer, error) {
	row := q.db.QueryRow(ctx, upsertMockServer,
		arg.ProjectID,
		arg.ContainerID,
		arg.Status,
		arg.Url,
		arg.HostPort,
		arg.Routes,
		arg.Faults,
		arg.RouteCount,
		arg.Image,
		arg.Error,
		arg.StartedBy,
		arg.StartedAt,
		arg.StoppedAt,
	)
	var i MockServer
	err := row.Scan(
		&i.ProjectID,
		&i.ContainerID,
		&i.Status,
		&i.Url,
		&i.HostPort,
		&i.Routes,
		&i.Faults,
		&i.RouteCount,
		&i.Image,
		&i.Error,
		&i.StartedBy,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
