// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type DefectSeverity string

const (
	DefectSeverityCritical DefectSeverity = "critical"
	DefectSeverityHigh     DefectSeverity = "high"
	DefectSeverityMedium   DefectSeverity = "medium"
	DefectSeverityLow      DefectSeverity = "low"
)

func (e *DefectSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DefectSeverity(s)
	case string:
		*e = DefectSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for DefectSeverity: %T", src)
	}
	return nil
}

type NullDefectSeverity struct {
	DefectSeverity DefectSeverity
	Valid          bool // Valid is true if DefectSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDefectSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.DefectSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DefectSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDefectSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DefectSeverity), nil
}

type DefectStatus string

const (
	DefectStatusOpen         DefectStatus = "open"
	DefectStatusAcknowledged DefectStatus = "acknowledged"
	DefectStatusInProgress   DefectStatus = "in_progress"
	DefectStatusFixed        DefectStatus = "fixed"
	DefectStatusWontFix      DefectStatus = "wont_fix"
	DefectStatusDuplicate    DefectStatus = "duplicate"
)

func (e *DefectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DefectStatus(s)
	case string:
		*e = DefectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DefectStatus: %T", src)
	}
	return nil
}

type NullDefectStatus struct {
	DefectStatus DefectStatus
	Valid        bool // Valid is true if DefectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDefectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DefectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DefectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDefectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DefectStatus), nil
}

type JobEventLevel string

const (
	JobEventLevelDebug JobEventLevel = "debug"
	JobEventLevelInfo  JobEventLevel = "info"
	JobEventLevelWarn  JobEventLevel = "warn"
	JobEventLevelError JobEventLevel = "error"
)

func (e *JobEventLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobEventLevel(s)
	case string:
		*e = JobEventLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for JobEventLevel: %T", src)
	}
	return nil
}

type NullJobEventLevel struct {
	JobEventLevel JobEventLevel
	Valid         bool // Valid is true if JobEventLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobEventLevel) Scan(value interface{}) error {
	if value == nil {
		ns.JobEventLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobEventLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobEventLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobEventLevel), nil
}

type JobStatus string

const (
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusCancelled JobStatus = "cancelled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type LlmDataResidency string

const (
	LlmDataResidencyLocal    LlmDataResidency = "local"
	LlmDataResidencyRegional LlmDataResidency = "regional"
	LlmDataResidencyExternal LlmDataResidency = "external"
)

func (e *LlmDataResidency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmDataResidency(s)
	case string:
		*e = LlmDataResidency(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmDataResidency: %T", src)
	}
	return nil
}

type NullLlmDataResidency struct {
	LlmDataResidency LlmDataResidency
	Valid            bool // Valid is true if LlmDataResidency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmDataResidency) Scan(value interface{}) error {
	if value == nil {
		ns.LlmDataResidency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmDataResidency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmDataResidency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmDataResidency), nil
}

type LlmHealthStatus string

const (
	LlmHealthStatusUnknown LlmHealthStatus = "unknown"
	LlmHealthStatusOk      LlmHealthStatus = "ok"
	LlmHealthStatusFailing LlmHealthStatus = "failing"
)

func (e *LlmHealthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmHealthStatus(s)
	case string:
		*e = LlmHealthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmHealthStatus: %T", src)
	}
	return nil
}

type NullLlmHealthStatus struct {
	LlmHealthStatus LlmHealthStatus
	Valid           bool // Valid is true if LlmHealthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmHealthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LlmHealthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmHealthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmHealthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmHealthStatus), nil
}

type LlmProviderKind string

const (
	LlmProviderKindAnthropic        LlmProviderKind = "anthropic"
	LlmProviderKindBedrock          LlmProviderKind = "bedrock"
	LlmProviderKindVertex           LlmProviderKind = "vertex"
	LlmProviderKindOpenai           LlmProviderKind = "openai"
	LlmProviderKindAzureOpenai      LlmProviderKind = "azure-openai"
	LlmProviderKindGemini           LlmProviderKind = "gemini"
	LlmProviderKindOpenaiCompatible LlmProviderKind = "openai-compatible"
)

func (e *LlmProviderKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmProviderKind(s)
	case string:
		*e = LlmProviderKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmProviderKind: %T", src)
	}
	return nil
}

type NullLlmProviderKind struct {
	LlmProviderKind LlmProviderKind
	Valid           bool // Valid is true if LlmProviderKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmProviderKind) Scan(value interface{}) error {
	if value == nil {
		ns.LlmProviderKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmProviderKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmProviderKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmProviderKind), nil
}

type LlmScope string

const (
	LlmScopeGlobal  LlmScope = "global"
	LlmScopeProject LlmScope = "project"
)

func (e *LlmScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmScope(s)
	case string:
		*e = LlmScope(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmScope: %T", src)
	}
	return nil
}

type NullLlmScope struct {
	LlmScope LlmScope
	Valid    bool // Valid is true if LlmScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmScope) Scan(value interface{}) error {
	if value == nil {
		ns.LlmScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmScope), nil
}

type LlmTier string

const (
	LlmTierReasoning LlmTier = "reasoning"
	LlmTierCode      LlmTier = "code"
	LlmTierCheap     LlmTier = "cheap"
	LlmTierVision    LlmTier = "vision"
)

func (e *LlmTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmTier(s)
	case string:
		*e = LlmTier(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmTier: %T", src)
	}
	return nil
}

type NullLlmTier struct {
	LlmTier LlmTier
	Valid   bool // Valid is true if LlmTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmTier) Scan(value interface{}) error {
	if value == nil {
		ns.LlmTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmTier), nil
}

type McpHealth string

const (
	McpHealthUnknown     McpHealth = "unknown"
	McpHealthHealthy     McpHealth = "healthy"
	McpHealthUnreachable McpHealth = "unreachable"
)

func (e *McpHealth) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = McpHealth(s)
	case string:
		*e = McpHealth(s)
	default:
		return fmt.Errorf("unsupported scan type for McpHealth: %T", src)
	}
	return nil
}

type NullMcpHealth struct {
	McpHealth McpHealth
	Valid     bool // Valid is true if McpHealth is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMcpHealth) Scan(value interface{}) error {
	if value == nil {
		ns.McpHealth, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.McpHealth.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMcpHealth) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.McpHealth), nil
}

type McpScope string

const (
	McpScopeGlobal  McpScope = "global"
	McpScopeProject McpScope = "project"
)

func (e *McpScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = McpScope(s)
	case string:
		*e = McpScope(s)
	default:
		return fmt.Errorf("unsupported scan type for McpScope: %T", src)
	}
	return nil
}

type NullMcpScope struct {
	McpScope McpScope
	Valid    bool // Valid is true if McpScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMcpScope) Scan(value interface{}) error {
	if value == nil {
		ns.McpScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.McpScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMcpScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.McpScope), nil
}

type McpTransport string

const (
	McpTransportStdio McpTransport = "stdio"
	McpTransportHttp  McpTransport = "http"
)

func (e *McpTransport) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = McpTransport(s)
	case string:
		*e = McpTransport(s)
	default:
		return fmt.Errorf("unsupported scan type for McpTransport: %T", src)
	}
	return nil
}

type NullMcpTransport struct {
	McpTransport McpTransport
	Valid        bool // Valid is true if McpTransport is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMcpTransport) Scan(value interface{}) error {
	if value == nil {
		ns.McpTransport, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.McpTransport.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMcpTransport) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.McpTransport), nil
}

type RepoProvider string

const (
	RepoProviderGit       RepoProvider = "git"
	RepoProviderGithub    RepoProvider = "github"
	RepoProviderGitlab    RepoProvider = "gitlab"
	RepoProviderBitbucket RepoProvider = "bitbucket"
	RepoProviderArchive   RepoProvider = "archive"
)

func (e *RepoProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RepoProvider(s)
	case string:
		*e = RepoProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for RepoProvider: %T", src)
	}
	return nil
}

type NullRepoProvider struct {
	RepoProvider RepoProvider
	Valid        bool // Valid is true if RepoProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRepoProvider) Scan(value interface{}) error {
	if value == nil {
		ns.RepoProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RepoProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRepoProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RepoProvider), nil
}

type ReportFormat string

const (
	ReportFormatHtml ReportFormat = "html"
	ReportFormatPdf  ReportFormat = "pdf"
)

func (e *ReportFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportFormat(s)
	case string:
		*e = ReportFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportFormat: %T", src)
	}
	return nil
}

type NullReportFormat struct {
	ReportFormat ReportFormat
	Valid        bool // Valid is true if ReportFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ReportFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportFormat), nil
}

type ReportStatus string

const (
	ReportStatusQueued  ReportStatus = "queued"
	ReportStatusRunning ReportStatus = "running"
	ReportStatusReady   ReportStatus = "ready"
	ReportStatusFailed  ReportStatus = "failed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type RequirementKind string

const (
	RequirementKindFeature        RequirementKind = "feature"
	RequirementKindBusinessRule   RequirementKind = "business_rule"
	RequirementKindValidationRule RequirementKind = "validation_rule"
	RequirementKindAuth           RequirementKind = "auth"
	RequirementKindEdgeCase       RequirementKind = "edge_case"
)

func (e *RequirementKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequirementKind(s)
	case string:
		*e = RequirementKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RequirementKind: %T", src)
	}
	return nil
}

type NullRequirementKind struct {
	RequirementKind RequirementKind
	Valid           bool // Valid is true if RequirementKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequirementKind) Scan(value interface{}) error {
	if value == nil {
		ns.RequirementKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequirementKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequirementKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequirementKind), nil
}

type RunKind string

const (
	RunKindFunctional  RunKind = "functional"
	RunKindPerformance RunKind = "performance"
	RunKindSecurity    RunKind = "security"
)

func (e *RunKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunKind(s)
	case string:
		*e = RunKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RunKind: %T", src)
	}
	return nil
}

type NullRunKind struct {
	RunKind RunKind
	Valid   bool // Valid is true if RunKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunKind) Scan(value interface{}) error {
	if value == nil {
		ns.RunKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunKind), nil
}

type RunResultStatus string

const (
	RunResultStatusPassed  RunResultStatus = "passed"
	RunResultStatusFailed  RunResultStatus = "failed"
	RunResultStatusFlaky   RunResultStatus = "flaky"
	RunResultStatusSkipped RunResultStatus = "skipped"
	RunResultStatusErrored RunResultStatus = "errored"
)

func (e *RunResultStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunResultStatus(s)
	case string:
		*e = RunResultStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunResultStatus: %T", src)
	}
	return nil
}

type NullRunResultStatus struct {
	RunResultStatus RunResultStatus
	Valid           bool // Valid is true if RunResultStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunResultStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunResultStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunResultStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunResultStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunResultStatus), nil
}

type RunStatus string

const (
	RunStatusQueued    RunStatus = "queued"
	RunStatusRunning   RunStatus = "running"
	RunStatusPassed    RunStatus = "passed"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusErrored   RunStatus = "errored"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus
	Valid     bool // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type RunTrigger string

const (
	RunTriggerManual   RunTrigger = "manual"
	RunTriggerSchedule RunTrigger = "schedule"
	RunTriggerWebhook  RunTrigger = "webhook"
	RunTriggerCi       RunTrigger = "ci"
)

func (e *RunTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunTrigger(s)
	case string:
		*e = RunTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for RunTrigger: %T", src)
	}
	return nil
}

type NullRunTrigger struct {
	RunTrigger RunTrigger
	Valid      bool // Valid is true if RunTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.RunTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunTrigger), nil
}

type SettingsScope string

const (
	SettingsScopeGlobal  SettingsScope = "global"
	SettingsScopeProject SettingsScope = "project"
	SettingsScopeUser    SettingsScope = "user"
)

func (e *SettingsScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettingsScope(s)
	case string:
		*e = SettingsScope(s)
	default:
		return fmt.Errorf("unsupported scan type for SettingsScope: %T", src)
	}
	return nil
}

type NullSettingsScope struct {
	SettingsScope SettingsScope
	Valid         bool // Valid is true if SettingsScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettingsScope) Scan(value interface{}) error {
	if value == nil {
		ns.SettingsScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettingsScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettingsScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettingsScope), nil
}

type TestCaseStatus string

const (
	TestCaseStatusDraft    TestCaseStatus = "draft"
	TestCaseStatusApproved TestCaseStatus = "approved"
	TestCaseStatusRejected TestCaseStatus = "rejected"
)

func (e *TestCaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestCaseStatus(s)
	case string:
		*e = TestCaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestCaseStatus: %T", src)
	}
	return nil
}

type NullTestCaseStatus struct {
	TestCaseStatus TestCaseStatus
	Valid          bool // Valid is true if TestCaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestCaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestCaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestCaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestCaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestCaseStatus), nil
}

type TestCategory string

const (
	TestCategoryFunctional  TestCategory = "functional"
	TestCategoryNegative    TestCategory = "negative"
	TestCategoryBoundary    TestCategory = "boundary"
	TestCategorySecurity    TestCategory = "security"
	TestCategoryAuth        TestCategory = "auth"
	TestCategoryPerformance TestCategory = "performance"
	TestCategoryData        TestCategory = "data"
)

func (e *TestCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestCategory(s)
	case string:
		*e = TestCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TestCategory: %T", src)
	}
	return nil
}

type NullTestCategory struct {
	TestCategory TestCategory
	Valid        bool // Valid is true if TestCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TestCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestCategory), nil
}

type TestFramework string

const (
	TestFrameworkSupertest  TestFramework = "supertest"
	TestFrameworkPostman    TestFramework = "postman"
	TestFrameworkJest       TestFramework = "jest"
	TestFrameworkVitest     TestFramework = "vitest"
	TestFrameworkPlaywright TestFramework = "playwright"
	TestFrameworkCypress    TestFramework = "cypress"
	TestFrameworkK6         TestFramework = "k6"
	TestFrameworkPytest     TestFramework = "pytest"
	TestFrameworkSecurity   TestFramework = "security"
)

func (e *TestFramework) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestFramework(s)
	case string:
		*e = TestFramework(s)
	default:
		return fmt.Errorf("unsupported scan type for TestFramework: %T", src)
	}
	return nil
}

type NullTestFramework struct {
	TestFramework TestFramework
	Valid         bool // Valid is true if TestFramework is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestFramework) Scan(value interface{}) error {
	if value == nil {
		ns.TestFramework, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestFramework.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestFramework) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestFramework), nil
}

type TestPriority string

const (
	TestPriorityCritical TestPriority = "critical"
	TestPriorityHigh     TestPriority = "high"
	TestPriorityMedium   TestPriority = "medium"
	TestPriorityLow      TestPriority = "low"
)

func (e *TestPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestPriority(s)
	case string:
		*e = TestPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TestPriority: %T", src)
	}
	return nil
}

type NullTestPriority struct {
	TestPriority TestPriority
	Valid        bool // Valid is true if TestPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TestPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestPriority), nil
}

type UserRole string

const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleQaLead     UserRole = "qa_lead"
	UserRoleQaEngineer UserRole = "qa_engineer"
	UserRoleViewer     UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AccountLock struct {
	Email       string
	LockedAt    time.Time
	LockedUntil time.Time
	Reason      string
}

type Analysis struct {
	ID             uuid.UUID
	RunResultID    uuid.UUID
	Reason         string
	RootCause      string
	SuggestedFix   string
	Evidence       json.RawMessage
	RelatedCommit  string
	StabilityScore *decimal.Decimal
	PromptVersion  string
	ModelName      string
	CreatedAt      time.Time
}

type AnalysisFeedback struct {
	AnalysisID    uuid.UUID
	UserID        uuid.UUID
	Helpful       bool
	Note          string
	PromptVersion string
	CreatedAt     time.Time
}

type Artifact struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Kind        string
	Filename    string
	StorageKey  string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	Version     int32
	LineageID   uuid.UUID
	UploadedBy  *uuid.UUID
	CreatedAt   time.Time
}

type AuditLog struct {
	ID         int64
	ActorID    *uuid.UUID
	ActorEmail string
	Action     string
	Subject    string
	ProjectID  *uuid.UUID
	Ip         *netip.Addr
	Detail     json.RawMessage
	At         time.Time
}

type CoverageFile struct {
	ID              int64
	CoverageRunID   uuid.UUID
	Path            string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
}

type CoverageRun struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	CommitSha       string
	Tool            string
	Command         string
	LinesTotal      int32
	LinesCovered    int32
	BranchesTotal   int32
	BranchesCovered int32
	Error           string
	JobID           *uuid.UUID
	CreatedAt       time.Time
}

type Defect struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	RunResultID   *uuid.UUID
	TestCaseID    *uuid.UUID
	RequirementID *uuid.UUID
	AnalysisID    *uuid.UUID
	Title         string
	Description   string
	Severity      DefectSeverity
	Status        DefectStatus
	AssigneeID    *uuid.UUID
	DuplicateOf   *uuid.UUID
	RootCauseKey  string
	ExternalRef   json.RawMessage
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ResolvedAt    *time.Time
	TestName      string
}

type DefectComment struct {
	ID        uuid.UUID
	DefectID  uuid.UUID
	AuthorID  *uuid.UUID
	Body      string
	System    bool
	CreatedAt time.Time
}

type Endpoint struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	ArtifactID  uuid.UUID
	Method      string
	Path        string
	OperationID string
	Summary     string
	Description string
	Parameters  json.RawMessage
	Request     json.RawMessage
	Responses   json.RawMessage
	Security    json.RawMessage
	SourceRef   string
	CreatedAt   time.Time
}

type Job struct {
	ID             uuid.UUID
	ProjectID      *uuid.UUID
	Type           string
	Status         JobStatus
	Progress       int16
	Attempts       int16
	MaxAttempts    int16
	Error          *string
	ParentJobID    *uuid.UUID
	Payload        json.RawMessage
	IdempotencyKey string
	CorrelationID  string
	EnqueuedBy     *uuid.UUID
	QueuedAt       time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
}

type JobEvent struct {
	ID      int64
	JobID   uuid.UUID
	Level   JobEventLevel
	Message string
	At      time.Time
}

type LlmCall struct {
	ID               int64
	ProviderID       *uuid.UUID
	ModelID          *uuid.UUID
	ProviderKind     string
	ModelName        string
	Tier             LlmTier
	Agent            string
	ProjectID        *uuid.UUID
	JobID            *uuid.UUID
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostUsd          decimal.Decimal
	LatencyMs        int32
	FallbackUsed     bool
	At               time.Time
}

type LlmModel struct {
	ID              uuid.UUID
	ProviderID      uuid.UUID
	ModelID         string
	DisplayName     string
	Tiers           []string
	Capabilities    json.RawMessage
	PriceInput      decimal.Decimal
	PriceOutput     decimal.Decimal
	PriceCacheRead  *decimal.Decimal
	PriceCacheWrite *decimal.Decimal
	MaxInputTokens  *int32
	MaxOutputTokens *int32
	IsEnabled       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type LlmProvider struct {
	ID              uuid.UUID
	Name            string
	Kind            LlmProviderKind
	Config          json.RawMessage
	Credentials     json.RawMessage
	DataResidency   LlmDataResidency
	IsEnabled       bool
	IsDefault       bool
	HealthStatus    LlmHealthStatus
	HealthCheckedAt *time.Time
	HealthDetail    string
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type LoginAttempt struct {
	ID          uuid.UUID
	Email       string
	Ip          *netip.Addr
	Succeeded   bool
	UserAgent   string
	AttemptedAt time.Time
}

type McpCall struct {
	ID         int64
	ServerID   *uuid.UUID
	ServerName string
	Tool       string
	Arguments  json.RawMessage
	Status     string
	Error      string
	Agent      string
	ProjectID  *uuid.UUID
	JobID      *uuid.UUID
	At         time.Time
}

type McpServer struct {
	ID              uuid.UUID
	Name            string
	Transport       McpTransport
	Command         string
	Args            []string
	Url             string
	Credentials     json.RawMessage
	Scope           McpScope
	ScopeID         *uuid.UUID
	EnabledTools    []string
	DiscoveredTools json.RawMessage
	AutoWrite       bool
	IsEnabled       bool
	HealthStatus    McpHealth
	HealthCheckedAt *time.Time
	HealthDetail    string
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MockServer struct {
	ProjectID   uuid.UUID
	ContainerID string
	Status      string
	Url         string
	HostPort    int32
	Routes      json.RawMessage
	Faults      json.RawMessage
	RouteCount  int32
	Image       string
	Error       string
	StartedBy   *uuid.UUID
	StartedAt   *time.Time
	StoppedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Title     string
	Body      string
	Link      string
	ReadAt    *time.Time
	CreatedAt time.Time
}

type Project struct {
	ID                 uuid.UUID
	Name               string
	Description        string
	OwnerID            uuid.UUID
	TestTypes          []string
	ExternalAiApproved bool
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ProjectMember struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      UserRole
	CreatedAt time.Time
}

type Quarantine struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	TestName     string
	TestCaseID   *uuid.UUID
	Reason       string
	FlakeCount   int32
	WindowRuns   int32
	Source       string
	OwnerID      *uuid.UUID
	ReleasedAt   *time.Time
	ReleasedBy   *uuid.UUID
	ReleaseNote  string
	LastFlakedAt *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RepoConnection struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Provider      RepoProvider
	RepoUrl       string
	DefaultBranch string
	CredentialRef string
	LastCommit    string
	LastFetchedAt *time.Time
	LastError     string
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Detected      json.RawMessage
	DetectedAt    *time.Time
}

type RepoMap struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	CommitSha string
	Stack     string
	Document  json.RawMessage
	Steps     int32
	CutShort  bool
	ModelName string
	JobID     *uuid.UUID
	CreatedAt time.Time
}

type Report struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Format      ReportFormat
	Status      ReportStatus
	WindowDays  int32
	StorageKey  string
	SizeBytes   int64
	Error       string
	JobID       *uuid.UUID
	RequestedBy *uuid.UUID
	CreatedAt   time.Time
	FinishedAt  *time.Time
}

type Requirement struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	ArtifactID  *uuid.UUID
	EndpointID  *uuid.UUID
	Kind        RequirementKind
	Title       string
	Body        string
	SourceRef   string
	Fingerprint []byte
	GeneratedBy string
	CreatedAt   time.Time
}

type RiskConfirmation struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Kind        string
	Host        string
	ConfirmedBy *uuid.UUID
	ConfirmedAt time.Time
}

type Run struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	JobID       *uuid.UUID
	TargetUrl   string
	Trigger     RunTrigger
	Status      RunStatus
	Framework   TestFramework
	Image       string
	Total       int32
	Passed      int32
	Failed      int32
	Flaky       int32
	Skipped     int32
	DurationMs  int32
	Error       string
	LogKey      string
	TriggeredBy *uuid.UUID
	StartedAt   *time.Time
	FinishedAt  *time.Time
	CreatedAt   time.Time
	Quarantined int32
	Kind        RunKind
	LoadProfile json.RawMessage
}

type RunCommand struct {
	ID            int64
	RunID         uuid.UUID
	Command       string
	ExitCode      *int32
	DurationMs    int32
	OutputExcerpt string
	At            time.Time
}

type RunLogLine struct {
	ID    int64
	RunID uuid.UUID
	Line  string
	At    time.Time
}

type RunMetric struct {
	RunID        uuid.UUID
	Requests     int64
	Throughput   float64
	ErrorRate    float64
	LatencyAvgMs float64
	LatencyP50Ms float64
	LatencyP90Ms float64
	LatencyP95Ms float64
	LatencyP99Ms float64
	LatencyMaxMs float64
	VirtualUsers int32
	DurationMs   int64
	CreatedAt    time.Time
}

type RunResult struct {
	ID             uuid.UUID
	RunID          uuid.UUID
	TestCaseID     *uuid.UUID
	TestFileID     *uuid.UUID
	Name           string
	Status         RunResultStatus
	DurationMs     int32
	Attempt        int32
	FailureMessage string
	LogKey         string
	ScreenshotKey  string
	VideoKey       string
	CreatedAt      time.Time
	TraceKey       string
	Quarantined    bool
}

type SecurityFinding struct {
	ID           uuid.UUID
	RunResultID  uuid.UUID
	RunID        uuid.UUID
	PayloadID    string
	Category     string
	Endpoint     string
	Parameter    string
	Severity     string
	Evidence     string
	Reproduction string
	CreatedAt    time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
	UserID *uuid.UUID
}

type Setting struct {
	ID        uuid.UUID
	Scope     SettingsScope
	ScopeID   *uuid.UUID
	Key       string
	Value     json.RawMessage
	IsSecret  bool
	UpdatedBy *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SettingsAudit struct {
	ID       uuid.UUID
	Scope    SettingsScope
	ScopeID  *uuid.UUID
	Key      string
	OldValue []byte
	NewValue []byte
	ActorID  *uuid.UUID
	At       time.Time
}

type TestCase struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	RequirementID *uuid.UUID
	Title         string
	Preconditions string
	Steps         json.RawMessage
	Expected      string
	Priority      TestPriority
	Category      TestCategory
	Status        TestCaseStatus
	Fingerprint   []byte
	SupersededBy  *uuid.UUID
	GeneratedBy   string
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Endpoint      string
}

type TestFile struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Framework      TestFramework
	Path           string
	Content        string
	TestCaseIds    []uuid.UUID
	GeneratedBy    string
	ValidatedAt    *time.Time
	ValidationNote string
	SizeBytes      int32
	GeneratedAt    time.Time
	UpdatedAt      time.Time
}

type TierAssignment struct {
	ID              uuid.UUID
	Scope           LlmScope
	ScopeID         *uuid.UUID
	Tier            LlmTier
	ModelID         uuid.UUID
	FallbackModelID *uuid.UUID
	Effort          *string
	UpdatedBy       *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UiFlow struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Target     string
	AuthMode   string
	Document   json.RawMessage
	PageCount  int32
	FlowCount  int32
	Steps      int32
	CutShort   bool
	Artifacts  json.RawMessage
	ReviewedAt *time.Time
	ReviewedBy *uuid.UUID
	ModelName  string
	JobID      *uuid.UUID
	CreatedAt  time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Role         UserRole
	PasswordHash *string
	Timezone     string
	DisabledAt   *time.Time
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserInvitation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
}
