// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, kind, title, body, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, kind, title, body, link, read_at, created_at
`

type CreateNotificationParams struct {
	UserID uuid.UUID
	Kind   string
	Title  string
	Body   string
	Link   string
}

// In-app notifications. The built-in Notifier, always available, zero
// configuration.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationsOlderThan = `-- name: DeleteNotificationsOlderThan :execrows
DELETE FROM notifications WHERE created_at < $1
`

func (q *Queries) DeleteNotificationsOlderThan(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, title, body, link, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
ORDER BY created_at DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly *bool
	Cursor     *time.Time
	PageSize   int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
