// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      UserRole
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const archiveProject = `-- name: ArchiveProject :execrows
UPDATE projects
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (name, description, owner_id, test_types)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, owner_id, test_types, external_ai_approved, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string
	Description string
	OwnerID     uuid.UUID
	TestTypes   []string
}

// Projects, membership, and artifacts.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.TestTypes,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.TestTypes,
		&i.ExternalAiApproved,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, owner_id, test_types, external_ai_approved, archived_at, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.TestTypes,
		&i.ExternalAiApproved,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT p.id AS project_id,
       p.owner_id,
       p.archived_at,
       m.role AS member_role
FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $2
WHERE p.id = $1
`

type GetProjectMembershipParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetProjectMembershipRow struct {
	ProjectID  uuid.UUID
	OwnerID    uuid.UUID
	ArchivedAt *time.Time
	MemberRole NullUserRole
}

// GetProjectMembership backs the RequireProjectMembership middleware. Ownership
// counts as membership so an owner never has to add themselves.
func (q *Queries) GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (GetProjectMembershipRow, error) {
	row := q.db.QueryRow(ctx, getProjectMembership, arg.ID, arg.UserID)
	var i GetProjectMembershipRow
	err := row.Scan(
		&i.ProjectID,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.MemberRole,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, name, description, owner_id, test_types, external_ai_approved, archived_at, created_at, updated_at
FROM projects
WHERE ($1::boolean OR archived_at IS NULL)
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type ListAllProjectsParams struct {
	IncludeArchived *bool
	Cursor          *time.Time
	PageSize        int32
}

func (q *Queries) ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listAllProjects, arg.IncludeArchived, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.TestTypes,
			&i.ExternalAiApproved,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.project_id, m.user_id, m.role, m.created_at, u.email, u.name
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY u.email
`

type ListProjectMembersRow struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      UserRole
	CreatedAt time.Time
	Email     string
	Name      string
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.description, p.owner_id, p.test_types, p.external_ai_approved,
       p.archived_at, p.created_at, p.updated_at
FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
WHERE (p.owner_id = $1 OR m.user_id IS NOT NULL)
  AND ($2::boolean OR p.archived_at IS NULL)
  AND ($3::timestamptz IS NULL OR p.created_at < $3::timestamptz)
ORDER BY p.created_at DESC
LIMIT $4
`

type ListProjectsForUserParams struct {
	UserID          uuid.UUID
	IncludeArchived *bool
	Cursor          *time.Time
	PageSize        int32
}

// ListProjectsForUser is the QA Engineer view: projects they own or are a member
// of. A QA Lead or Admin uses ListAllProjects instead, and that difference is a
// decision the service makes, not the query.
func (q *Queries) ListProjectsForUser(ctx context.Context, arg ListProjectsForUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser,
		arg.UserID,
		arg.IncludeArchived,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.TestTypes,
			&i.ExternalAiApproved,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setExternalAIApproved = `-- name: SetExternalAIApproved :execrows
UPDATE projects
SET external_ai_approved = $2, updated_at = now()
WHERE id = $1
`

type SetExternalAIApprovedParams struct {
	ID                 uuid.UUID
	ExternalAiApproved bool
}

// SetExternalAIApproved is admin-only and audited. Without the flag a project may
// only be assigned providers marked local (F-16.13).
func (q *Queries) SetExternalAIApproved(ctx context.Context, arg SetExternalAIApprovedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setExternalAIApproved, arg.ID, arg.ExternalAiApproved)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unarchiveProject = `-- name: UnarchiveProject :execrows
UPDATE projects
SET archived_at = NULL, updated_at = now()
WHERE id = $1 AND archived_at IS NOT NULL
`

func (q *Queries) UnarchiveProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unarchiveProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, test_types = $4, updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, description, owner_id, test_types, external_ai_approved, archived_at, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	TestTypes   []string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TestTypes,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.TestTypes,
		&i.ExternalAiApproved,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
