// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id uuid.UUID) (int64, error)
	// Quarantine (BE-7.6). A test that flakes more than the threshold stops failing the
	// run and appears on a list with an owner and an age.
	ActiveQuarantines(ctx context.Context, projectID uuid.UUID) ([]Quarantine, error)
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	AppendJobEvent(ctx context.Context, arg AppendJobEventParams) (JobEvent, error)
	// Live log lines (BE-4.11). Written in batches by the worker, read by the SSE
	// stream, deleted once the run's full log is safely in object storage.
	AppendRunLogLines(ctx context.Context, arg []AppendRunLogLinesParams) (int64, error)
	ArchiveProject(ctx context.Context, id uuid.UUID) (int64, error)
	AssignQuarantineOwner(ctx context.Context, arg AssignQuarantineOwnerParams) (Quarantine, error)
	CancelJob(ctx context.Context, id uuid.UUID) (int64, error)
	CancelRun(ctx context.Context, id uuid.UUID) (int64, error)
	ClearAccountLock(ctx context.Context, email string) (int64, error)
	// ClearDefaultProvider and SetDefaultProvider run in one transaction. The partial
	// unique index refuses two defaults, so the clear has to happen first.
	ClearDefaultProvider(ctx context.Context) error
	ClearRunLog(ctx context.Context, id uuid.UUID) error
	// ClearRunResultArtifacts forgets the keys after the objects are gone. In that order:
	// a stored file with no key wastes space, while a key with no file is a download that
	// fails, and only one of those is visible to a user.
	ClearRunResultArtifacts(ctx context.Context, id uuid.UUID) error
	// Confirmed hosts for the two dangerous test kinds (BE-9.5).
	ConfirmHost(ctx context.Context, arg ConfirmHostParams) (RiskConfirmation, error)
	// CountActiveRuns backs the concurrency limit's "waiting for a slot" message: the
	// semaphore is what enforces it, and this is what explains it (BE-4.10).
	CountActiveRuns(ctx context.Context) (int64, error)
	// CountActiveRunsForProject backs the per-project cap. Global concurrency is a
	// semaphore in the worker; this is the check that stops one project queueing ten
	// runs and starving every other project behind them (BE-4.10).
	CountActiveRunsForProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountAssignmentsUsingModel(ctx context.Context, modelID uuid.UUID) (int64, error)
	// CountAssignmentsUsingProvider is what makes deleting a referenced provider a
	// clear refusal rather than a cascade that silently unassigns a tier.
	CountAssignmentsUsingProvider(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountAuditEntriesByAction(ctx context.Context, at time.Time) ([]CountAuditEntriesByActionRow, error)
	CountCoveredRequirements(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountDefectsByStatus(ctx context.Context, projectID uuid.UUID) ([]CountDefectsByStatusRow, error)
	// CountEnabledProviders backs the setup status and the enqueue-time check: an AI
	// job with no configured provider is refused when the user presses submit, not
	// inside a worker twenty minutes later.
	CountEnabledProviders(ctx context.Context) (int64, error)
	CountEndpoints(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountJobsByStatus(ctx context.Context, projectID *uuid.UUID) ([]CountJobsByStatusRow, error)
	CountOpenDefects(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error)
	CountRecentFailedAttemptsByIP(ctx context.Context, arg CountRecentFailedAttemptsByIPParams) (int64, error)
	CountRequirements(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountRunResultsByStatus(ctx context.Context, runID uuid.UUID) ([]CountRunResultsByStatusRow, error)
	CountSessionsForUser(ctx context.Context, userID *uuid.UUID) (int64, error)
	CountTestCases(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountTestCasesByStatus(ctx context.Context, projectID uuid.UUID) ([]CountTestCasesByStatusRow, error)
	CountTestFiles(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountTestFilesByFramework(ctx context.Context, projectID uuid.UUID) ([]CountTestFilesByFrameworkRow, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	// CountUsers backs the first-run check: the setup endpoint is available only while
	// no user exists, then permanently 404.
	CountUsers(ctx context.Context) (int64, error)
	// CoverageTrend backs the "did it rise" question that gives measured coverage its
	// point: a number with no history is a number nobody acts on.
	CoverageTrend(ctx context.Context, arg CoverageTrendParams) ([]CoverageTrendRow, error)
	// Failure analyses and the feedback on them (BE-5.1, BE-5.8).
	//
	// The evidence column is written whole by Go, after every reference in it has been
	// checked against the artifact it points at: an analysis citing line 4,000 of a
	// 300-line log is rejected before it reaches this table (BE-5.3).
	CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error)
	// Artifacts: uploaded or connected inputs, versioned by content hash.
	// CreateArtifact relies on the unique index on (project_id, sha256): an identical
	// re-upload conflicts and the service returns the existing row with
	// deduplicated: true rather than re-running generation (FR-1.4).
	//
	// The id is supplied rather than generated here because the storage key contains
	// it, and the object is written before the row exists: a key built after the
	// insert would mean either a second statement to fill it in or a row that briefly
	// points nowhere.
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateCoverageFilesBulk(ctx context.Context, arg []CreateCoverageFilesBulkParams) (int64, error)
	// Code coverage (BE-6.6, BE-6.7).
	//
	// Percentages are computed on read from the stored totals. A stored percentage is a
	// number that can disagree with its own numerator after one bad migration, and the
	// whole value of this table is that it agrees with the tool that produced it.
	CreateCoverageRun(ctx context.Context, arg CreateCoverageRunParams) (CoverageRun, error)
	// The built-in defect tracker (BE-5.5).
	//
	// It ships before any external tracker exists, because bug tracking has to work on
	// an installation with no Jira and no GitHub. The external_ref column is where a
	// tracker somebody else owns gets recorded later; on a zero-integration install it
	// stays empty and nothing here changes.
	//
	// The filtered list is built with squirrel in the owning store rather than generated
	// here: five optional filters is thirty-two queries or one unindexable one
	// (backend-standards.md 9).
	CreateDefect(ctx context.Context, arg CreateDefectParams) (Defect, error)
	CreateDefectComment(ctx context.Context, arg CreateDefectCommentParams) (DefectComment, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (UserInvitation, error)
	CreateLLMModel(ctx context.Context, arg CreateLLMModelParams) (LlmModel, error)
	// The AI provider layer: providers, models, tier assignments, and the call log.
	//
	// Resolution for a tier is project assignment, then global assignment, then an
	// error. Never a silent code default: a zero value that quietly means "use
	// whatever" is the failure this whole design prevents (ai-architecture.md 3.2).
	CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error)
	// MCP servers and call audit (BE-10.1).
	CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error)
	// In-app notifications. The built-in Notifier, always available, zero
	// configuration.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Projects, membership, and artifacts.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Comprehension maps (BE-6.4). One row per exploration: a map describes a revision,
	// and last month's map is history rather than something to overwrite.
	CreateRepoMap(ctx context.Context, arg CreateRepoMapParams) (RepoMap, error)
	// Generated reports (BE-5.9).
	//
	// The row is written before the file, so a report whose generation failed is visible
	// and retryable rather than being a gap nobody notices.
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	// CreateRequirement conflicts on the fingerprint, so re-running extract on an
	// unchanged artifact writes nothing new and returns what was already there.
	CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error)
	// Runs, results, and the command log.
	//
	// The counts on the runs row are maintained when results are written, so the
	// dashboard reads one row rather than aggregating a result table that grows with
	// every execution.
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateRunResultsBulk(ctx context.Context, arg []CreateRunResultsBulkParams) (int64, error)
	// Security findings (BE-9.4). One per probe that succeeded, keyed to the run_result the
	// probe produced so the promote-to-defect path works unchanged.
	CreateSecurityFinding(ctx context.Context, arg CreateSecurityFindingParams) (SecurityFinding, error)
	// CreateTestCase is the single-row path, used by manual authoring and by the
	// dedupe pass. Bulk generation uses CopyFrom instead.
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	// CreateTestCasesBulk is the generation write path: 400 cases is one statement
	// rather than 400 round trips inside a transaction that is now long
	// (backend-standards.md 8).
	CreateTestCasesBulk(ctx context.Context, arg []CreateTestCasesBulkParams) (int64, error)
	// Discovered UI flow graphs (BE-7.2). One row per discovery: a graph describes an
	// application as it behaved at a moment, and last week's graph is history rather than
	// something to overwrite.
	CreateUIFlow(ctx context.Context, arg CreateUIFlowParams) (UiFlow, error)
	// Users, invitations, and login throttling.
	//
	// Explicit column lists everywhere. SELECT * is a review failure: an added column
	// must not silently change the API surface or pull a credential into memory.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// DefectForResult is the promotion guard: promoting the same failure twice returns
	// the defect that already exists (BE-5.6.3).
	DefectForResult(ctx context.Context, runResultID *uuid.UUID) (Defect, error)
	DeleteAnalysisFeedback(ctx context.Context, arg DeleteAnalysisFeedbackParams) error
	DeleteArtifact(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteEndpointsForArtifact(ctx context.Context, artifactID uuid.UUID) (int64, error)
	DeleteExpiredInvitations(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteLLMModel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteLLMProvider(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMCPServer(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteNotificationsOlderThan(ctx context.Context, createdAt time.Time) (int64, error)
	DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error)
	DeleteRepoConnection(ctx context.Context, projectID uuid.UUID) (int64, error)
	DeleteRunLogLines(ctx context.Context, runID uuid.UUID) error
	// DeleteRunResults makes the result write idempotent: a redelivered execute job
	// replaces its own results rather than doubling them (BE-4.9.5).
	DeleteRunResults(ctx context.Context, runID uuid.UUID) error
	DeleteSession(ctx context.Context, token string) (int64, error)
	// DeleteSessionsForUser is the immediate-revocation path: offboarding, disabling an
	// account, or a password change.
	DeleteSessionsForUser(ctx context.Context, userID *uuid.UUID) (int64, error)
	DeleteSetting(ctx context.Context, arg DeleteSettingParams) (int64, error)
	DeleteSettingsForScopeID(ctx context.Context, arg DeleteSettingsForScopeIDParams) (int64, error)
	DeleteStaleLoginAttempts(ctx context.Context, before time.Time) (int64, error)
	DeleteTestCase(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteTestFilesForFramework(ctx context.Context, arg DeleteTestFilesForFrameworkParams) (int64, error)
	DeleteTierAssignment(ctx context.Context, id uuid.UUID) (int64, error)
	// Jobs and job events.
	//
	// The jobs row is the durable record of what ran. Redis holds only in-flight
	// coordination.
	// EnqueueJob is idempotent by unique index on (type, idempotency_key). A retried
	// enqueue returns the existing row instead of creating a second one, which is what
	// makes NFR-4 structural rather than disciplined.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error)
	FailReport(ctx context.Context, arg FailReportParams) error
	// FailingResultsForRun is what the analyse chain iterates: every failure worth
	// explaining, flaky ones included, because "why is this flaky" is the question a
	// reviewer actually has.
	FailingResultsForRun(ctx context.Context, runID uuid.UUID) ([]RunResult, error)
	// FeedbackByPromptVersion is the point of storing the version: prompt iteration with
	// numbers rather than impressions (BE-5.8.2).
	FeedbackByPromptVersion(ctx context.Context) ([]FeedbackByPromptVersionRow, error)
	// FindArtifactLineage locates the previous versions of the same logical input, by
	// filename and kind within a project. This is what a re-upload of a changed spec
	// attaches itself to, and what phase 11 diffs against.
	FindArtifactLineage(ctx context.Context, arg FindArtifactLineageParams) (FindArtifactLineageRow, error)
	// Sessions.
	//
	// The first three columns are the shape alexedwards/scs expects. user_id is ours:
	// scs has no notion of an owner, and without it "revoke every session for this
	// user" would mean decoding every blob.
	FindSession(ctx context.Context, token string) (Session, error)
	// FindTestFilesForCase answers "where is this case implemented", which is the
	// traceability half of F-6.11.
	FindTestFilesForCase(ctx context.Context, arg FindTestFilesForCaseParams) ([]FindTestFilesForCaseRow, error)
	FinishReport(ctx context.Context, arg FinishReportParams) (Report, error)
	// FinishRun writes the outcome and the counts in one statement, so a dashboard can
	// never read a run that is finished but not yet counted.
	FinishRun(ctx context.Context, arg FinishRunParams) (Run, error)
	// FlakeCountsForProject is the arithmetic behind an automatic quarantine: how many of
	// the last N finished runs saw each test flake. Counted from the results rather than
	// from a stored score, because a score is a summary and this decision deserves the
	// underlying facts (BE-4.13).
	// A test flaked in a run when that run holds both a passing and a failing attempt of
	// it. Derived rather than read from a status column, because the results table stores
	// what each attempt did and `flaky` is a conclusion about a set of attempts: the run
	// row carries the tally, and the rows carry the facts it was computed from (BE-4.13.2).
	FlakeCountsForProject(ctx context.Context, arg FlakeCountsForProjectParams) ([]FlakeCountsForProjectRow, error)
	GetAccountLock(ctx context.Context, email string) (AccountLock, error)
	GetAnalysis(ctx context.Context, id uuid.UUID) (Analysis, error)
	GetAnalysisFeedback(ctx context.Context, arg GetAnalysisFeedbackParams) (AnalysisFeedback, error)
	GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetArtifactByHash(ctx context.Context, arg GetArtifactByHashParams) (Artifact, error)
	GetDefect(ctx context.Context, id uuid.UUID) (Defect, error)
	// GetInvitationByTokenHash looks up by hash, never by the token itself: a leaked
	// database must not yield working invitation links.
	GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (UserInvitation, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetLLMModel(ctx context.Context, id uuid.UUID) (LlmModel, error)
	GetLLMProvider(ctx context.Context, id uuid.UUID) (LlmProvider, error)
	GetMCPServer(ctx context.Context, id uuid.UUID) (McpServer, error)
	GetMockServer(ctx context.Context, projectID uuid.UUID) (MockServer, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	// GetProjectMembership backs the RequireProjectMembership middleware. Ownership
	// counts as membership so an owner never has to add themselves.
	GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (GetProjectMembershipRow, error)
	GetQuarantine(ctx context.Context, id uuid.UUID) (Quarantine, error)
	GetRepoConnection(ctx context.Context, projectID uuid.UUID) (RepoConnection, error)
	GetReport(ctx context.Context, id uuid.UUID) (Report, error)
	GetRequirement(ctx context.Context, id uuid.UUID) (Requirement, error)
	GetRun(ctx context.Context, id uuid.UUID) (Run, error)
	GetRunMetrics(ctx context.Context, runID uuid.UUID) (RunMetric, error)
	GetRunResult(ctx context.Context, id uuid.UUID) (RunResult, error)
	GetSecurityFinding(ctx context.Context, id uuid.UUID) (SecurityFinding, error)
	// Settings and the settings audit trail.
	//
	// Resolution is user -> project -> global -> registry default, and it happens in
	// one place in Go. These queries fetch the candidate rows; they do not decide.
	GetSetting(ctx context.Context, arg GetSettingParams) (Setting, error)
	GetTestCase(ctx context.Context, id uuid.UUID) (TestCase, error)
	GetTestFile(ctx context.Context, id uuid.UUID) (TestFile, error)
	GetUIFlow(ctx context.Context, id uuid.UUID) (UiFlow, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HostConfirmed(ctx context.Context, arg HostConfirmedParams) (bool, error)
	// LatestAnalysisForResult is what the UI shows: a re-analysis after a prompt change
	// is a new row, and the newest one wins.
	LatestAnalysisForResult(ctx context.Context, runResultID uuid.UUID) (Analysis, error)
	LatestCoverageRun(ctx context.Context, projectID uuid.UUID) (CoverageRun, error)
	LatestRepoMap(ctx context.Context, projectID uuid.UUID) (RepoMap, error)
	// LatestSourceArchive is what an archive-backed sync expands. The newest upload of
	// the kind, because a project that re-uploaded its source meant the new one.
	LatestSourceArchive(ctx context.Context, projectID uuid.UUID) (LatestSourceArchiveRow, error)
	LatestUIFlow(ctx context.Context, projectID uuid.UUID) (UiFlow, error)
	// LinkDuplicate is reversible: passing null unlinks, because the platform proposes
	// and a person decides (BE-5.7.3).
	LinkDuplicate(ctx context.Context, arg LinkDuplicateParams) (Defect, error)
	ListAllMCPServers(ctx context.Context) ([]McpServer, error)
	ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]Project, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListAnalysesForRun(ctx context.Context, runID uuid.UUID) ([]Analysis, error)
	// ListApprovedTestCases feeds code generation: approved cases only, because
	// generating from a draft somebody is still editing wastes the call (BE-3.2).
	ListApprovedTestCases(ctx context.Context, projectID uuid.UUID) ([]ListApprovedTestCasesRow, error)
	ListArtifactVersions(ctx context.Context, lineageID uuid.UUID) ([]Artifact, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error)
	// ListArtifactsOlderThan drives the retention job. Retention is a setting in days
	// (F-17.5).
	ListArtifactsOlderThan(ctx context.Context, arg ListArtifactsOlderThanParams) ([]ListArtifactsOlderThanRow, error)
	// ListAuditEntries is deliberately narrow. The filtered admin view is a dynamic
	// query built with squirrel inside the store, because four optional filters would
	// otherwise mean sixteen generated queries.
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error)
	// ListChainEventsSince is the same, widened to a chain.
	//
	// Handlers write their log lines against the stage that is running, so a viewer
	// watching the submission would otherwise see an empty log while three stages
	// narrated themselves. Asking for a stage still returns only that stage's lines,
	// because a stage has no children.
	ListChainEventsSince(ctx context.Context, arg ListChainEventsSinceParams) ([]JobEvent, error)
	ListChildJobs(ctx context.Context, parentJobID *uuid.UUID) ([]Job, error)
	ListConfirmedHosts(ctx context.Context, arg ListConfirmedHostsParams) ([]RiskConfirmation, error)
	// ListCoverageFiles is the per-file detail, least covered first: the only order
	// anybody reads it in.
	ListCoverageFiles(ctx context.Context, arg ListCoverageFilesParams) ([]ListCoverageFilesRow, error)
	ListDefectComments(ctx context.Context, arg ListDefectCommentsParams) ([]DefectComment, error)
	// ListDuplicatesOf is how one defect shows its recurrences: three runs failing the
	// same way is one defect with three linked occurrences (BE-5.7).
	ListDuplicatesOf(ctx context.Context, duplicateOf *uuid.UUID) ([]Defect, error)
	ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error)
	// ListJobEventsSince backs the SSE stream. The bigserial id doubles as the
	// Last-Event-ID cursor, so a reconnect resumes without gaps or duplicates.
	ListJobEventsSince(ctx context.Context, arg ListJobEventsSinceParams) ([]JobEvent, error)
	ListJobsForProject(ctx context.Context, arg ListJobsForProjectParams) ([]Job, error)
	ListLLMCalls(ctx context.Context, arg ListLLMCallsParams) ([]LlmCall, error)
	ListLLMModels(ctx context.Context, providerID *uuid.UUID) ([]LlmModel, error)
	ListLLMProviders(ctx context.Context) ([]LlmProvider, error)
	ListMCPCalls(ctx context.Context, arg ListMCPCallsParams) ([]McpCall, error)
	// ListMCPServersForScope is what an agent's tool loader reads: the enabled servers a
	// project may use, which is the global ones plus that project's own. The per-project
	// boundary is here — another project's servers are never returned.
	ListMCPServersForScope(ctx context.Context, scopeID *uuid.UUID) ([]McpServer, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	// ListProjectsForUser is the QA Engineer view: projects they own or are a member
	// of. A QA Lead or Admin uses ListAllProjects instead, and that difference is a
	// decision the service makes, not the query.
	ListProjectsForUser(ctx context.Context, arg ListProjectsForUserParams) ([]Project, error)
	ListQuarantines(ctx context.Context, arg ListQuarantinesParams) ([]Quarantine, error)
	ListRepoMaps(ctx context.Context, arg ListRepoMapsParams) ([]ListRepoMapsRow, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
	ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]Requirement, error)
	// Run artifact retention (BE-7.5.3). A video, a trace, and a screenshot are the
	// largest things this platform stores, and they are stored per failing attempt: an
	// installation that never expires them fills a disk with evidence about tests nobody
	// is still investigating.
	//
	// The cutoff is the run's finish time rather than the result's creation, because a run
	// and its evidence expire together: half a run's artifacts is worse than none.
	ListRunArtifactsOlderThan(ctx context.Context, arg ListRunArtifactsOlderThanParams) ([]ListRunArtifactsOlderThanRow, error)
	ListRunCommands(ctx context.Context, runID uuid.UUID) ([]RunCommand, error)
	ListRunLogLinesSince(ctx context.Context, arg ListRunLogLinesSinceParams) ([]RunLogLine, error)
	ListRunLogsOlderThan(ctx context.Context, arg ListRunLogsOlderThanParams) ([]ListRunLogsOlderThanRow, error)
	ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]RunResult, error)
	// ListRunningMocks is what a sweeper reconciles against the host: a row that says
	// running with no container behind it is a row a UI is lying with.
	ListRunningMocks(ctx context.Context) ([]MockServer, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error)
	ListSecurityFindings(ctx context.Context, runID uuid.UUID) ([]SecurityFinding, error)
	ListSettingChanges(ctx context.Context, arg ListSettingChangesParams) ([]SettingsAudit, error)
	ListSettingsByScope(ctx context.Context, arg ListSettingsByScopeParams) ([]Setting, error)
	// ListStaleRuns finds runs a crashed worker left behind, so the sweeper can mark
	// them errored rather than leaving them running forever (BE-4.2).
	ListStaleRuns(ctx context.Context, arg ListStaleRunsParams) ([]ListStaleRunsRow, error)
	// ListTestCasesByFingerprint is how the generation pass learns what it already
	// has before writing, so an unchanged spec produces zero new rows.
	ListTestCasesByFingerprint(ctx context.Context, arg ListTestCasesByFingerprintParams) ([]ListTestCasesByFingerprintRow, error)
	// ListTestCasesForRequirement is the narrow candidate set the AI dedupe pass
	// compares against, which is what keeps that cost bounded (F-5.4).
	ListTestCasesForRequirement(ctx context.Context, requirementID *uuid.UUID) ([]TestCase, error)
	// ListTestFiles is the tree query. Content is excluded on purpose: it is the one
	// column that makes this expensive, and a file browser does not need it.
	ListTestFiles(ctx context.Context, arg ListTestFilesParams) ([]ListTestFilesRow, error)
	// ListTestFilesForExport streams the whole suite, content included. Ordered by
	// path so the zip is deterministic: two exports of the same suite produce the
	// same archive.
	ListTestFilesForExport(ctx context.Context, arg ListTestFilesForExportParams) ([]TestFile, error)
	ListTierAssignments(ctx context.Context, projectID *uuid.UUID) ([]TierAssignment, error)
	// ListUIFlows is the history. The document is left out: a list screen shows the
	// counts and the date, and shipping forty graphs to render ten rows is a page nobody
	// waits for.
	ListUIFlows(ctx context.Context, arg ListUIFlowsParams) ([]ListUIFlowsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// ListUsersByRole backs admin fan-out: a degraded integration raises an alert for
	// every admin, and a disabled account is not somebody who will read it.
	ListUsersByRole(ctx context.Context, role UserRole) ([]User, error)
	LockAccount(ctx context.Context, arg LockAccountParams) error
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error)
	// MarkChainRunning moves a parent row out of queued when its first stage starts.
	//
	// Deliberately not MarkJobRunning: that counts an attempt, and a parent is not
	// attempted. A three-stage chain would otherwise report three attempts on a
	// submission that never failed once.
	MarkChainRunning(ctx context.Context, id uuid.UUID) (int64, error)
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (int64, error)
	MarkJobQueuedForRetry(ctx context.Context, arg MarkJobQueuedForRetryParams) (int64, error)
	MarkJobRunning(ctx context.Context, id uuid.UUID) (int64, error)
	MarkJobSucceeded(ctx context.Context, id uuid.UUID) (int64, error)
	// MarkMockStopped records that the container is gone, keeping the routes so a restart
	// serves the same mock.
	MarkMockStopped(ctx context.Context, arg MarkMockStoppedParams) (MockServer, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	MarkReportRunning(ctx context.Context, id uuid.UUID) (int64, error)
	// MarkRunFailed is the sweeper's write: a run whose worker died is errored with a
	// stated reason rather than left running forever.
	MarkRunFailed(ctx context.Context, arg MarkRunFailedParams) (int64, error)
	MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) (int64, error)
	// MarkUIFlowReviewed records that a person has read the graph, so generating from an
	// unreviewed one is a visible choice rather than an invisible default (BE-7.2.3).
	MarkUIFlowReviewed(ctx context.Context, arg MarkUIFlowReviewedParams) (UiFlow, error)
	// OpenDefectWithRootCause is duplicate detection, and it is a lookup rather than a
	// model call: the same test case with the same normalised root cause is the same
	// defect (BE-5.7.2). Closed defects are excluded, because a failure recurring after
	// a fix is a regression and deserves its own row.
	OpenDefectWithRootCause(ctx context.Context, arg OpenDefectWithRootCauseParams) (Defect, error)
	// OpenDefectWithRootCauseByName is the fallback when a result could not be mapped to
	// exactly one test case. The test's name plus the normalised root cause is still
	// "this test, failing this way" (BE-5.7.2).
	OpenDefectWithRootCauseByName(ctx context.Context, arg OpenDefectWithRootCauseByNameParams) (Defect, error)
	// ProjectDashboard is the counts panel (F-12.1) as one query rather than five.
	//
	// Every subquery qualifies its own table: without the alias the planner and the
	// generator both have to guess which project_id is meant, and one of them guesses
	// differently.
	ProjectDashboard(ctx context.Context, projectID uuid.UUID) (ProjectDashboardRow, error)
	// QuarantineTest is idempotent on the live row: a second run that finds the same test
	// still flaking updates the arithmetic and the last-flaked time rather than creating a
	// second quarantine for the same test.
	QuarantineTest(ctx context.Context, arg QuarantineTestParams) (Quarantine, error)
	// The audit log. Every privileged action, and nothing that holds a secret.
	RecordAuditEntry(ctx context.Context, arg RecordAuditEntryParams) error
	// RecordLLMCall is written by Go and only by Go. Python returns usage and
	// persists nothing (backend-standards.md 10).
	RecordLLMCall(ctx context.Context, arg RecordLLMCallParams) (LlmCall, error)
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RecordMCPCall(ctx context.Context, arg RecordMCPCallParams) error
	RecordMCPHealth(ctx context.Context, arg RecordMCPHealthParams) error
	// RecordRepoDetection stores the detected stack and the files it was read from.
	RecordRepoDetection(ctx context.Context, arg RecordRepoDetectionParams) error
	// RecordRepoFetch stores what a clone actually got. The commit rather than the
	// branch, because a branch moves and a map of a repository has to say which
	// revision it describes.
	RecordRepoFetch(ctx context.Context, arg RecordRepoFetchParams) error
	RecordRepoFetchError(ctx context.Context, arg RecordRepoFetchErrorParams) error
	RecordRunCommand(ctx context.Context, arg RecordRunCommandParams) error
	// The audit row is written in the same transaction as the settings write. For a
	// secret both values arrive as '[redacted]': only the fact of the change is kept.
	RecordSettingChange(ctx context.Context, arg RecordSettingChangeParams) error
	ReleaseQuarantine(ctx context.Context, arg ReleaseQuarantineParams) (Quarantine, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error)
	// ReportDefects lists the defects with how many times the same failure recurred.
	// Duplicates are counted rather than listed: three occurrences of one bug is one row
	// saying three.
	ReportDefects(ctx context.Context, arg ReportDefectsParams) ([]ReportDefectsRow, error)
	// The report's own reads (BE-5.9.2). They live here rather than being assembled from
	// four services, because one document's definition split across four packages is a
	// document whose sections drift apart.
	// ReportFailures is every failure in the window with its newest analysis, if it has
	// one, and the defect it was promoted to, if it was. A left join in both cases: a
	// report that hid unexplained failures would look better than the project is.
	// One row per test, preferring the newest occurrence that has an explanation. The
	// alternative is showing "not analysed" for a failure the platform did explain, just
	// on an earlier run of the same test, which reads as a gap in the analysis rather
	// than what it is.
	ReportFailures(ctx context.Context, arg ReportFailuresParams) ([]ReportFailuresRow, error)
	// RequirementCoverage answers "which requirements have test cases" as one indexed
	// query, which is what BE-2.1 exists to make possible. Passing coverage arrives
	// with runs in phase 4; this is the generation half (FR-7.2 keeps the two numbers
	// separate).
	RequirementCoverage(ctx context.Context, projectID uuid.UUID) ([]RequirementCoverageRow, error)
	// ResolveSetting returns every stored row that could satisfy one key for one
	// caller, ordered strongest scope first. Go takes the first and falls through to
	// the registry default when there is none, so a missing row is never a zero value.
	ResolveSetting(ctx context.Context, arg ResolveSettingParams) ([]Setting, error)
	// ResolveSettingsForScope warms the whole cache in one round trip rather than one
	// query per key.
	ResolveSettingsForScope(ctx context.Context, arg ResolveSettingsForScopeParams) ([]Setting, error)
	// ResolveTier is the whole resolution rule in one query: project first, then
	// global, ordered so the caller takes the first row and never sorts it itself.
	ResolveTier(ctx context.Context, arg ResolveTierParams) ([]TierAssignment, error)
	// ResultAttempts backs the stability score's first permitted signal: how a test
	// behaved across the attempts of one run (BE-5.4.1).
	ResultAttempts(ctx context.Context, arg ResultAttemptsParams) ([]ResultAttemptsRow, error)
	// ResultHistoryByName is the second stability input: how this test has behaved over
	// recent runs of the same project. By name rather than by test case, because a
	// result the platform could not map to exactly one case still has a history.
	ResultHistoryByName(ctx context.Context, arg ResultHistoryByNameParams) ([]ResultHistoryByNameRow, error)
	// ResultHistoryForCase backs the stability score and the flake view: the same case
	// across runs, newest first.
	ResultHistoryForCase(ctx context.Context, arg ResultHistoryForCaseParams) ([]ResultHistoryForCaseRow, error)
	// RunTrend is the dashboard's trend panel: one row per run, oldest first, so a
	// chart plots it without reversing.
	RunTrend(ctx context.Context, arg RunTrendParams) ([]RunTrendRow, error)
	SetDefaultProvider(ctx context.Context, id uuid.UUID) error
	SetDefectExternalRef(ctx context.Context, arg SetDefectExternalRefParams) error
	// SetExternalAIApproved is admin-only and audited. Without the flag a project may
	// only be assigned providers marked local (F-16.13).
	SetExternalAIApproved(ctx context.Context, arg SetExternalAIApprovedParams) (int64, error)
	SetJobProgress(ctx context.Context, arg SetJobProgressParams) (int64, error)
	// SetLLMModelCapabilities is written by the probe. Detected capability overwrites
	// declared capability, because a declaration is a claim and a probe is a
	// measurement (F-16.5).
	SetLLMModelCapabilities(ctx context.Context, arg SetLLMModelCapabilitiesParams) error
	// SetLLMProviderCredentials is separate from the rest of the update, because a
	// form submitted without the secret field must not blank the stored one: a secret
	// is replaced deliberately or left alone (F-1.8).
	SetLLMProviderCredentials(ctx context.Context, arg SetLLMProviderCredentialsParams) error
	SetLLMProviderHealth(ctx context.Context, arg SetLLMProviderHealthParams) error
	SetMCPCredentials(ctx context.Context, arg SetMCPCredentialsParams) error
	// SetSessionUser runs immediately after authentication, because scs writes the
	// row before anyone knows who is signing in.
	SetSessionUser(ctx context.Context, arg SetSessionUserParams) (int64, error)
	// SetStabilityScore is written after the analysis, because the score comes from
	// re-run history and commit overlap rather than from the agent (BE-5.4).
	SetStabilityScore(ctx context.Context, arg SetStabilityScoreParams) error
	// SetTestCaseStatus backs bulk approve and reject. The batch is capped by the
	// service and runs in one transaction.
	SetTestCaseStatus(ctx context.Context, arg SetTestCaseStatusParams) (int64, error)
	SetTestFileValidation(ctx context.Context, arg SetTestFileValidationParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	SpendByAgent(ctx context.Context, arg SpendByAgentParams) ([]SpendByAgentRow, error)
	SpendByProject(ctx context.Context, arg SpendByProjectParams) ([]SpendByProjectRow, error)
	// SpendByProvider, SpendByProject, and SpendByAgent back the dashboard. Genuine
	// SQL aggregates, generated like any other query, so the numbers reconcile exactly
	// against a direct SUM over llm_calls (BE-1.14).
	SpendByProvider(ctx context.Context, arg SpendByProviderParams) ([]SpendByProviderRow, error)
	// SpendSince is the ceiling check, evaluated before a call rather than after
	// (F-16.10). A mixed setup may have one cheap local provider and one metered one,
	// so it is available per provider and in total.
	SpendSince(ctx context.Context, arg SpendSinceParams) (decimal.Decimal, error)
	SpendTotal(ctx context.Context, arg SpendTotalParams) (SpendTotalRow, error)
	// Performance metrics (BE-9.1). One row per run: a run has one summary, and a
	// percentile is the summary rather than a sample of one.
	StoreRunMetrics(ctx context.Context, arg StoreRunMetricsParams) error
	// SupersedeTestCase records a merge rather than deleting the loser, so "why is
	// this case gone" has an answer.
	SupersedeTestCase(ctx context.Context, arg SupersedeTestCaseParams) (int64, error)
	// TouchDefect keeps updated_at meaningful when the change was a comment rather than
	// a field: a thread that moved is a defect that moved.
	TouchDefect(ctx context.Context, id uuid.UUID) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UnarchiveProject(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateDefect(ctx context.Context, arg UpdateDefectParams) (Defect, error)
	UpdateLLMModel(ctx context.Context, arg UpdateLLMModelParams) (LlmModel, error)
	UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (LlmProvider, error)
	UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertAnalysisFeedback(ctx context.Context, arg UpsertAnalysisFeedbackParams) error
	// Ingest and generation: endpoints, requirements, and test cases.
	//
	// Two ideas run through this file. Re-running work is free, because the unique
	// indexes turn a repeat into a conflict rather than a duplicate. And bulk writes
	// are one statement: 400 test cases is a CopyFrom, not 400 round trips inside a
	// transaction that is now long (backend-standards.md 8).
	// UpsertEndpoint makes re-parsing an artifact idempotent. A changed spec updates
	// the row it already had rather than leaving two versions of one endpoint.
	UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (Endpoint, error)
	// UpsertGlobalSetting exists separately because two NULL scope_ids are distinct to
	// a plain unique index, so global rows are constrained by their own partial index
	// and need their own ON CONFLICT target.
	UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (Setting, error)
	// UpsertTierAssignment writes the global row. Global and project need separate
	// statements because their uniqueness is enforced by two partial indexes: a NULL
	// scope_id is not equal to itself, so one ON CONFLICT target cannot cover both.
	UpsertGlobalTierAssignment(ctx context.Context, arg UpsertGlobalTierAssignmentParams) (TierAssignment, error)
	// Mock servers (BE-8.6). One row per project: a project has one mock, and restarting
	// replaces its container rather than adding a row.
	UpsertMockServer(ctx context.Context, arg UpsertMockServerParams) (MockServer, error)
	UpsertProjectTierAssignment(ctx context.Context, arg UpsertProjectTierAssignmentParams) (TierAssignment, error)
	// Repository connections (BE-6.1).
	//
	// The token is never here: `credential_ref` names a settings key, and the settings
	// store owns encryption and rotation for every secret in the platform.
	UpsertRepoConnection(ctx context.Context, arg UpsertRepoConnectionParams) (RepoConnection, error)
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
	// UpsertSetting is the only write path. The unique indexes make it idempotent, so
	// a retried job cannot produce a second row for the same key.
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
	// Generated test files.
	//
	// Regeneration replaces a file at the same path rather than accumulating copies,
	// and every read of a file's content is deliberate: the browsing endpoint returns
	// the tree without it, because a 300-file suite is not something to load whole
	// to draw a sidebar (BE-3.5).
	UpsertTestFile(ctx context.Context, arg UpsertTestFileParams) (TestFile, error)
}

var _ Querier = (*Queries)(nil)
