// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRepoMap = `-- name: CreateRepoMap :one

INSERT INTO repo_maps (project_id, commit_sha, stack, document, steps, cut_short, model_name, job_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, commit_sha, stack, document, steps, cut_short, model_name,
          job_id, created_at
`

type CreateRepoMapParams struct {
	ProjectID uuid.UUID
	CommitSha string
	Stack     string
	Document  json.RawMessage
	Steps     int32
	CutShort  bool
	ModelName string
	JobID     *uuid.UUID
}

// Comprehension maps (BE-6.4). One row per exploration: a map describes a revision,
// and last month's map is history rather than something to overwrite.
func (q *Queries) CreateRepoMap(ctx context.Context, arg CreateRepoMapParams) (RepoMap, error) {
	row := q.db.QueryRow(ctx, createRepoMap,
		arg.ProjectID,
		arg.CommitSha,
		arg.Stack,
		arg.Document,
		arg.Steps,
		arg.CutShort,
		arg.ModelName,
		arg.JobID,
	)
	var i RepoMap
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.Stack,
		&i.Document,
		&i.Steps,
		&i.CutShort,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepoConnection = `-- name: DeleteRepoConnection :execrows
DELETE FROM repo_connections WHERE project_id = $1
`

func (q *Queries) DeleteRepoConnection(ctx context.Context, projectID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepoConnection, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRepoConnection = `-- name: GetRepoConnection :one
SELECT id, project_id, provider, repo_url, default_branch, credential_ref,
       last_commit, last_fetched_at, last_error, created_by, created_at, updated_at,
       detected, detected_at
FROM repo_connections
WHERE project_id = $1
`

func (q *Queries) GetRepoConnection(ctx context.Context, projectID uuid.UUID) (RepoConnection, error) {
	row := q.db.QueryRow(ctx, getRepoConnection, projectID)
	var i RepoConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.CredentialRef,
		&i.LastCommit,
		&i.LastFetchedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Detected,
		&i.DetectedAt,
	)
	return i, err
}

const latestRepoMap = `-- name: LatestRepoMap :one
SELECT id, project_id, commit_sha, stack, document, steps, cut_short, model_name,
       job_id, created_at
FROM repo_maps
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestRepoMap(ctx context.Context, projectID uuid.UUID) (RepoMap, error) {
	row := q.db.QueryRow(ctx, latestRepoMap, projectID)
	var i RepoMap
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitSha,
		&i.Stack,
		&i.Document,
		&i.Steps,
		&i.CutShort,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const latestSourceArchive = `-- name: LatestSourceArchive :one
SELECT id, filename, storage_key
FROM artifacts
WHERE project_id = $1 AND kind = 'source_archive'
ORDER BY created_at DESC
LIMIT 1
`

type LatestSourceArchiveRow struct {
	ID         uuid.UUID
	Filename   string
	StorageKey string
}

// LatestSourceArchive is what an archive-backed sync expands. The newest upload of
// the kind, because a project that re-uploaded its source meant the new one.
func (q *Queries) LatestSourceArchive(ctx context.Context, projectID uuid.UUID) (LatestSourceArchiveRow, error) {
	row := q.db.QueryRow(ctx, latestSourceArchive, projectID)
	var i LatestSourceArchiveRow
	err := row.Scan(&i.ID, &i.Filename, &i.StorageKey)
	return i, err
}

const listRepoMaps = `-- name: ListRepoMaps :many
SELECT id, project_id, commit_sha, stack, steps, cut_short, model_name, created_at
FROM repo_maps
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRepoMapsParams struct {
	ProjectID uuid.UUID
	PageSize  int32
}

type ListRepoMapsRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	CommitSha string
	Stack     string
	Steps     int32
	CutShort  bool
	ModelName string
	CreatedAt time.Time
}

func (q *Queries) ListRepoMaps(ctx context.Context, arg ListRepoMapsParams) ([]ListRepoMapsRow, error) {
	rows, err := q.db.Query(ctx, listRepoMaps, arg.ProjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoMapsRow{}
	for rows.Next() {
		var i ListRepoMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitSha,
			&i.Stack,
			&i.Steps,
			&i.CutShort,
			&i.ModelName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRepoDetection = `-- name: RecordRepoDetection :exec
UPDATE repo_connections
SET detected = $2, detected_at = now()
WHERE project_id = $1
`

type RecordRepoDetectionParams struct {
	ProjectID uuid.UUID
	Detected  json.RawMessage
}

// RecordRepoDetection stores the detected stack and the files it was read from.
func (q *Queries) RecordRepoDetection(ctx context.Context, arg RecordRepoDetectionParams) error {
	_, err := q.db.Exec(ctx, recordRepoDetection, arg.ProjectID, arg.Detected)
	return err
}

const recordRepoFetch = `-- name: RecordRepoFetch :exec
UPDATE repo_connections
SET last_commit = $2, last_fetched_at = now(), last_error = ''
WHERE project_id = $1
`

type RecordRepoFetchParams struct {
	ProjectID  uuid.UUID
	LastCommit string
}

// RecordRepoFetch stores what a clone actually got. The commit rather than the
// branch, because a branch moves and a map of a repository has to say which
// revision it describes.
func (q *Queries) RecordRepoFetch(ctx context.Context, arg RecordRepoFetchParams) error {
	_, err := q.db.Exec(ctx, recordRepoFetch, arg.ProjectID, arg.LastCommit)
	return err
}

const recordRepoFetchError = `-- name: RecordRepoFetchError :exec
UPDATE repo_connections
SET last_error = $2, last_fetched_at = now()
WHERE project_id = $1
`

type RecordRepoFetchErrorParams struct {
	ProjectID uuid.UUID
	LastError string
}

func (q *Queries) RecordRepoFetchError(ctx context.Context, arg RecordRepoFetchErrorParams) error {
	_, err := q.db.Exec(ctx, recordRepoFetchError, arg.ProjectID, arg.LastError)
	return err
}

const upsertRepoConnection = `-- name: UpsertRepoConnection :one

INSERT INTO repo_connections (
    project_id, provider, repo_url, default_branch, credential_ref, created_by
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id) DO UPDATE
SET provider = EXCLUDED.provider,
    repo_url = EXCLUDED.repo_url,
    default_branch = EXCLUDED.default_branch,
    credential_ref = EXCLUDED.credential_ref,
    updated_at = now()
RETURNING id, project_id, provider, repo_url, default_branch, credential_ref,
          last_commit, last_fetched_at, last_error, created_by, created_at, updated_at,
          detected, detected_at
`

type UpsertRepoConnectionParams struct {
	ProjectID     uuid.UUID
	Provider      RepoProvider
	RepoUrl       string
	DefaultBranch string
	CredentialRef string
	CreatedBy     *uuid.UUID
}

// Repository connections (BE-6.1).
//
// The token is never here: `credential_ref` names a settings key, and the settings
// store owns encryption and rotation for every secret in the platform.
func (q *Queries) UpsertRepoConnection(ctx context.Context, arg UpsertRepoConnectionParams) (RepoConnection, error) {
	row := q.db.QueryRow(ctx, upsertRepoConnection,
		arg.ProjectID,
		arg.Provider,
		arg.RepoUrl,
		arg.DefaultBranch,
		arg.CredentialRef,
		arg.CreatedBy,
	)
	var i RepoConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.CredentialRef,
		&i.LastCommit,
		&i.LastFetchedAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Detected,
		&i.DetectedAt,
	)
	return i, err
}
