// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countOpenDefects = `-- name: CountOpenDefects :one
SELECT count(*)::bigint FROM defects
WHERE project_id = $1 AND status IN ('open', 'acknowledged', 'in_progress')
`

func (q *Queries) CountOpenDefects(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDefects, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReport = `-- name: CreateReport :one

INSERT INTO reports (project_id, format, window_days, job_id, requested_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, format, status, window_days, storage_key, size_bytes,
          error, job_id, requested_by, created_at, finished_at
`

type CreateReportParams struct {
	ProjectID   uuid.UUID
	Format      ReportFormat
	WindowDays  int32
	JobID       *uuid.UUID
	RequestedBy *uuid.UUID
}

// Generated reports (BE-5.9).
//
// The row is written before the file, so a report whose generation failed is visible
// and retryable rather than being a gap nobody notices.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ProjectID,
		arg.Format,
		arg.WindowDays,
		arg.JobID,
		arg.RequestedBy,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Format,
		&i.Status,
		&i.WindowDays,
		&i.StorageKey,
		&i.SizeBytes,
		&i.Error,
		&i.JobID,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failReport = `-- name: FailReport :exec
UPDATE reports
SET status = 'failed', error = $2, finished_at = now()
WHERE id = $1
`

type FailReportParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) FailReport(ctx context.Context, arg FailReportParams) error {
	_, err := q.db.Exec(ctx, failReport, arg.ID, arg.Error)
	return err
}

const finishReport = `-- name: FinishReport :one
UPDATE reports
SET status = 'ready', storage_key = $2, size_bytes = $3, finished_at = now()
WHERE id = $1
RETURNING id, project_id, format, status, window_days, storage_key, size_bytes,
          error, job_id, requested_by, created_at, finished_at
`

type FinishReportParams struct {
	ID         uuid.UUID
	StorageKey string
	SizeBytes  int64
}

func (q *Queries) FinishReport(ctx context.Context, arg FinishReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, finishReport, arg.ID, arg.StorageKey, arg.SizeBytes)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Format,
		&i.Status,
		&i.WindowDays,
		&i.StorageKey,
		&i.SizeBytes,
		&i.Error,
		&i.JobID,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, project_id, format, status, window_days, storage_key, size_bytes,
       error, job_id, requested_by, created_at, finished_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Format,
		&i.Status,
		&i.WindowDays,
		&i.StorageKey,
		&i.SizeBytes,
		&i.Error,
		&i.JobID,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, project_id, format, status, window_days, storage_key, size_bytes,
       error, job_id, requested_by, created_at, finished_at
FROM reports
WHERE project_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type ListReportsParams struct {
	ProjectID uuid.UUID
	Cursor    *time.Time
	PageSize  int32
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.ProjectID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Format,
			&i.Status,
			&i.WindowDays,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Error,
			&i.JobID,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportRunning = `-- name: MarkReportRunning :execrows
UPDATE reports SET status = 'running' WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkReportRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markReportRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reportDefects = `-- name: ReportDefects :many
SELECT d.id, d.title, d.severity, d.status, d.created_at,
       (SELECT count(*) FROM defects k WHERE k.duplicate_of = d.id)::bigint AS occurrences
FROM defects d
WHERE d.project_id = $1 AND d.duplicate_of IS NULL
ORDER BY
    CASE d.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
    d.created_at DESC
LIMIT $2
`

type ReportDefectsParams struct {
	ProjectID uuid.UUID
	PageSize  int32
}

type ReportDefectsRow struct {
	ID          uuid.UUID
	Title       string
	Severity    DefectSeverity
	Status      DefectStatus
	CreatedAt   time.Time
	Occurrences int64
}

// ReportDefects lists the defects with how many times the same failure recurred.
// Duplicates are counted rather than listed: three occurrences of one bug is one row
// saying three.
func (q *Queries) ReportDefects(ctx context.Context, arg ReportDefectsParams) ([]ReportDefectsRow, error) {
	rows, err := q.db.Query(ctx, reportDefects, arg.ProjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDefectsRow{}
	for rows.Next() {
		var i ReportDefectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.Occurrences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportFailures = `-- name: ReportFailures :many

SELECT DISTINCT ON (r.name)
       r.id, r.name, r.status, r.failure_message, r.created_at,
       -- coalesced rather than nullable, because "no analysis" and "an analysis with
       -- an empty root cause" are the same thing to a reader, and a nullable column
       -- here would put four pointer checks in the renderer for no gain.
       coalesce(a.reason, '') AS reason,
       coalesce(a.root_cause, '') AS root_cause,
       coalesce(a.suggested_fix, '') AS suggested_fix,
       coalesce(a.evidence, '[]'::jsonb) AS evidence,
       a.stability_score,
       d.id AS defect_id
FROM run_results r
JOIN runs n ON n.id = r.run_id
LEFT JOIN LATERAL (
    SELECT x.reason, x.root_cause, x.suggested_fix, x.evidence, x.stability_score
    FROM analyses x
    WHERE x.run_result_id = r.id
    ORDER BY x.created_at DESC
    LIMIT 1
) a ON true
LEFT JOIN defects d ON d.run_result_id = r.id
WHERE n.project_id = $1
  AND n.created_at >= $2
  AND r.status IN ('failed', 'flaky', 'errored')
ORDER BY r.name, (a.reason IS NOT NULL) DESC, r.created_at DESC
LIMIT $3
`

type ReportFailuresParams struct {
	ProjectID uuid.UUID
	CreatedAt time.Time
	PageSize  int32
}

type ReportFailuresRow struct {
	ID             uuid.UUID
	Name           string
	Status         RunResultStatus
	FailureMessage string
	CreatedAt      time.Time
	Reason         string
	RootCause      string
	SuggestedFix   string
	Evidence       json.RawMessage
	StabilityScore *decimal.Decimal
	DefectID       *uuid.UUID
}

// The report's own reads (BE-5.9.2). They live here rather than being assembled from
// four services, because one document's definition split across four packages is a
// document whose sections drift apart.
// ReportFailures is every failure in the window with its newest analysis, if it has
// one, and the defect it was promoted to, if it was. A left join in both cases: a
// report that hid unexplained failures would look better than the project is.
// One row per test, preferring the newest occurrence that has an explanation. The
// alternative is showing "not analysed" for a failure the platform did explain, just
// on an earlier run of the same test, which reads as a gap in the analysis rather
// than what it is.
func (q *Queries) ReportFailures(ctx context.Context, arg ReportFailuresParams) ([]ReportFailuresRow, error) {
	rows, err := q.db.Query(ctx, reportFailures, arg.ProjectID, arg.CreatedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportFailuresRow{}
	for rows.Next() {
		var i ReportFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.FailureMessage,
			&i.CreatedAt,
			&i.Reason,
			&i.RootCause,
			&i.SuggestedFix,
			&i.Evidence,
			&i.StabilityScore,
			&i.DefectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
