// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: riskcontrol.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const confirmHost = `-- name: ConfirmHost :one

INSERT INTO risk_confirmations (project_id, kind, host, confirmed_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, kind, host) DO UPDATE
SET confirmed_by = EXCLUDED.confirmed_by, confirmed_at = now()
RETURNING id, project_id, kind, host, confirmed_by, confirmed_at
`

type ConfirmHostParams struct {
	ProjectID   uuid.UUID
	Kind        string
	Host        string
	ConfirmedBy *uuid.UUID
}

// Confirmed hosts for the two dangerous test kinds (BE-9.5).
func (q *Queries) ConfirmHost(ctx context.Context, arg ConfirmHostParams) (RiskConfirmation, error) {
	row := q.db.QueryRow(ctx, confirmHost,
		arg.ProjectID,
		arg.Kind,
		arg.Host,
		arg.ConfirmedBy,
	)
	var i RiskConfirmation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Host,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const hostConfirmed = `-- name: HostConfirmed :one
SELECT EXISTS (
    SELECT 1 FROM risk_confirmations
    WHERE project_id = $1 AND kind = $2 AND host = $3
) AS confirmed
`

type HostConfirmedParams struct {
	ProjectID uuid.UUID
	Kind      string
	Host      string
}

func (q *Queries) HostConfirmed(ctx context.Context, arg HostConfirmedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostConfirmed, arg.ProjectID, arg.Kind, arg.Host)
	var confirmed bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const listConfirmedHosts = `-- name: ListConfirmedHosts :many
SELECT id, project_id, kind, host, confirmed_by, confirmed_at
FROM risk_confirmations
WHERE project_id = $1 AND kind = $2
ORDER BY confirmed_at DESC
`

type ListConfirmedHostsParams struct {
	ProjectID uuid.UUID
	Kind      string
}

func (q *Queries) ListConfirmedHosts(ctx context.Context, arg ListConfirmedHostsParams) ([]RiskConfirmation, error) {
	rows, err := q.db.Query(ctx, listConfirmedHosts, arg.ProjectID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskConfirmation{}
	for rows.Next() {
		var i RiskConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Host,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
