// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeQuarantines = `-- name: ActiveQuarantines :many

SELECT id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
       source, owner_id, released_at, released_by, release_note, last_flaked_at,
       created_at, updated_at
FROM quarantines
WHERE project_id = $1 AND released_at IS NULL
ORDER BY created_at
`

// Quarantine (BE-7.6). A test that flakes more than the threshold stops failing the
// run and appears on a list with an owner and an age.
func (q *Queries) ActiveQuarantines(ctx context.Context, projectID uuid.UUID) ([]Quarantine, error) {
	rows, err := q.db.Query(ctx, activeQuarantines, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quarantine{}
	for rows.Next() {
		var i Quarantine
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TestName,
			&i.TestCaseID,
			&i.Reason,
			&i.FlakeCount,
			&i.WindowRuns,
			&i.Source,
			&i.OwnerID,
			&i.ReleasedAt,
			&i.ReleasedBy,
			&i.ReleaseNote,
			&i.LastFlakedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type AppendRunLogLinesParams struct {
	RunID uuid.UUID
	Line  string
}

const assignQuarantineOwner = `-- name: AssignQuarantineOwner :one
UPDATE quarantines
SET owner_id = $2, updated_at = now()
WHERE id = $1 AND released_at IS NULL
RETURNING id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
          source, owner_id, released_at, released_by, release_note, last_flaked_at,
          created_at, updated_at
`

type AssignQuarantineOwnerParams struct {
	ID      uuid.UUID
	OwnerID *uuid.UUID
}

func (q *Queries) AssignQuarantineOwner(ctx context.Context, arg AssignQuarantineOwnerParams) (Quarantine, error) {
	row := q.db.QueryRow(ctx, assignQuarantineOwner, arg.ID, arg.OwnerID)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TestName,
		&i.TestCaseID,
		&i.Reason,
		&i.FlakeCount,
		&i.WindowRuns,
		&i.Source,
		&i.OwnerID,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.ReleaseNote,
		&i.LastFlakedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelRun = `-- name: CancelRun :execrows
UPDATE runs
SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CancelRun(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearRunLog = `-- name: ClearRunLog :exec
UPDATE runs SET log_key = '' WHERE id = $1
`

func (q *Queries) ClearRunLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRunLog, id)
	return err
}

const clearRunResultArtifacts = `-- name: ClearRunResultArtifacts :exec
UPDATE run_results
SET screenshot_key = '', video_key = '', trace_key = ''
WHERE id = $1
`

// ClearRunResultArtifacts forgets the keys after the objects are gone. In that order:
// a stored file with no key wastes space, while a key with no file is a download that
// fails, and only one of those is visible to a user.
func (q *Queries) ClearRunResultArtifacts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRunResultArtifacts, id)
	return err
}

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT count(*) FROM runs WHERE status = 'running'
`

// CountActiveRuns backs the concurrency limit's "waiting for a slot" message: the
// semaphore is what enforces it, and this is what explains it (BE-4.10).
func (q *Queries) CountActiveRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveRunsForProject = `-- name: CountActiveRunsForProject :one
SELECT count(*) FROM runs
WHERE project_id = $1 AND status IN ('queued', 'running')
`

// CountActiveRunsForProject backs the per-project cap. Global concurrency is a
// semaphore in the worker; this is the check that stops one project queueing ten
// runs and starving every other project behind them (BE-4.10).
func (q *Queries) CountActiveRunsForProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRunsForProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunResultsByStatus = `-- name: CountRunResultsByStatus :many
SELECT status, count(*)::bigint AS total
FROM run_results
WHERE run_id = $1
GROUP BY status
`

type CountRunResultsByStatusRow struct {
	Status RunResultStatus
	Total  int64
}

func (q *Queries) CountRunResultsByStatus(ctx context.Context, runID uuid.UUID) ([]CountRunResultsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRunResultsByStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRunResultsByStatusRow{}
	for rows.Next() {
		var i CountRunResultsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (project_id, job_id, target_url, trigger, framework, image, triggered_by,
                  kind, load_profile)
VALUES (
    $1, $6::uuid, $2, $3, $4, $5, $7::uuid,
    $8, $9
)
RETURNING id, project_id, job_id, target_url, trigger, status, framework, image,
          total, passed, failed, flaky, skipped, duration_ms, error, log_key,
          triggered_by, started_at, finished_at, created_at, quarantined, kind, load_profile
`

type CreateRunParams struct {
	ProjectID   uuid.UUID
	TargetUrl   string
	Trigger     RunTrigger
	Framework   TestFramework
	Image       string
	JobID       *uuid.UUID
	TriggeredBy *uuid.UUID
	Kind        RunKind
	LoadProfile json.RawMessage
}

// Runs, results, and the command log.
//
// The counts on the runs row are maintained when results are written, so the
// dashboard reads one row rather than aggregating a result table that grows with
// every execution.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.TargetUrl,
		arg.Trigger,
		arg.Framework,
		arg.Image,
		arg.JobID,
		arg.TriggeredBy,
		arg.Kind,
		arg.LoadProfile,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.JobID,
		&i.TargetUrl,
		&i.Trigger,
		&i.Status,
		&i.Framework,
		&i.Image,
		&i.Total,
		&i.Passed,
		&i.Failed,
		&i.Flaky,
		&i.Skipped,
		&i.DurationMs,
		&i.Error,
		&i.LogKey,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Quarantined,
		&i.Kind,
		&i.LoadProfile,
	)
	return i, err
}

type CreateRunResultsBulkParams struct {
	RunID          uuid.UUID
	TestCaseID     *uuid.UUID
	TestFileID     *uuid.UUID
	Name           string
	Status         RunResultStatus
	DurationMs     int32
	Attempt        int32
	FailureMessage string
	LogKey         string
	ScreenshotKey  string
	VideoKey       string
	TraceKey       string
	Quarantined    bool
}

const deleteRunLogLines = `-- name: DeleteRunLogLines :exec
DELETE FROM run_log_lines WHERE run_id = $1
`

func (q *Queries) DeleteRunLogLines(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunLogLines, runID)
	return err
}

const deleteRunResults = `-- name: DeleteRunResults :exec
DELETE FROM run_results WHERE run_id = $1
`

// DeleteRunResults makes the result write idempotent: a redelivered execute job
// replaces its own results rather than doubling them (BE-4.9.5).
func (q *Queries) DeleteRunResults(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunResults, runID)
	return err
}

const finishRun = `-- name: FinishRun :one
UPDATE runs
SET status = $2, total = $3, passed = $4, failed = $5, flaky = $6, skipped = $7,
    quarantined = $11,
    duration_ms = $8, error = $9, log_key = $10, finished_at = now()
WHERE id = $1
RETURNING id, project_id, job_id, target_url, trigger, status, framework, image,
          total, passed, failed, flaky, skipped, duration_ms, error, log_key,
          triggered_by, started_at, finished_at, created_at, quarantined, kind, load_profile
`

type FinishRunParams struct {
	ID          uuid.UUID
	Status      RunStatus
	Total       int32
	Passed      int32
	Failed      int32
	Flaky       int32
	Skipped     int32
	DurationMs  int32
	Error       string
	LogKey      string
	Quarantined int32
}

// FinishRun writes the outcome and the counts in one statement, so a dashboard can
// never read a run that is finished but not yet counted.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Total,
		arg.Passed,
		arg.Failed,
		arg.Flaky,
		arg.Skipped,
		arg.DurationMs,
		arg.Error,
		arg.LogKey,
		arg.Quarantined,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.JobID,
		&i.TargetUrl,
		&i.Trigger,
		&i.Status,
		&i.Framework,
		&i.Image,
		&i.Total,
		&i.Passed,
		&i.Failed,
		&i.Flaky,
		&i.Skipped,
		&i.DurationMs,
		&i.Error,
		&i.LogKey,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Quarantined,
		&i.Kind,
		&i.LoadProfile,
	)
	return i, err
}

const flakeCountsForProject = `-- name: FlakeCountsForProject :many
WITH recent AS (
    SELECT id
    FROM runs
    WHERE project_id = $1 AND finished_at IS NOT NULL
    ORDER BY finished_at DESC
    LIMIT $2
),
per_run AS (
    SELECT rr.name,
           rr.run_id,
           bool_or(rr.status = 'passed') AS ever_passed,
           bool_or(rr.status IN ('failed', 'errored', 'flaky')) AS ever_failed
    FROM run_results rr
    JOIN recent ON recent.id = rr.run_id
    GROUP BY rr.name, rr.run_id
)
SELECT name,
       count(*) FILTER (WHERE ever_passed AND ever_failed)::bigint AS flaky_runs,
       count(*)::bigint AS seen_runs
FROM per_run
GROUP BY name
`

type FlakeCountsForProjectParams struct {
	ProjectID  uuid.UUID
	WindowRuns int32
}

type FlakeCountsForProjectRow struct {
	Name      string
	FlakyRuns int64
	SeenRuns  int64
}

// FlakeCountsForProject is the arithmetic behind an automatic quarantine: how many of
// the last N finished runs saw each test flake. Counted from the results rather than
// from a stored score, because a score is a summary and this decision deserves the
// underlying facts (BE-4.13).
// A test flaked in a run when that run holds both a passing and a failing attempt of
// it. Derived rather than read from a status column, because the results table stores
// what each attempt did and `flaky` is a conclusion about a set of attempts: the run
// row carries the tally, and the rows carry the facts it was computed from (BE-4.13.2).
func (q *Queries) FlakeCountsForProject(ctx context.Context, arg FlakeCountsForProjectParams) ([]FlakeCountsForProjectRow, error) {
	rows, err := q.db.Query(ctx, flakeCountsForProject, arg.ProjectID, arg.WindowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlakeCountsForProjectRow{}
	for rows.Next() {
		var i FlakeCountsForProjectRow
		if err := rows.Scan(&i.Name, &i.FlakyRuns, &i.SeenRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuarantine = `-- name: GetQuarantine :one
SELECT id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
       source, owner_id, released_at, released_by, release_note, last_flaked_at,
       created_at, updated_at
FROM quarantines
WHERE id = $1
`

func (q *Queries) GetQuarantine(ctx context.Context, id uuid.UUID) (Quarantine, error) {
	row := q.db.QueryRow(ctx, getQuarantine, id)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TestName,
		&i.TestCaseID,
		&i.Reason,
		&i.FlakeCount,
		&i.WindowRuns,
		&i.Source,
		&i.OwnerID,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.ReleaseNote,
		&i.LastFlakedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, job_id, target_url, trigger, status, framework, image,
       total, passed, failed, flaky, skipped, duration_ms, error, log_key,
       triggered_by, started_at, finished_at, created_at, quarantined, kind, load_profile
FROM runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.JobID,
		&i.TargetUrl,
		&i.Trigger,
		&i.Status,
		&i.Framework,
		&i.Image,
		&i.Total,
		&i.Passed,
		&i.Failed,
		&i.Flaky,
		&i.Skipped,
		&i.DurationMs,
		&i.Error,
		&i.LogKey,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Quarantined,
		&i.Kind,
		&i.LoadProfile,
	)
	return i, err
}

const getRunMetrics = `-- name: GetRunMetrics :one
SELECT run_id, requests, throughput, error_rate,
       latency_avg_ms, latency_p50_ms, latency_p90_ms, latency_p95_ms, latency_p99_ms, latency_max_ms,
       virtual_users, duration_ms, created_at
FROM run_metrics
WHERE run_id = $1
`

func (q *Queries) GetRunMetrics(ctx context.Context, runID uuid.UUID) (RunMetric, error) {
	row := q.db.QueryRow(ctx, getRunMetrics, runID)
	var i RunMetric
	err := row.Scan(
		&i.RunID,
		&i.Requests,
		&i.Throughput,
		&i.ErrorRate,
		&i.LatencyAvgMs,
		&i.LatencyP50Ms,
		&i.LatencyP90Ms,
		&i.LatencyP95Ms,
		&i.LatencyP99Ms,
		&i.LatencyMaxMs,
		&i.VirtualUsers,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const listQuarantines = `-- name: ListQuarantines :many
SELECT id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
       source, owner_id, released_at, released_by, release_note, last_flaked_at,
       created_at, updated_at
FROM quarantines
WHERE project_id = $1
  AND ($2::bool IS TRUE OR released_at IS NULL)
ORDER BY released_at NULLS FIRST, created_at
LIMIT $3
`

type ListQuarantinesParams struct {
	ProjectID       uuid.UUID
	IncludeReleased *bool
	PageSize        int32
}

func (q *Queries) ListQuarantines(ctx context.Context, arg ListQuarantinesParams) ([]Quarantine, error) {
	rows, err := q.db.Query(ctx, listQuarantines, arg.ProjectID, arg.IncludeReleased, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quarantine{}
	for rows.Next() {
		var i Quarantine
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TestName,
			&i.TestCaseID,
			&i.Reason,
			&i.FlakeCount,
			&i.WindowRuns,
			&i.Source,
			&i.OwnerID,
			&i.ReleasedAt,
			&i.ReleasedBy,
			&i.ReleaseNote,
			&i.LastFlakedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunArtifactsOlderThan = `-- name: ListRunArtifactsOlderThan :many
SELECT rr.id, rr.screenshot_key, rr.video_key, rr.trace_key
FROM run_results rr
JOIN runs r ON r.id = rr.run_id
WHERE r.finished_at IS NOT NULL
  AND r.finished_at < $1
  AND (rr.screenshot_key <> '' OR rr.video_key <> '' OR rr.trace_key <> '')
ORDER BY r.finished_at
LIMIT $2
`

type ListRunArtifactsOlderThanParams struct {
	FinishedAt *time.Time
	PageSize   int32
}

type ListRunArtifactsOlderThanRow struct {
	ID            uuid.UUID
	ScreenshotKey string
	VideoKey      string
	TraceKey      string
}

// Run artifact retention (BE-7.5.3). A video, a trace, and a screenshot are the
// largest things this platform stores, and they are stored per failing attempt: an
// installation that never expires them fills a disk with evidence about tests nobody
// is still investigating.
//
// The cutoff is the run's finish time rather than the result's creation, because a run
// and its evidence expire together: half a run's artifacts is worse than none.
func (q *Queries) ListRunArtifactsOlderThan(ctx context.Context, arg ListRunArtifactsOlderThanParams) ([]ListRunArtifactsOlderThanRow, error) {
	rows, err := q.db.Query(ctx, listRunArtifactsOlderThan, arg.FinishedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunArtifactsOlderThanRow{}
	for rows.Next() {
		var i ListRunArtifactsOlderThanRow
		if err := rows.Scan(
			&i.ID,
			&i.ScreenshotKey,
			&i.VideoKey,
			&i.TraceKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCommands = `-- name: ListRunCommands :many
SELECT id, run_id, command, exit_code, duration_ms, output_excerpt, at
FROM run_commands
WHERE run_id = $1
ORDER BY id
`

func (q *Queries) ListRunCommands(ctx context.Context, runID uuid.UUID) ([]RunCommand, error) {
	rows, err := q.db.Query(ctx, listRunCommands, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunCommand{}
	for rows.Next() {
		var i RunCommand
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Command,
			&i.ExitCode,
			&i.DurationMs,
			&i.OutputExcerpt,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogLinesSince = `-- name: ListRunLogLinesSince :many
SELECT id, run_id, line, at
FROM run_log_lines
WHERE run_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListRunLogLinesSinceParams struct {
	RunID uuid.UUID
	ID    int64
	Limit int32
}

func (q *Queries) ListRunLogLinesSince(ctx context.Context, arg ListRunLogLinesSinceParams) ([]RunLogLine, error) {
	rows, err := q.db.Query(ctx, listRunLogLinesSince, arg.RunID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunLogLine{}
	for rows.Next() {
		var i RunLogLine
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Line,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogsOlderThan = `-- name: ListRunLogsOlderThan :many
SELECT id, log_key
FROM runs
WHERE finished_at IS NOT NULL
  AND finished_at < $1
  AND log_key <> ''
ORDER BY finished_at
LIMIT $2
`

type ListRunLogsOlderThanParams struct {
	FinishedAt *time.Time
	PageSize   int32
}

type ListRunLogsOlderThanRow struct {
	ID     uuid.UUID
	LogKey string
}

func (q *Queries) ListRunLogsOlderThan(ctx context.Context, arg ListRunLogsOlderThanParams) ([]ListRunLogsOlderThanRow, error) {
	rows, err := q.db.Query(ctx, listRunLogsOlderThan, arg.FinishedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunLogsOlderThanRow{}
	for rows.Next() {
		var i ListRunLogsOlderThanRow
		if err := rows.Scan(&i.ID, &i.LogKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunResults = `-- name: ListRunResults :many
SELECT id, run_id, test_case_id, test_file_id, name, status, duration_ms, attempt,
       failure_message, log_key, screenshot_key, video_key, created_at, trace_key,
       quarantined
FROM run_results
WHERE run_id = $1
  AND ($2::run_result_status IS NULL
       OR status = $2::run_result_status)
ORDER BY name, attempt
LIMIT $4 OFFSET $3
`

type ListRunResultsParams struct {
	RunID     uuid.UUID
	Status    NullRunResultStatus
	RowOffset int32
	PageSize  int32
}

func (q *Queries) ListRunResults(ctx context.Context, arg ListRunResultsParams) ([]RunResult, error) {
	rows, err := q.db.Query(ctx, listRunResults,
		arg.RunID,
		arg.Status,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunResult{}
	for rows.Next() {
		var i RunResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TestCaseID,
			&i.TestFileID,
			&i.Name,
			&i.Status,
			&i.DurationMs,
			&i.Attempt,
			&i.FailureMessage,
			&i.LogKey,
			&i.ScreenshotKey,
			&i.VideoKey,
			&i.CreatedAt,
			&i.TraceKey,
			&i.Quarantined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, project_id, job_id, target_url, trigger, status, framework, image,
       total, passed, failed, flaky, skipped, duration_ms, error, log_key,
       triggered_by, started_at, finished_at, created_at, quarantined, kind, load_profile
FROM runs
WHERE project_id = $1
  AND ($2::run_kind IS NULL OR kind = $2::run_kind)
  AND ($3::run_status IS NULL OR status = $3::run_status)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC
LIMIT $5
`

type ListRunsParams struct {
	ProjectID uuid.UUID
	Kind      NullRunKind
	Status    NullRunStatus
	Cursor    *time.Time
	PageSize  int32
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.ProjectID,
		arg.Kind,
		arg.Status,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.TargetUrl,
			&i.Trigger,
			&i.Status,
			&i.Framework,
			&i.Image,
			&i.Total,
			&i.Passed,
			&i.Failed,
			&i.Flaky,
			&i.Skipped,
			&i.DurationMs,
			&i.Error,
			&i.LogKey,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Quarantined,
			&i.Kind,
			&i.LoadProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRuns = `-- name: ListStaleRuns :many
SELECT id, project_id, started_at
FROM runs
WHERE status = 'running' AND started_at < $1
ORDER BY started_at
LIMIT $2
`

type ListStaleRunsParams struct {
	StartedAt *time.Time
	PageSize  int32
}

type ListStaleRunsRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	StartedAt *time.Time
}

// ListStaleRuns finds runs a crashed worker left behind, so the sweeper can mark
// them errored rather than leaving them running forever (BE-4.2).
func (q *Queries) ListStaleRuns(ctx context.Context, arg ListStaleRunsParams) ([]ListStaleRunsRow, error) {
	rows, err := q.db.Query(ctx, listStaleRuns, arg.StartedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleRunsRow{}
	for rows.Next() {
		var i ListStaleRunsRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunFailed = `-- name: MarkRunFailed :execrows
UPDATE runs
SET status = 'errored', error = $2, finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
`

type MarkRunFailedParams struct {
	ID    uuid.UUID
	Error string
}

// MarkRunFailed is the sweeper's write: a run whose worker died is errored with a
// stated reason rather than left running forever.
func (q *Queries) MarkRunFailed(ctx context.Context, arg MarkRunFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunFailed, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRunStarted = `-- name: MarkRunStarted :execrows
UPDATE runs
SET status = 'running', started_at = coalesce(started_at, now()), image = $2
WHERE id = $1 AND status = 'queued'
`

type MarkRunStartedParams struct {
	ID    uuid.UUID
	Image string
}

func (q *Queries) MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunStarted, arg.ID, arg.Image)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectDashboard = `-- name: ProjectDashboard :one
SELECT
    (SELECT count(*) FROM requirements q WHERE q.project_id = $1)::bigint AS requirements,
    (SELECT count(*) FROM test_cases c
      WHERE c.project_id = $1 AND c.superseded_by IS NULL)::bigint AS test_cases,
    (SELECT count(*) FROM test_cases a
      WHERE a.project_id = $1 AND a.superseded_by IS NULL
        AND a.status = 'approved')::bigint AS approved_cases,
    (SELECT count(*) FROM test_files f WHERE f.project_id = $1)::bigint AS test_files,
    (SELECT count(*) FROM runs r WHERE r.project_id = $1)::bigint AS runs,
    -- The pass, fail, and flake counts are the latest finished run, not a lifetime
    -- sum. A sum grows forever and answers a question nobody asked: what a dashboard
    -- has to say is "where does this project stand now", and that is the last run
    -- that actually produced results (F-12.1).
    (SELECT coalesce(l.passed, 0) FROM runs l
      WHERE l.project_id = $1 AND l.status NOT IN ('queued', 'running')
      ORDER BY l.created_at DESC LIMIT 1)::bigint AS passed,
    (SELECT coalesce(x.failed, 0) FROM runs x
      WHERE x.project_id = $1 AND x.status NOT IN ('queued', 'running')
      ORDER BY x.created_at DESC LIMIT 1)::bigint AS failed,
    (SELECT coalesce(k.flaky, 0) FROM runs k
      WHERE k.project_id = $1 AND k.status NOT IN ('queued', 'running')
      ORDER BY k.created_at DESC LIMIT 1)::bigint AS flaky
`

type ProjectDashboardRow struct {
	Requirements  int64
	TestCases     int64
	ApprovedCases int64
	TestFiles     int64
	Runs          int64
	Passed        int64
	Failed        int64
	Flaky         int64
}

// ProjectDashboard is the counts panel (F-12.1) as one query rather than five.
//
// Every subquery qualifies its own table: without the alias the planner and the
// generator both have to guess which project_id is meant, and one of them guesses
// differently.
func (q *Queries) ProjectDashboard(ctx context.Context, projectID uuid.UUID) (ProjectDashboardRow, error) {
	row := q.db.QueryRow(ctx, projectDashboard, projectID)
	var i ProjectDashboardRow
	err := row.Scan(
		&i.Requirements,
		&i.TestCases,
		&i.ApprovedCases,
		&i.TestFiles,
		&i.Runs,
		&i.Passed,
		&i.Failed,
		&i.Flaky,
	)
	return i, err
}

const quarantineTest = `-- name: QuarantineTest :one
INSERT INTO quarantines (
    project_id, test_name, test_case_id, reason, flake_count, window_runs, source,
    owner_id, last_flaked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (project_id, test_name) WHERE released_at IS NULL
DO UPDATE SET reason = EXCLUDED.reason,
              flake_count = EXCLUDED.flake_count,
              window_runs = EXCLUDED.window_runs,
              last_flaked_at = now(),
              updated_at = now()
RETURNING id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
          source, owner_id, released_at, released_by, release_note, last_flaked_at,
          created_at, updated_at
`

type QuarantineTestParams struct {
	ProjectID  uuid.UUID
	TestName   string
	TestCaseID *uuid.UUID
	Reason     string
	FlakeCount int32
	WindowRuns int32
	Source     string
	OwnerID    *uuid.UUID
}

// QuarantineTest is idempotent on the live row: a second run that finds the same test
// still flaking updates the arithmetic and the last-flaked time rather than creating a
// second quarantine for the same test.
func (q *Queries) QuarantineTest(ctx context.Context, arg QuarantineTestParams) (Quarantine, error) {
	row := q.db.QueryRow(ctx, quarantineTest,
		arg.ProjectID,
		arg.TestName,
		arg.TestCaseID,
		arg.Reason,
		arg.FlakeCount,
		arg.WindowRuns,
		arg.Source,
		arg.OwnerID,
	)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TestName,
		&i.TestCaseID,
		&i.Reason,
		&i.FlakeCount,
		&i.WindowRuns,
		&i.Source,
		&i.OwnerID,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.ReleaseNote,
		&i.LastFlakedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordRunCommand = `-- name: RecordRunCommand :exec
INSERT INTO run_commands (run_id, command, exit_code, duration_ms, output_excerpt)
VALUES ($1, $2, $5::integer, $3, $4)
`

type RecordRunCommandParams struct {
	RunID         uuid.UUID
	Command       string
	DurationMs    int32
	OutputExcerpt string
	ExitCode      *int32
}

func (q *Queries) RecordRunCommand(ctx context.Context, arg RecordRunCommandParams) error {
	_, err := q.db.Exec(ctx, recordRunCommand,
		arg.RunID,
		arg.Command,
		arg.DurationMs,
		arg.OutputExcerpt,
		arg.ExitCode,
	)
	return err
}

const releaseQuarantine = `-- name: ReleaseQuarantine :one
UPDATE quarantines
SET released_at = now(), released_by = $2, release_note = $3, updated_at = now()
WHERE id = $1 AND released_at IS NULL
RETURNING id, project_id, test_name, test_case_id, reason, flake_count, window_runs,
          source, owner_id, released_at, released_by, release_note, last_flaked_at,
          created_at, updated_at
`

type ReleaseQuarantineParams struct {
	ID          uuid.UUID
	ReleasedBy  *uuid.UUID
	ReleaseNote string
}

func (q *Queries) ReleaseQuarantine(ctx context.Context, arg ReleaseQuarantineParams) (Quarantine, error) {
	row := q.db.QueryRow(ctx, releaseQuarantine, arg.ID, arg.ReleasedBy, arg.ReleaseNote)
	var i Quarantine
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TestName,
		&i.TestCaseID,
		&i.Reason,
		&i.FlakeCount,
		&i.WindowRuns,
		&i.Source,
		&i.OwnerID,
		&i.ReleasedAt,
		&i.ReleasedBy,
		&i.ReleaseNote,
		&i.LastFlakedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resultHistoryForCase = `-- name: ResultHistoryForCase :many
SELECT r.id, r.run_id, r.status, r.duration_ms, r.attempt, r.created_at
FROM run_results r
WHERE r.test_case_id = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ResultHistoryForCaseParams struct {
	TestCaseID *uuid.UUID
	PageSize   int32
}

type ResultHistoryForCaseRow struct {
	ID         uuid.UUID
	RunID      uuid.UUID
	Status     RunResultStatus
	DurationMs int32
	Attempt    int32
	CreatedAt  time.Time
}

// ResultHistoryForCase backs the stability score and the flake view: the same case
// across runs, newest first.
func (q *Queries) ResultHistoryForCase(ctx context.Context, arg ResultHistoryForCaseParams) ([]ResultHistoryForCaseRow, error) {
	rows, err := q.db.Query(ctx, resultHistoryForCase, arg.TestCaseID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResultHistoryForCaseRow{}
	for rows.Next() {
		var i ResultHistoryForCaseRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Status,
			&i.DurationMs,
			&i.Attempt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runTrend = `-- name: RunTrend :many
SELECT id, created_at, status, total, passed, failed, flaky, skipped, quarantined, duration_ms
FROM runs
WHERE project_id = $1 AND created_at >= $2 AND status NOT IN ('queued', 'running')
ORDER BY created_at
`

type RunTrendParams struct {
	ProjectID uuid.UUID
	CreatedAt time.Time
}

type RunTrendRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Status      RunStatus
	Total       int32
	Passed      int32
	Failed      int32
	Flaky       int32
	Skipped     int32
	Quarantined int32
	DurationMs  int32
}

// RunTrend is the dashboard's trend panel: one row per run, oldest first, so a
// chart plots it without reversing.
func (q *Queries) RunTrend(ctx context.Context, arg RunTrendParams) ([]RunTrendRow, error) {
	rows, err := q.db.Query(ctx, runTrend, arg.ProjectID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunTrendRow{}
	for rows.Next() {
		var i RunTrendRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Status,
			&i.Total,
			&i.Passed,
			&i.Failed,
			&i.Flaky,
			&i.Skipped,
			&i.Quarantined,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeRunMetrics = `-- name: StoreRunMetrics :exec

INSERT INTO run_metrics (
    run_id, requests, throughput, error_rate,
    latency_avg_ms, latency_p50_ms, latency_p90_ms, latency_p95_ms, latency_p99_ms, latency_max_ms,
    virtual_users, duration_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (run_id) DO UPDATE
SET requests = EXCLUDED.requests, throughput = EXCLUDED.throughput, error_rate = EXCLUDED.error_rate,
    latency_avg_ms = EXCLUDED.latency_avg_ms, latency_p50_ms = EXCLUDED.latency_p50_ms,
    latency_p90_ms = EXCLUDED.latency_p90_ms, latency_p95_ms = EXCLUDED.latency_p95_ms,
    latency_p99_ms = EXCLUDED.latency_p99_ms, latency_max_ms = EXCLUDED.latency_max_ms,
    virtual_users = EXCLUDED.virtual_users, duration_ms = EXCLUDED.duration_ms
`

type StoreRunMetricsParams struct {
	RunID        uuid.UUID
	Requests     int64
	Throughput   float64
	ErrorRate    float64
	LatencyAvgMs float64
	LatencyP50Ms float64
	LatencyP90Ms float64
	LatencyP95Ms float64
	LatencyP99Ms float64
	LatencyMaxMs float64
	VirtualUsers int32
	DurationMs   int64
}

// Performance metrics (BE-9.1). One row per run: a run has one summary, and a
// percentile is the summary rather than a sample of one.
func (q *Queries) StoreRunMetrics(ctx context.Context, arg StoreRunMetricsParams) error {
	_, err := q.db.Exec(ctx, storeRunMetrics,
		arg.RunID,
		arg.Requests,
		arg.Throughput,
		arg.ErrorRate,
		arg.LatencyAvgMs,
		arg.LatencyP50Ms,
		arg.LatencyP90Ms,
		arg.LatencyP95Ms,
		arg.LatencyP99Ms,
		arg.LatencyMaxMs,
		arg.VirtualUsers,
		arg.DurationMs,
	)
	return err
}
