// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createSecurityFinding = `-- name: CreateSecurityFinding :one

INSERT INTO security_findings (
    run_result_id, run_id, payload_id, category, endpoint, parameter,
    severity, evidence, reproduction
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, run_result_id, run_id, payload_id, category, endpoint, parameter,
          severity, evidence, reproduction, created_at
`

type CreateSecurityFindingParams struct {
	RunResultID  uuid.UUID
	RunID        uuid.UUID
	PayloadID    string
	Category     string
	Endpoint     string
	Parameter    string
	Severity     string
	Evidence     string
	Reproduction string
}

// Security findings (BE-9.4). One per probe that succeeded, keyed to the run_result the
// probe produced so the promote-to-defect path works unchanged.
func (q *Queries) CreateSecurityFinding(ctx context.Context, arg CreateSecurityFindingParams) (SecurityFinding, error) {
	row := q.db.QueryRow(ctx, createSecurityFinding,
		arg.RunResultID,
		arg.RunID,
		arg.PayloadID,
		arg.Category,
		arg.Endpoint,
		arg.Parameter,
		arg.Severity,
		arg.Evidence,
		arg.Reproduction,
	)
	var i SecurityFinding
	err := row.Scan(
		&i.ID,
		&i.RunResultID,
		&i.RunID,
		&i.PayloadID,
		&i.Category,
		&i.Endpoint,
		&i.Parameter,
		&i.Severity,
		&i.Evidence,
		&i.Reproduction,
		&i.CreatedAt,
	)
	return i, err
}

const getSecurityFinding = `-- name: GetSecurityFinding :one
SELECT id, run_result_id, run_id, payload_id, category, endpoint, parameter,
       severity, evidence, reproduction, created_at
FROM security_findings
WHERE id = $1
`

func (q *Queries) GetSecurityFinding(ctx context.Context, id uuid.UUID) (SecurityFinding, error) {
	row := q.db.QueryRow(ctx, getSecurityFinding, id)
	var i SecurityFinding
	err := row.Scan(
		&i.ID,
		&i.RunResultID,
		&i.RunID,
		&i.PayloadID,
		&i.Category,
		&i.Endpoint,
		&i.Parameter,
		&i.Severity,
		&i.Evidence,
		&i.Reproduction,
		&i.CreatedAt,
	)
	return i, err
}

const listSecurityFindings = `-- name: ListSecurityFindings :many
SELECT id, run_result_id, run_id, payload_id, category, endpoint, parameter,
       severity, evidence, reproduction, created_at
FROM security_findings
WHERE run_id = $1
ORDER BY
    CASE severity
        WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2
        WHEN 'low' THEN 3 ELSE 4
    END,
    endpoint
`

func (q *Queries) ListSecurityFindings(ctx context.Context, runID uuid.UUID) ([]SecurityFinding, error) {
	rows, err := q.db.Query(ctx, listSecurityFindings, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityFinding{}
	for rows.Next() {
		var i SecurityFinding
		if err := rows.Scan(
			&i.ID,
			&i.RunResultID,
			&i.RunID,
			&i.PayloadID,
			&i.Category,
			&i.Endpoint,
			&i.Parameter,
			&i.Severity,
			&i.Evidence,
			&i.Reproduction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
