// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSessionsForUser = `-- name: CountSessionsForUser :one
SELECT count(*) FROM sessions WHERE user_id = $1 AND expiry > now()
`

func (q *Queries) CountSessionsForUser(ctx context.Context, userID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expiry < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = $1 AND token <> $2
`

type DeleteOtherSessionsForUserParams struct {
	UserID *uuid.UUID
	Token  string
}

func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

// DeleteSessionsForUser is the immediate-revocation path: offboarding, disabling an
// account, or a password change.
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSession = `-- name: FindSession :one

SELECT token, data, expiry, user_id
FROM sessions
WHERE token = $1 AND expiry > now()
`

// Sessions.
//
// The first three columns are the shape alexedwards/scs expects. user_id is ours:
// scs has no notion of an owner, and without it "revoke every session for this
// user" would mean decoding every blob.
func (q *Queries) FindSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, findSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.Data,
		&i.Expiry,
		&i.UserID,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT token, data, expiry, user_id
FROM sessions
WHERE expiry > now()
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Token,
			&i.Data,
			&i.Expiry,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionUser = `-- name: SetSessionUser :execrows
UPDATE sessions SET user_id = $2 WHERE token = $1
`

type SetSessionUserParams struct {
	Token  string
	UserID *uuid.UUID
}

// SetSessionUser runs immediately after authentication, because scs writes the
// row before anyone knows who is signing in.
func (q *Queries) SetSessionUser(ctx context.Context, arg SetSessionUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionUser, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (token, data, expiry)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET data = EXCLUDED.data, expiry = EXCLUDED.expiry
`

type UpsertSessionParams struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession, arg.Token, arg.Data, arg.Expiry)
	return err
}
