// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM settings
WHERE key = $1
  AND scope = $2
  AND (scope_id IS NULL AND $3::uuid IS NULL OR scope_id = $3::uuid)
`

type DeleteSettingParams struct {
	Key     string
	Scope   SettingsScope
	ScopeID *uuid.UUID
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetting, arg.Key, arg.Scope, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSettingsForScopeID = `-- name: DeleteSettingsForScopeID :execrows
DELETE FROM settings WHERE scope = $1 AND scope_id = $2
`

type DeleteSettingsForScopeIDParams struct {
	Scope   SettingsScope
	ScopeID *uuid.UUID
}

func (q *Queries) DeleteSettingsForScopeID(ctx context.Context, arg DeleteSettingsForScopeIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSettingsForScopeID, arg.Scope, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetting = `-- name: GetSetting :one

SELECT id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
FROM settings
WHERE key = $1
  AND scope = $2
  AND (scope_id IS NULL AND $3::uuid IS NULL OR scope_id = $3::uuid)
`

type GetSettingParams struct {
	Key     string
	Scope   SettingsScope
	ScopeID *uuid.UUID
}

// Settings and the settings audit trail.
//
// Resolution is user -> project -> global -> registry default, and it happens in
// one place in Go. These queries fetch the candidate rows; they do not decide.
func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, arg.Key, arg.Scope, arg.ScopeID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettingChanges = `-- name: ListSettingChanges :many
SELECT id, scope, scope_id, key, old_value, new_value, actor_id, at
FROM settings_audit
WHERE ($1::text IS NULL OR key = $1::text)
  AND ($2::timestamptz IS NULL OR at < $2::timestamptz)
ORDER BY at DESC
LIMIT $3
`

type ListSettingChangesParams struct {
	Key      *string
	Cursor   *time.Time
	PageSize int32
}

func (q *Queries) ListSettingChanges(ctx context.Context, arg ListSettingChangesParams) ([]SettingsAudit, error) {
	rows, err := q.db.Query(ctx, listSettingChanges, arg.Key, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsAudit{}
	for rows.Next() {
		var i SettingsAudit
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Key,
			&i.OldValue,
			&i.NewValue,
			&i.ActorID,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsByScope = `-- name: ListSettingsByScope :many
SELECT id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
FROM settings
WHERE scope = $1
  AND (scope_id IS NULL AND $2::uuid IS NULL OR scope_id = $2::uuid)
ORDER BY key
`

type ListSettingsByScopeParams struct {
	Scope   SettingsScope
	ScopeID *uuid.UUID
}

func (q *Queries) ListSettingsByScope(ctx context.Context, arg ListSettingsByScopeParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettingsByScope, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSettingChange = `-- name: RecordSettingChange :exec
INSERT INTO settings_audit (scope, scope_id, key, old_value, new_value, actor_id)
VALUES ($1, $3::uuid, $2, $4::jsonb, $5::jsonb, $6::uuid)
`

type RecordSettingChangeParams struct {
	Scope    SettingsScope
	Key      string
	ScopeID  *uuid.UUID
	OldValue []byte
	NewValue []byte
	ActorID  *uuid.UUID
}

// The audit row is written in the same transaction as the settings write. For a
// secret both values arrive as '[redacted]': only the fact of the change is kept.
func (q *Queries) RecordSettingChange(ctx context.Context, arg RecordSettingChangeParams) error {
	_, err := q.db.Exec(ctx, recordSettingChange,
		arg.Scope,
		arg.Key,
		arg.ScopeID,
		arg.OldValue,
		arg.NewValue,
		arg.ActorID,
	)
	return err
}

const resolveSetting = `-- name: ResolveSetting :many
SELECT id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
FROM settings
WHERE key = $1
  AND (
    (scope = 'user' AND scope_id = $2::uuid)
    OR (scope = 'project' AND scope_id = $3::uuid)
    OR (scope = 'global' AND scope_id IS NULL)
  )
ORDER BY CASE scope WHEN 'user' THEN 0 WHEN 'project' THEN 1 ELSE 2 END
`

type ResolveSettingParams struct {
	Key       string
	UserID    *uuid.UUID
	ProjectID *uuid.UUID
}

// ResolveSetting returns every stored row that could satisfy one key for one
// caller, ordered strongest scope first. Go takes the first and falls through to
// the registry default when there is none, so a missing row is never a zero value.
func (q *Queries) ResolveSetting(ctx context.Context, arg ResolveSettingParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, resolveSetting, arg.Key, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSettingsForScope = `-- name: ResolveSettingsForScope :many
SELECT id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
FROM settings
WHERE (
    (scope = 'user' AND scope_id = $1::uuid)
    OR (scope = 'project' AND scope_id = $2::uuid)
    OR (scope = 'global' AND scope_id IS NULL)
  )
ORDER BY key, CASE scope WHEN 'user' THEN 0 WHEN 'project' THEN 1 ELSE 2 END
`

type ResolveSettingsForScopeParams struct {
	UserID    *uuid.UUID
	ProjectID *uuid.UUID
}

// ResolveSettingsForScope warms the whole cache in one round trip rather than one
// query per key.
func (q *Queries) ResolveSettingsForScope(ctx context.Context, arg ResolveSettingsForScopeParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, resolveSettingsForScope, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalSetting = `-- name: UpsertGlobalSetting :one
INSERT INTO settings (scope, scope_id, key, value, is_secret, updated_by)
VALUES ('global', NULL, $1, $2, $3, $4::uuid)
ON CONFLICT (key) WHERE scope_id IS NULL DO UPDATE
SET value = EXCLUDED.value,
    is_secret = EXCLUDED.is_secret,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
`

type UpsertGlobalSettingParams struct {
	Key       string
	Value     json.RawMessage
	IsSecret  bool
	UpdatedBy *uuid.UUID
}

// UpsertGlobalSetting exists separately because two NULL scope_ids are distinct to
// a plain unique index, so global rows are constrained by their own partial index
// and need their own ON CONFLICT target.
func (q *Queries) UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertGlobalSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (scope, scope_id, key, value, is_secret, updated_by)
VALUES ($1, $5::uuid, $2, $3, $4, $6::uuid)
ON CONFLICT (scope, scope_id, key) WHERE scope_id IS NOT NULL DO UPDATE
SET value = EXCLUDED.value,
    is_secret = EXCLUDED.is_secret,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, scope, scope_id, key, value, is_secret, updated_by, created_at, updated_at
`

type UpsertSettingParams struct {
	Scope     SettingsScope
	Key       string
	Value     json.RawMessage
	IsSecret  bool
	ScopeID   *uuid.UUID
	UpdatedBy *uuid.UUID
}

// UpsertSetting is the only write path. The unique indexes make it idempotent, so
// a retried job cannot produce a second row for the same key.
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Scope,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.ScopeID,
		arg.UpdatedBy,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
