// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testfiles.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countTestFiles = `-- name: CountTestFiles :one
SELECT count(*) FROM test_files WHERE project_id = $1
`

func (q *Queries) CountTestFiles(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTestFiles, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTestFilesByFramework = `-- name: CountTestFilesByFramework :many
SELECT framework, count(*)::bigint AS total, sum(size_bytes)::bigint AS bytes
FROM test_files
WHERE project_id = $1
GROUP BY framework
ORDER BY framework
`

type CountTestFilesByFrameworkRow struct {
	Framework TestFramework
	Total     int64
	Bytes     int64
}

func (q *Queries) CountTestFilesByFramework(ctx context.Context, projectID uuid.UUID) ([]CountTestFilesByFrameworkRow, error) {
	rows, err := q.db.Query(ctx, countTestFilesByFramework, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTestFilesByFrameworkRow{}
	for rows.Next() {
		var i CountTestFilesByFrameworkRow
		if err := rows.Scan(&i.Framework, &i.Total, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTestFilesForFramework = `-- name: DeleteTestFilesForFramework :execrows
DELETE FROM test_files WHERE project_id = $1 AND framework = $2
`

type DeleteTestFilesForFrameworkParams struct {
	ProjectID uuid.UUID
	Framework TestFramework
}

func (q *Queries) DeleteTestFilesForFramework(ctx context.Context, arg DeleteTestFilesForFrameworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTestFilesForFramework, arg.ProjectID, arg.Framework)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTestFilesForCase = `-- name: FindTestFilesForCase :many
SELECT id, project_id, framework, path, test_case_ids, generated_by,
       validated_at, validation_note, size_bytes, generated_at, updated_at
FROM test_files
WHERE project_id = $1 AND $2::uuid = ANY(test_case_ids)
ORDER BY path
`

type FindTestFilesForCaseParams struct {
	ProjectID uuid.UUID
	Column2   uuid.UUID
}

type FindTestFilesForCaseRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Framework      TestFramework
	Path           string
	TestCaseIds    []uuid.UUID
	GeneratedBy    string
	ValidatedAt    *time.Time
	ValidationNote string
	SizeBytes      int32
	GeneratedAt    time.Time
	UpdatedAt      time.Time
}

// FindTestFilesForCase answers "where is this case implemented", which is the
// traceability half of F-6.11.
func (q *Queries) FindTestFilesForCase(ctx context.Context, arg FindTestFilesForCaseParams) ([]FindTestFilesForCaseRow, error) {
	rows, err := q.db.Query(ctx, findTestFilesForCase, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTestFilesForCaseRow{}
	for rows.Next() {
		var i FindTestFilesForCaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Framework,
			&i.Path,
			&i.TestCaseIds,
			&i.GeneratedBy,
			&i.ValidatedAt,
			&i.ValidationNote,
			&i.SizeBytes,
			&i.GeneratedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestFile = `-- name: GetTestFile :one
SELECT id, project_id, framework, path, content, test_case_ids, generated_by,
       validated_at, validation_note, size_bytes, generated_at, updated_at
FROM test_files
WHERE id = $1
`

func (q *Queries) GetTestFile(ctx context.Context, id uuid.UUID) (TestFile, error) {
	row := q.db.QueryRow(ctx, getTestFile, id)
	var i TestFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Framework,
		&i.Path,
		&i.Content,
		&i.TestCaseIds,
		&i.GeneratedBy,
		&i.ValidatedAt,
		&i.ValidationNote,
		&i.SizeBytes,
		&i.GeneratedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedTestCases = `-- name: ListApprovedTestCases :many
SELECT t.id, t.project_id, t.requirement_id, t.title, t.preconditions, t.steps,
       t.expected, t.priority, t.category, t.status, t.fingerprint, t.endpoint,
       t.superseded_by, t.generated_by, t.created_by, t.created_at, t.updated_at,
       -- The case's own endpoint wins: a requirement may cover the whole API,
       -- and the case knows which operation it calls. The join is the fallback
       -- for a case written before the column existed.
       coalesce(nullif(split_part(t.endpoint, ' ', 1), ''), e.method, '') AS method,
       coalesce(nullif(split_part(t.endpoint, ' ', 2), ''), e.path, '')   AS endpoint_path
FROM test_cases t
LEFT JOIN requirements r ON r.id = t.requirement_id
LEFT JOIN endpoints e ON e.id = r.endpoint_id
WHERE t.project_id = $1
  AND t.superseded_by IS NULL
  AND t.status = 'approved'
ORDER BY endpoint_path, method, t.created_at
`

type ListApprovedTestCasesRow struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	RequirementID *uuid.UUID
	Title         string
	Preconditions string
	Steps         json.RawMessage
	Expected      string
	Priority      TestPriority
	Category      TestCategory
	Status        TestCaseStatus
	Fingerprint   []byte
	Endpoint      string
	SupersededBy  *uuid.UUID
	GeneratedBy   string
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Method        string
	EndpointPath  string
}

// ListApprovedTestCases feeds code generation: approved cases only, because
// generating from a draft somebody is still editing wastes the call (BE-3.2).
func (q *Queries) ListApprovedTestCases(ctx context.Context, projectID uuid.UUID) ([]ListApprovedTestCasesRow, error) {
	rows, err := q.db.Query(ctx, listApprovedTestCases, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedTestCasesRow{}
	for rows.Next() {
		var i ListApprovedTestCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RequirementID,
			&i.Title,
			&i.Preconditions,
			&i.Steps,
			&i.Expected,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Fingerprint,
			&i.Endpoint,
			&i.SupersededBy,
			&i.GeneratedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Method,
			&i.EndpointPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestFiles = `-- name: ListTestFiles :many
SELECT id, project_id, framework, path, test_case_ids, generated_by,
       validated_at, validation_note, size_bytes, generated_at, updated_at
FROM test_files
WHERE project_id = $1
  AND ($2::test_framework IS NULL
       OR framework = $2::test_framework)
  AND ($3::text IS NULL OR path > $3::text)
ORDER BY path
LIMIT $4
`

type ListTestFilesParams struct {
	ProjectID uuid.UUID
	Framework NullTestFramework
	Cursor    *string
	PageSize  int32
}

type ListTestFilesRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Framework      TestFramework
	Path           string
	TestCaseIds    []uuid.UUID
	GeneratedBy    string
	ValidatedAt    *time.Time
	ValidationNote string
	SizeBytes      int32
	GeneratedAt    time.Time
	UpdatedAt      time.Time
}

// ListTestFiles is the tree query. Content is excluded on purpose: it is the one
// column that makes this expensive, and a file browser does not need it.
func (q *Queries) ListTestFiles(ctx context.Context, arg ListTestFilesParams) ([]ListTestFilesRow, error) {
	rows, err := q.db.Query(ctx, listTestFiles,
		arg.ProjectID,
		arg.Framework,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestFilesRow{}
	for rows.Next() {
		var i ListTestFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Framework,
			&i.Path,
			&i.TestCaseIds,
			&i.GeneratedBy,
			&i.ValidatedAt,
			&i.ValidationNote,
			&i.SizeBytes,
			&i.GeneratedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestFilesForExport = `-- name: ListTestFilesForExport :many
SELECT id, project_id, framework, path, content, test_case_ids, generated_by,
       validated_at, validation_note, size_bytes, generated_at, updated_at
FROM test_files
WHERE project_id = $1
  AND ($2::test_framework IS NULL
       OR framework = $2::test_framework)
ORDER BY path
`

type ListTestFilesForExportParams struct {
	ProjectID uuid.UUID
	Framework NullTestFramework
}

// ListTestFilesForExport streams the whole suite, content included. Ordered by
// path so the zip is deterministic: two exports of the same suite produce the
// same archive.
func (q *Queries) ListTestFilesForExport(ctx context.Context, arg ListTestFilesForExportParams) ([]TestFile, error) {
	rows, err := q.db.Query(ctx, listTestFilesForExport, arg.ProjectID, arg.Framework)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestFile{}
	for rows.Next() {
		var i TestFile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Framework,
			&i.Path,
			&i.Content,
			&i.TestCaseIds,
			&i.GeneratedBy,
			&i.ValidatedAt,
			&i.ValidationNote,
			&i.SizeBytes,
			&i.GeneratedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestFileValidation = `-- name: SetTestFileValidation :exec
UPDATE test_files
SET validated_at = now(), validation_note = $2, updated_at = now()
WHERE id = $1
`

type SetTestFileValidationParams struct {
	ID             uuid.UUID
	ValidationNote string
}

func (q *Queries) SetTestFileValidation(ctx context.Context, arg SetTestFileValidationParams) error {
	_, err := q.db.Exec(ctx, setTestFileValidation, arg.ID, arg.ValidationNote)
	return err
}

const upsertTestFile = `-- name: UpsertTestFile :one

INSERT INTO test_files (
    project_id, framework, path, content, test_case_ids, generated_by, size_bytes
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, framework, path) DO UPDATE
SET content       = EXCLUDED.content,
    test_case_ids = EXCLUDED.test_case_ids,
    generated_by  = EXCLUDED.generated_by,
    size_bytes    = EXCLUDED.size_bytes,
    -- A replaced file has not been validated again, so the previous verdict is
    -- cleared rather than carried over onto content it never saw.
    validated_at    = NULL,
    validation_note = '',
    updated_at    = now()
RETURNING id, project_id, framework, path, content, test_case_ids, generated_by,
          validated_at, validation_note, size_bytes, generated_at, updated_at
`

type UpsertTestFileParams struct {
	ProjectID   uuid.UUID
	Framework   TestFramework
	Path        string
	Content     string
	TestCaseIds []uuid.UUID
	GeneratedBy string
	SizeBytes   int32
}

// Generated test files.
//
// Regeneration replaces a file at the same path rather than accumulating copies,
// and every read of a file's content is deliberate: the browsing endpoint returns
// the tree without it, because a 300-file suite is not something to load whole
// to draw a sidebar (BE-3.5).
func (q *Queries) UpsertTestFile(ctx context.Context, arg UpsertTestFileParams) (TestFile, error) {
	row := q.db.QueryRow(ctx, upsertTestFile,
		arg.ProjectID,
		arg.Framework,
		arg.Path,
		arg.Content,
		arg.TestCaseIds,
		arg.GeneratedBy,
		arg.SizeBytes,
	)
	var i TestFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Framework,
		&i.Path,
		&i.Content,
		&i.TestCaseIds,
		&i.GeneratedBy,
		&i.ValidatedAt,
		&i.ValidationNote,
		&i.SizeBytes,
		&i.GeneratedAt,
		&i.UpdatedAt,
	)
	return i, err
}
