// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uitests.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createUIFlow = `-- name: CreateUIFlow :one

INSERT INTO ui_flows (
    project_id, target, auth_mode, document, page_count, flow_count,
    steps, cut_short, artifacts, model_name, job_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, target, auth_mode, document, page_count, flow_count,
          steps, cut_short, artifacts, reviewed_at, reviewed_by, model_name, job_id, created_at
`

type CreateUIFlowParams struct {
	ProjectID uuid.UUID
	Target    string
	AuthMode  string
	Document  json.RawMessage
	PageCount int32
	FlowCount int32
	Steps     int32
	CutShort  bool
	Artifacts json.RawMessage
	ModelName string
	JobID     *uuid.UUID
}

// Discovered UI flow graphs (BE-7.2). One row per discovery: a graph describes an
// application as it behaved at a moment, and last week's graph is history rather than
// something to overwrite.
func (q *Queries) CreateUIFlow(ctx context.Context, arg CreateUIFlowParams) (UiFlow, error) {
	row := q.db.QueryRow(ctx, createUIFlow,
		arg.ProjectID,
		arg.Target,
		arg.AuthMode,
		arg.Document,
		arg.PageCount,
		arg.FlowCount,
		arg.Steps,
		arg.CutShort,
		arg.Artifacts,
		arg.ModelName,
		arg.JobID,
	)
	var i UiFlow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.AuthMode,
		&i.Document,
		&i.PageCount,
		&i.FlowCount,
		&i.Steps,
		&i.CutShort,
		&i.Artifacts,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const getUIFlow = `-- name: GetUIFlow :one
SELECT id, project_id, target, auth_mode, document, page_count, flow_count,
       steps, cut_short, artifacts, reviewed_at, reviewed_by, model_name, job_id, created_at
FROM ui_flows
WHERE id = $1
`

func (q *Queries) GetUIFlow(ctx context.Context, id uuid.UUID) (UiFlow, error) {
	row := q.db.QueryRow(ctx, getUIFlow, id)
	var i UiFlow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.AuthMode,
		&i.Document,
		&i.PageCount,
		&i.FlowCount,
		&i.Steps,
		&i.CutShort,
		&i.Artifacts,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const latestUIFlow = `-- name: LatestUIFlow :one
SELECT id, project_id, target, auth_mode, document, page_count, flow_count,
       steps, cut_short, artifacts, reviewed_at, reviewed_by, model_name, job_id, created_at
FROM ui_flows
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestUIFlow(ctx context.Context, projectID uuid.UUID) (UiFlow, error) {
	row := q.db.QueryRow(ctx, latestUIFlow, projectID)
	var i UiFlow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.AuthMode,
		&i.Document,
		&i.PageCount,
		&i.FlowCount,
		&i.Steps,
		&i.CutShort,
		&i.Artifacts,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}

const listUIFlows = `-- name: ListUIFlows :many
SELECT id, project_id, target, auth_mode, page_count, flow_count,
       steps, cut_short, reviewed_at, reviewed_by, model_name, created_at
FROM ui_flows
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUIFlowsParams struct {
	ProjectID uuid.UUID
	PageSize  int32
}

type ListUIFlowsRow struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Target     string
	AuthMode   string
	PageCount  int32
	FlowCount  int32
	Steps      int32
	CutShort   bool
	ReviewedAt *time.Time
	ReviewedBy *uuid.UUID
	ModelName  string
	CreatedAt  time.Time
}

// ListUIFlows is the history. The document is left out: a list screen shows the
// counts and the date, and shipping forty graphs to render ten rows is a page nobody
// waits for.
func (q *Queries) ListUIFlows(ctx context.Context, arg ListUIFlowsParams) ([]ListUIFlowsRow, error) {
	rows, err := q.db.Query(ctx, listUIFlows, arg.ProjectID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUIFlowsRow{}
	for rows.Next() {
		var i ListUIFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Target,
			&i.AuthMode,
			&i.PageCount,
			&i.FlowCount,
			&i.Steps,
			&i.CutShort,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ModelName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUIFlowReviewed = `-- name: MarkUIFlowReviewed :one
UPDATE ui_flows
SET reviewed_at = now(), reviewed_by = $2
WHERE id = $1
RETURNING id, project_id, target, auth_mode, document, page_count, flow_count,
          steps, cut_short, artifacts, reviewed_at, reviewed_by, model_name, job_id, created_at
`

type MarkUIFlowReviewedParams struct {
	ID         uuid.UUID
	ReviewedBy *uuid.UUID
}

// MarkUIFlowReviewed records that a person has read the graph, so generating from an
// unreviewed one is a visible choice rather than an invisible default (BE-7.2.3).
func (q *Queries) MarkUIFlowReviewed(ctx context.Context, arg MarkUIFlowReviewedParams) (UiFlow, error) {
	row := q.db.QueryRow(ctx, markUIFlowReviewed, arg.ID, arg.ReviewedBy)
	var i UiFlow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.AuthMode,
		&i.Document,
		&i.PageCount,
		&i.FlowCount,
		&i.Steps,
		&i.CutShort,
		&i.Artifacts,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ModelName,
		&i.JobID,
		&i.CreatedAt,
	)
	return i, err
}
