// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE user_invitations
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearAccountLock = `-- name: ClearAccountLock :execrows
DELETE FROM account_locks WHERE email = lower($1::text)
`

func (q *Queries) ClearAccountLock(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, clearAccountLock, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentFailedAttempts = `-- name: CountRecentFailedAttempts :one
SELECT count(*)
FROM login_attempts
WHERE lower(email) = lower($1::text)
  AND succeeded = false
  AND attempted_at > $2::timestamptz
`

type CountRecentFailedAttemptsParams struct {
	Email string
	Since time.Time
}

func (q *Queries) CountRecentFailedAttempts(ctx context.Context, arg CountRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAttempts, arg.Email, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedAttemptsByIP = `-- name: CountRecentFailedAttemptsByIP :one
SELECT count(*)
FROM login_attempts
WHERE ip = $1::inet
  AND succeeded = false
  AND attempted_at > $2::timestamptz
`

type CountRecentFailedAttemptsByIPParams struct {
	Ip    netip.Addr
	Since time.Time
}

func (q *Queries) CountRecentFailedAttemptsByIP(ctx context.Context, arg CountRecentFailedAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAttemptsByIP, arg.Ip, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// CountUsers backs the first-run check: the setup endpoint is available only while
// no user exists, then permanently 404.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO user_invitations (user_id, token_hash, expires_at, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, accepted_at, invited_by, created_at
`

type CreateInvitationParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	InvitedBy *uuid.UUID
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedBy,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, role, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email    string
	Name     string
	Role     UserRole
	Timezone string
}

// Users, invitations, and login throttling.
//
// Explicit column lists everywhere. SELECT * is a review failure: an added column
// must not silently change the API surface or pull a credential into memory.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Timezone,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :execrows
DELETE FROM user_invitations
WHERE accepted_at IS NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvitations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleLoginAttempts = `-- name: DeleteStaleLoginAttempts :execrows
DELETE FROM login_attempts WHERE attempted_at < $1::timestamptz
`

func (q *Queries) DeleteStaleLoginAttempts(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleLoginAttempts, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountLock = `-- name: GetAccountLock :one
SELECT email, locked_at, locked_until, reason
FROM account_locks
WHERE email = lower($1::text) AND locked_until > now()
`

func (q *Queries) GetAccountLock(ctx context.Context, email string) (AccountLock, error) {
	row := q.db.QueryRow(ctx, getAccountLock, email)
	var i AccountLock
	err := row.Scan(
		&i.Email,
		&i.LockedAt,
		&i.LockedUntil,
		&i.Reason,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, user_id, token_hash, expires_at, accepted_at, invited_by, created_at
FROM user_invitations
WHERE token_hash = $1
`

// GetInvitationByTokenHash looks up by hash, never by the token itself: a leaked
// database must not yield working invitation links.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Timezone,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Timezone,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
FROM users
WHERE ($1::timestamptz IS NULL OR created_at < $1::timestamptz)
ORDER BY created_at DESC
LIMIT $2
`

type ListUsersParams struct {
	Cursor   *time.Time
	PageSize int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Timezone,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
FROM users
WHERE role = $1 AND disabled_at IS NULL
ORDER BY created_at
`

// ListUsersByRole backs admin fan-out: a degraded integration raises an alert for
// every admin, and a disabled account is not somebody who will read it.
func (q *Queries) ListUsersByRole(ctx context.Context, role UserRole) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Timezone,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :exec
INSERT INTO account_locks (email, locked_until, reason)
VALUES (lower($1::text), $2::timestamptz, $3::text)
ON CONFLICT (email) DO UPDATE
SET locked_at = now(), locked_until = EXCLUDED.locked_until, reason = EXCLUDED.reason
`

type LockAccountParams struct {
	Email       string
	LockedUntil time.Time
	Reason      string
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) error {
	_, err := q.db.Exec(ctx, lockAccount, arg.Email, arg.LockedUntil, arg.Reason)
	return err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (email, ip, succeeded, user_agent)
VALUES ($1, $2, $3, $4)
`

type RecordLoginAttemptParams struct {
	Email     string
	Ip        *netip.Addr
	Succeeded bool
	UserAgent string
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt,
		arg.Email,
		arg.Ip,
		arg.Succeeded,
		arg.UserAgent,
	)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users
SET disabled_at = $2, updated_at = now()
WHERE id = $1
`

type SetUserDisabledParams struct {
	ID         uuid.UUID
	DisabledAt *time.Time
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.DisabledAt)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users
SET role = $2, updated_at = now()
WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role UserRole
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2, timezone = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, name, role, password_hash, timezone, disabled_at, last_login_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID
	Name     string
	Timezone string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Timezone,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
